(function(g){var window=this;var SY=function(a){a.g||(a.g=new g.Ao,g.H(a,a.g));return a.g},TY=function(a){a.M("cardstatechange",a.ud()&&a.ue()?1:0)},UY=function(a){var b=g.Hh(a);
a=g.Oh(a);return new g.jh(b.x,b.y,a.width,a.height)},VY=function(a,b){var c=a.style;
"opacity"in c?c.opacity=b:"MozOpacity"in c?c.MozOpacity=b:"filter"in c&&(c.filter=""===b?"":"alpha(opacity="+100*Number(b)+")")},WY=function(a){return"none"!=a.style.display},XY=function(a,b){if(/^\d+px?$/.test(b))return parseInt(b,10);
var c=a.style.left,d=a.runtimeStyle.left;a.runtimeStyle.left=a.currentStyle.left;a.style.left=b;var e=a.style.pixelLeft;a.style.left=c;a.runtimeStyle.left=d;return+e},cna=function(a){var b=g.Bh(a,"fontSize");
var c=(c=b.match($ma))&&c[0]||null;if(b&&"px"==c)return parseInt(b,10);if(g.Md){if(String(c)in ana)return XY(a,b);if(a.parentNode&&1==a.parentNode.nodeType&&String(c)in bna)return a=a.parentNode,c=g.Bh(a,"fontSize"),XY(a,b==c?"1em":b)}c=g.Rd("SPAN",{style:"visibility:hidden;position:absolute;line-height:0;padding:0;margin:0;border:0;height:1em;"});a.appendChild(c);b=c.offsetHeight;g.Xd(c);return b},dna=function(a){if(/-[a-z]/.test("pollChoiceIndex"))return null;
if(g.Ak&&a.dataset){if(g.jc()&&!("pollChoiceIndex"in a.dataset))return null;a=a.dataset.pollChoiceIndex;return void 0===a?null:a}return a.getAttribute("data-"+g.vc("pollChoiceIndex"))},$Y=function(a){a=g.Qa(a);
delete YY[a];g.Xb(YY)&&ZY&&ZY.stop()},aZ=function(){ZY||(ZY=new g.M(function(){ena()},20));
var a=ZY;a.isActive()||a.start()},ena=function(){var a=(0,g.C)();
g.Kb(YY,function(b){bZ(b,a)});
g.Xb(YY)||aZ()},cZ=function(a,b){g.sf.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.D;this.state=b.g},dZ=function(a,b,c,d){g.Zn.call(this);
if(!g.La(a)||!g.La(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.i=a;this.F=b;this.duration=c;this.B=d;this.coords=[];this.progress=this.D=0;this.A=null},bZ=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.D=1E3/(b-a.A);a.A=b;eZ(a,a.progress);1==a.progress?(a.g=0,$Y(a),a.Xc(),a.l()):1==a.g&&a.qr()},eZ=function(a,b){g.Na(a.B)&&(b=a.B(b));
a.coords=Array(a.i.length);for(var c=0;c<a.i.length;c++)a.coords[c]=(a.F[c]-a.i[c])*b+a.i[c]},fZ=function(a,b,c,d,e){dZ.call(this,b,c,d,e);
this.element=a},gZ=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
fZ.call(this,a,b,c,d,e)},fna=function(a){return Math.pow(a,3)},gna=function(a){return 3*a*a-2*a*a*a},hZ=function(a){g.G.call(this);
this.i=a||window;this.g=[]},hna=function(a,b,c,d){c=(0,g.z)(c,d||a.i);
b=g.Fr(b,"change",c,"iv-card-poll-choice-input");a.g.push(b)},iZ=function(a,b){(0,g.B)(b,function(c){g.vs("visualElementShown",{csn:a,
ve:g.Es(c),eventType:4},g.As,void 0,void 0)})},jZ=function(a,b){(0,g.B)(b,function(c){g.vs("visualElementHidden",{csn:a,
ve:g.Es(c),eventType:8},g.As,void 0,void 0)})},kZ=function(a,b,c){this.id=a;
this.timestamp=b.timestamp||0;this.type=b.card_type;this.teaserText=b.teaser_text;this.teaserDurationMs=b.teaser_duration_ms;this.startMs=b.start_ms;this.autoOpen=b.auto_open||!1;this.Yc=b.session_data||{};this.l=c;this.sponsored=b.sponsored||!1;a=b.tracking||{};this.i={uD:a.impression,click:a.click,close:a.close,RL:a.teaser_impression,os:a.teaser_click};b=b.tracking_params||{};this.A=g.Ds(b.card);this.D=g.Ds(b.teaser);this.u=g.Ds(b.icon)},lZ=function(a,b){g.Qf.call(this);
this.xj=a;this.zp=b;this[g.uf]=!1},qZ=function(a,b,c,d){lZ.call(this,a,b);
a=this.zp;b=this.ka();c?(b.setAttribute("stroke",c.i),b.setAttribute("stroke-opacity",1),c=c.g,g.v(c)&&-1!=c.indexOf("px")?b.setAttribute("stroke-width",parseFloat(c)/ina(a)):b.setAttribute("stroke-width",c)):b.setAttribute("stroke","none");this.fill=d;c=this.zp;a=this.ka();if(d instanceof mZ)a.setAttribute("fill",d.F),a.setAttribute("fill-opacity",d.H);else if(d instanceof nZ){b="lg-"+d.u+"-"+d.B+"-"+d.A+"-"+d.D+"-"+d.g+"-"+d.i;var e=b in c.g?c.g[b]:null;if(!e){e=oZ(c,"linearGradient",{x1:d.u,y1:d.B,
x2:d.A,y2:d.D,gradientUnits:"userSpaceOnUse"});var f="stop-color:"+d.g;g.Da(d.l)&&(f+=";stop-opacity:"+d.l);f=oZ(c,"stop",{offset:"0%",style:f});e.appendChild(f);f="stop-color:"+d.i;g.Da(d.o)&&(f+=";stop-opacity:"+d.o);d=oZ(c,"stop",{offset:"100%",style:f});e.appendChild(d);e=pZ(c,b,e)}a.setAttribute("fill","url(#"+e+")")}else a.setAttribute("fill","none")},rZ=function(){},sZ=function(a,b){lZ.call(this,a,b)},tZ=function(){this.Ta=[];
this.Ba=[];this.Nd=[]},uZ=function(a,b,c,d){var e=a.xd[0]-b*Math.cos(g.td(d))+b*Math.cos(g.td(d+90)),f=a.xd[1]-c*Math.sin(g.td(d))+c*Math.sin(g.td(d+90));
a.Ta.push(3);a.Ba.push(1);a.Nd.push(b,c,d,90,e,f);a.Ck=!1;a.xd=[e,f]},kna=function(a,b){for(var c=a.Nd,d=0,e=0,f=a.Ta.length;e<f;e++){var k=a.Ta[e],l=jna[k]*a.Ba[e];
b(k,c.slice(d,d+l));d+=l}},vZ=function(a,b,c,d){qZ.call(this,a,b,c,d)},wZ=function(a,b){this.g=a;
this.i=b},xZ=function(a,b,c,d,e){g.ko.call(this,e);
this.width=a;this.height=b;this.l=c||null;this.I=d||null},ina=function(a){var b=a.nj();
return b?b.width/(a.l?new g.xd(a.l,a.I):a.nj()).width:0},nZ=function(a,b,c,d,e,f,k,l){this.u=a;
this.B=b;this.A=c;this.D=d;this.g=e;this.i=f;this.l=g.Ba(k)?k:null;this.o=g.Ba(l)?l:null},mZ=function(a,b){this.F=a;
this.H=null==b?1:b},yZ=function(a,b){lZ.call(this,a,b)},zZ=function(a,b,c,d){qZ.call(this,a,b,c,d)},AZ=function(a,b,c,d,e){xZ.call(this,a,b,c,d,e);
this.g={};this.O=g.Od&&!g.Cc(526);this.P=new g.bn(this)},oZ=function(a,b,c){a=a.N.g.createElementNS("http://www.w3.org/2000/svg",b);
if(c)for(var d in c)a.setAttribute(d,c[d]);return a},BZ=function(a,b,c,d){b=oZ(a,"path",{d:lna(b)});
c=new zZ(b,a,c,d);a.o.ka().appendChild(c.ka())},lna=function(a){var b=[];
kna(a,function(c,d){switch(c){case 0:b.push("M");Array.prototype.push.apply(b,d);break;case 1:b.push("L");Array.prototype.push.apply(b,d);break;case 2:b.push("C");Array.prototype.push.apply(b,d);break;case 3:var e=d[3];b.push("A",d[0],d[1],0,180<Math.abs(e)?1:0,0<e?1:0,d[4],d[5]);break;case 4:b.push("Z")}});
return b.join(" ")},pZ=function(a,b,c){if(b in a.g)return a.g[b];
var d="_svgdef_"+mna++;c.setAttribute("id",d);a.g[b]=d;a.B.appendChild(c);return d},nna=function(){CZ||(CZ=new g.Cg(400),CZ.start());
return CZ},DZ=function(a,b){function c(l){return l.baseUrl}
function d(l){if(l){var m=l.simpleText;if(m)return m;if(l.runs)return(0,g.F)(l.runs,function(n){return n.text}).join("")}}
function e(l){if(l){var m=[],n=l.videoId;n&&m.push("v="+n);(n=l.playlistId)&&m.push("list="+n);(l=l.startTimeSeconds)&&m.push("t="+l);return"/watch?"+m.join("&")}}
var f={};f.startMs=parseInt(a.startMs,10);f.impressionUrls=(0,g.F)(a.impressionUrls||[],c);f.skip=a.skipEndscreen;a.trackingParams&&(f.visualElement=g.Ds(a.trackingParams));var k=(0,g.F)(a.elements||[],function(l,m){var n=l.endscreenElementRenderer;if(!n)return null;var p={},r=n.style,u=n.endpoint||{};p.id="element-"+m;p.type=r;p.title=d(n.title);p.metadata=d(n.metadata);p.callToAction=d(n.callToAction);p.Nu=n.image;p.left=parseFloat(n.left);p.width=parseFloat(n.width);p.top=parseFloat(n.top);p.aspectRatio=
parseFloat(n.aspectRatio);p.startMs=parseInt(n.startMs,10);p.endMs=parseInt(n.endMs,10);p.clickUrls=(0,g.F)(u.loggingUrls||[],c);p.dl=g.Sb(n,"title","accessibility","accessibilityData","label");p.impressionUrls=(0,g.F)(n.impressionUrls||[],c);p.sD=(0,g.F)(n.hovercardShowUrls||[],c);p.Yc={itct:n.trackingParams};p.visualElement=g.Ds(n.trackingParams);if("VIDEO"==r)p.targetUrl=u.urlEndpoint?u.urlEndpoint.url:e(u.watchEndpoint),p.Yl=!1,p.Mn=b,p.videoDuration=d(n.videoDuration);else if("PLAYLIST"==r)p.targetUrl=
u.urlEndpoint?u.urlEndpoint.url:e(u.watchEndpoint),p.Yl=!1,p.Mn=b,p.playlistLength=d(n.playlistLength);else if("CHANNEL"==r){if(r=g.Sb(u,"browseEndpoint","browseId"))p.channelId=r,p.targetUrl="/channel/"+r;p.Yl=!1;p.Mn="new";p.isSubscribe=!!n.isSubscribe;if(p.isSubscribe){a:{if(r=n.hovercardButton)if(r=r.subscribeButtonRenderer){u=d(r.unsubscribedButtonText);var y=d(r.subscribedButtonText);if(r.subscribed){var D=d(r.subscriberCountWithUnsubscribeText);var E=d(r.subscriberCountText)}else D=d(r.subscriberCountText),
E=d(r.subscriberCountWithSubscribeText);var K=null;if(n.signinEndpoint&&(K=g.Sb(n,"signinEndpoint","webNavigationEndpointData","url"),!K)){n=void 0;break a}if(u&&(y||K)){n={subscribed:r.subscribed,subscribeText:u,subscribeCount:D,unsubscribeText:y,unsubscribeCount:E,enabled:r.enabled,signinUrl:K,classic:n.useClassicSubscribeButton};break a}}n=void 0}p.subscribeButton=n}else p.subscribersText=d(n.subscribersText)}else"WEBSITE"==r&&(p.targetUrl=g.Sb(u,"urlEndpoint","url"),p.Yl=!0,p.Mn="new",p.iconUrl=
n.icon.thumbnails[0].url);return p});
f.elements=(0,g.Yd)(k,function(l){return!!l});
return f},EZ=function(a){g.TJ.call(this,a);
this.i=null;this.H=!1;this.o=null;this.g={};this.B={};this.A=this.l=null;this.I=[];a=g.V(a);this.P=g.wy(a)||g.yy(a);this.Yz=!0;this.D=0;this.F=new g.Pn;this.u=new g.Jr(this);g.H(this,this.u);this.u.K(this.player,g.pD("creatorendscreen"),this.oE);this.u.K(this.player,"crx_creatorendscreen",this.pE);this.u.K(this.player,"resize",this.ob);this.u.K(window,"focus",this.ZK);this.load();var b=g.Sd("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.pf(this,function(){g.Xd(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},FZ=function(a){return a.player.getVideoData().ac?"current":a.P?"new":"current"},GZ=function(a){return"creator-endscreen-editor"===a},HZ=function(a,b){g.BJ(a.player,"creatorendscreen");
a.l&&(a.l.dispose(),a.l=null,a.A.dispose(),a.A=null);for(var c in a.g)a.g[c].dispose();a.g={};a.B={};0<a.I.length&&(a.I.forEach(function(l){l.dispose()}),a.I.length=0);
a.D=0;if((a.i=b)&&b.elements){ona(a);c=[];var d=new g.mD(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);g.V(a.player).g||(a.l=new g.T({C:"div",G:"ytp-ce-shadow"}),g.FJ(a.player,a.l.element,4),a.A=new g.qP(a.l,200));for(d=0;d<b.elements.length;++d){var e=b.elements[d],f=pna(a,e);a.g[e.id]=f;a.B[e.id]=e;g.FJ(a.player,f.element,4);var k=new g.mD(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(k);qna(a,f,e)}g.yJ(a.player,
c);a.ob()}},ona=function(a){var b=g.Ts(),c=g.Us();
c&&b&&a.i.visualElement&&g.Fs(c,b,[a.i.visualElement],void 0)},pna=function(a,b){var c=null;
switch(b.type){case "VIDEO":c={C:"div",W:["ytp-ce-element","ytp-ce-video"],L:{tabindex:"0","aria-label":b.dl||"","aria-hidden":"true"},J:[{C:"div",G:"ytp-ce-element-shadow"},{C:"div",G:"ytp-ce-covering-image",L:IZ(b)},{C:"div",G:"ytp-ce-covering-shadow-top"},{C:"a",G:"ytp-ce-covering-overlay",L:{href:b.targetUrl,tabindex:"-1"},J:[{C:"div",W:["ytp-ce-video-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],L:{dir:g.Qn(a.F,b.title||"")},U:b.title},{C:"div",G:"ytp-ce-video-duration",U:b.videoDuration}]}]};
c=new g.T(c);break;case "PLAYLIST":c={C:"div",W:["ytp-ce-element","ytp-ce-playlist"],L:{tabindex:"0","aria-label":b.dl||"","aria-hidden":"true"},J:[{C:"div",G:"ytp-ce-element-shadow"},{C:"div",G:"ytp-ce-covering-image",L:IZ(b)},{C:"div",G:"ytp-ce-covering-shadow-top"},{C:"a",G:"ytp-ce-covering-overlay",L:{href:b.targetUrl,tabindex:"-1"},J:[{C:"div",W:["ytp-ce-playlist-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],L:{dir:g.Qn(a.F,b.title||"")},U:b.title},{C:"div",G:"ytp-ce-playlist-count",J:[{C:"div",
G:"ytp-ce-playlist-icon"},{C:"div",G:"ytp-ce-playlist-count-text",U:b.playlistLength}]}]}]};c=new g.T(c);break;case "CHANNEL":c={C:"div",W:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],L:{tabindex:"0","aria-label":b.dl||"","aria-hidden":"true"},J:[{C:"div",G:"ytp-ce-element-shadow"},{C:"div",G:"ytp-ce-expanding-overlay",J:[{C:"div",G:"ytp-ce-expanding-overlay-hider"},{C:"div",G:"ytp-ce-expanding-overlay-background"},{C:"div",G:"ytp-ce-expanding-overlay-content",
J:[{C:"div",G:"ytp-ce-expanding-overlay-body",J:[{C:"div",G:"ytp-ce-expanding-overlay-body-padding",J:[{C:"a",W:["ytp-ce-channel-title","ytp-ce-link"],L:{href:b.targetUrl,target:"_blank",tabindex:"-1",dir:g.Qn(a.F,b.title||"")},U:b.title},b.subscribeButton?{C:"div",G:"ytp-ce-subscribe-container",J:[{C:"div",G:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{C:"div",G:"ytp-ce-channel-subscribers-text",U:b.subscribersText}:"",b.metadata?{C:"div",W:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],
U:b.metadata}:""]}]}]}]},{C:"div",G:"ytp-ce-expanding-image",L:IZ(b)}]};c=new g.T(c);var d=g.Fd(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton){g.J(d,"ytp-ce-subscribe-button");if(g.V(a.player).g){var e=null;var f=b.Yc.itct}else e="endscreen",f=null;e=new g.hV(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,b.subscribeButton.enabled,b.subscribeButton.classic,b.channelId,!!b.subscribeButton.subscribed,
e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.I.push(e)}break;case "WEBSITE":c={C:"div",W:["ytp-ce-element","ytp-ce-website"],L:{tabindex:"0","aria-label":b.dl||"","aria-hidden":"true"},J:[{C:"div",G:"ytp-ce-element-shadow"},{C:"div",G:"ytp-ce-expanding-overlay",J:[{C:"div",G:"ytp-ce-expanding-overlay-hider"},{C:"div",G:"ytp-ce-expanding-overlay-background"},{C:"div",G:"ytp-ce-expanding-overlay-content",J:[{C:"div",G:"ytp-ce-expanding-overlay-body",J:[{C:"div",G:"ytp-ce-expanding-overlay-body-padding",
J:[{C:"div",G:"ytp-ce-website-title",L:{dir:g.Qn(a.F,b.title||"")},U:b.title},{C:"div",G:"ytp-ce-website-metadata",U:b.metadata},{C:"a",W:["ytp-ce-website-goto","ytp-ce-link"],L:{href:b.targetUrl,target:"_blank",tabindex:"-1"},U:b.callToAction}]}]}]}]},{C:"div",G:"ytp-ce-expanding-image",L:IZ(b)},{C:"div",G:"ytp-ce-expanding-icon",L:JZ(b.iconUrl)}]},c=new g.T(c)}b.g&&g.J(c.element,"ytp-ce-placeholder");return c},IZ=function(a){if(a.Nu)var b=a.Nu.thumbnails;
return JZ(b?b[b.length-1].url:null)},JZ=function(a){return a?{style:"background-image: url("+a+")"}:{}},qna=function(a,b,c){function d(){k(1)}
function e(){k(-1)}
b.da("mouseenter",(0,g.z)(a.Dq,a,b,c));b.da("mouseleave",(0,g.z)(a.xr,a,b,c));g.V(a.player).g||b.da("click",(0,g.z)(function(l){g.J(l.element,"ytp-ce-element-hover")},a,b));
b.da("click",(0,g.z)(a.hy,a,c));b.da("keypress",(0,g.z)(a.hy,a,c));b.da("focus",(0,g.z)(function(l,m){this.Dq(l,m)},a,b,c));
b.da("blur",(0,g.z)(function(l,m){this.xr(l,m)},a,b,c));
b.da("touchstart",(0,g.z)(a.Dq,a,b,c));var f=g.Hd("ytp-ce-expanding-overlay-hider",b.element);f&&b.K(f,"touchstart",function(l){l=l||window.event;l.cancelBubble=!0;l.stopPropagation&&l.stopPropagation();g.Wn(b.element,"ytp-ce-element-hover");g.Wn(b.element,"ytp-ce-force-expand")});
b.da("keydown",(0,g.z)(function(l,m){this.Yz=9==m.keyCode&&!m.shiftKey},a,b));
var k=(0,g.z)(function(l,m,n){this.D+=n;0<this.D?(g.J(l.element,"ytp-ce-force-expand"),KZ(this,m.id,!0)):(g.Wn(l.element,"ytp-ce-force-expand"),g.Wn(l.element,"ytp-ce-element-hover"),KZ(this,m.id,!1))},a,b,c);
a=(0,g.z)(function(l,m){m&&(l.da("blur",function(){WY(m)&&this.Yz&&m.focus()}),l.K(m,"focus",d),l.K(m,"blur",e))},a,b);
a(g.Hd("ytp-sb-subscribe",b.element));a(g.Hd("ytp-sb-unsubscribe",b.element));b.da("focus",d);b.da("blur",e)},KZ=function(a,b,c){a.l&&(c?a.A.show():a.A.hide());
for(var d in a.g)d!=b&&g.L(a.g[d].element,"ytp-ce-element-shadow-show",c)},LZ=function(a,b,c){function d(){f||(e++,e==b.length&&(k.stop(),c&&c()))}
if(!b||GZ(g.V(a.player).playerStyle))c&&c();else{b=rna(a,b);var e=0,f=!1,k=new g.M(function(){f=!0;c&&c()},1E3,a);
k.start();for(a=0;a<b.length;a++)g.Sq(b[a],d)}},MZ=function(a,b,c){LZ(a,b.clickUrls,c);
(a=g.Us())&&b.Yl&&g.Hs(a,b.visualElement)},rna=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce,d=a.player.getCurrentTime().toFixed(2);
c={CPN:c,AD_CPN:c,MT:d};d=[];for(var e=0;e<b.length;e++)d.push(sna(b[e],c));return d},sna=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},NZ=function(a){return g.La(a)&&a.length?a[0]:a},OZ=function(a){var b=/.+/;
return g.v(a)&&null!=b&&null!=a&&a.match(b)?a:""},PZ=function(a,b){if(null==a)return b;
var c=parseInt(a,0);if(isNaN(c))return b;c=c.toString(16);return"#"+"000000".substring(0,6-c.length)+c},QZ=function(a){return g.v(a)?a:""},RZ=function(a,b,c){for(var d in b)if(b[d]==a)return a;
return c},SZ=function(a,b){return"true"==a||"false"==a?"true"==a:b},TZ=function(a,b){return g.v(a)?parseFloat(a):b},UZ=function(a,b,c,d,e){a=parseFloat(a);
if(null!=a&&!isNaN(a)){if(d)return g.qd(a,b,c);if(a>=b&&a<=c)return a}return e},tna=function(a){if(null==a)return 0;
if("never"==a)return-1;a=a.split(":");if(3<a.length)return 0;var b=0,c=1;(0,g.B)(a,function(d){d=parseFloat(d);0>d&&(c=-c);b=60*b+Math.abs(d)});
return c*b},VZ=function(a,b){if(null==a)return null;
if(g.Ma(a)){var c=[];(0,g.B)(a,function(e){(e=b(e))&&c.push(e)});
return c}var d=b(a);return d?[d]:[]},una=function(a){function b(c){return null!=c&&!isNaN(c)}
return(a=a?new g.gh(parseFloat(a.top),parseFloat(a.right),parseFloat(a.bottom),parseFloat(a.left)):null)&&b(a.top)&&b(a.right)&&b(a.bottom)&&b(a.left)?a:null},vna=function(a){function b(c){return(0,g.Yd)(c.split(/ +/),function(d){return""!=d})}
return null==a?[]:b(a)},wna=function(a){this.externalId=a},xna=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.g=d},WZ=function(a){if(!a)return null;
var b=g.Wc(QZ(a.value));b=g.Tc(b);if(!b)return null;var c=RZ(a.target,yna,"current");return null==c?null:new xna(b,c,SZ(a.show_link_icon,!0),null!=a.pause_on_navigation?a.pause_on_navigation:!0)},XZ=function(a){return a.value?a.value:null},zna=function(a,b,c,d){this.type=a;
this.trigger=b;this.url=c;this.subscribeData=d},Cna=function(a){if(!a)return null;
var b=RZ(a.type,Ana),c=RZ(a.trigger,Bna),d=NZ(a.url);d=WZ(d?d:null);a=NZ(a.subscribeData);var e=a?a:null;e?(a=QZ(e.external_user_id),e=QZ(e.subscription_token),a=a&&e?new wna(a):null):a=null;return b?new zna(b,c,d,a):null},YZ=function(a,b,c){var d=(c="xx"==c||"xy"==c)?640:360;
return(d+((c?a.width:a.height)-d)*b)/d},ZZ=function(a,b,c){var d=(c="xy"==c||"yy"==c)?360:640;
return(d+((c?a.height:a.width)-d)*b)/d},$Z=function(a,b,c,d,e,f,k,l,m,n,p){this.x=a;
this.y=b;this.Fi=c;this.l=d;this.t=e;this.u=f;this.A=k;this.B=l;this.o=m;this.i=n;this.g=p},a_=function(a,b){if(!a)return null;
var c=TZ(a.x,0),d=TZ(a.y,0),e=TZ(a.w,0),f=TZ(a.h,0),k=tna(a.t),l=TZ(a.d,0),m=TZ(a.px,0),n=TZ(a.py,0),p=TZ(a.scaleSlope,1),r=TZ(a.scaleSlopeX,p);p=TZ(a.scaleSlopeY,p);var u=RZ(a.scaleDimension,Dna,"xy");return b(c,d,e,f,k,l,m,n,r,p,u)},d_=function(a,b){var c=b_(b,c_(a,new g.jh(a.x,a.y,a.Fi,a.l),b.g)),d=b.g,e=c.clone();
d&&!d.contains(c)&&(c.width<d.width?e.left=g.qd(c.left,d.left,d.left+d.width-c.width):(e.left=d.left,e.width=d.width),c.height<d.height?e.top=g.qd(c.top,d.top,d.top+d.height-c.height):(e.top=d.top,e.height=d.height));return e},c_=function(a,b,c){var d=a.A,e=a.B,f=a.g?a.g:"xy",k=YZ(c,a.o,f);
a=ZZ(c,a.i,f);f=640*b.width*k/100;var l=360*b.height*a/100;return new g.jh(0==d?640*b.left*k/100:0<d?d:c.width+d-f,0==e?360*b.top*a/100:0<e?e:c.height+e-l,f,l)},e_=function(a){return a?a_(a,function(b,c,d,e,f,k,l,m,n,p,r){return new $Z(b,c,d,e,f,k,l,m,n,p,r)}):null},f_=function(a,b){this.g=a;
this.i=b||null},b_=function(a,b){var c=a.i?d_(a.i,new f_(a.g)):a.g;
var d=b.clone(),e=c.left;c=c.top;e instanceof g.ud?(d.left+=e.x,d.top+=e.y):(d.left+=e,g.Da(c)&&(d.top+=c));return d},g_=function(a,b,c,d,e,f,k,l,m,n,p,r,u){$Z.call(this,a,b,c,d,e,l,m,n,p,r,u);
this.D=f;this.F=k},Ena=function(a){if(!a)return null;
var b=TZ(a.sx,0),c=TZ(a.sy,0);return a_(a,function(d,e,f,k,l,m,n,p,r,u,y){return new g_(d,e,f,k,l,b,c,m,n,p,r,u,y)})},Fna=function(a,b,c,d,e,f,k,l,m,n,p,r,u,y){this.i=a;
this.bgColor=b;this.borderColor=c;this.borderWidth=d;this.g=e;this.A=f;this.l=k;this.textAlign=l;this.textSize=m;this.o=n;this.padding=p;this.effects=r;this.cornerRadius=u;this.u=y},h_=function(a){if(!a)return null;
var b=PZ(a.fgColor,"#1A1A1A"),c=PZ(a.bgColor,"#FFF"),d=PZ(a.borderColor,"#000"),e=UZ(a.borderWidth,0,5,!1,0),f=UZ(a.bgAlpha,0,1,!1,.8),k=PZ(a.highlightFontColor,"#F2F2F2"),l=UZ(a.highlightWidth,0,5,!1,3),m=QZ(a.textAlign),n=UZ(a.textSize,3.3,30.1,!0,3.6107),p=QZ(a.fontWeight),r=una(a.padding),u=vna(a.effects),y=UZ(a.cornerRadius,0,10,!0,0);a=NZ(a.gradient);if(a=a?a:null){var D=UZ(a.x1,0,100,!0,0),E=UZ(a.y1,0,100,!0,0),K=UZ(a.x2,0,100,!0,100),X=UZ(a.y2,0,100,!0,100),la=PZ(a.color1,"#FFF"),Ja=PZ(a.color2,
"#000");a=new Gna(D,E,K,X,la,Ja,UZ(a.opacity1,0,100,!0,100),UZ(a.opacity2,0,100,!0,0))}else a=null;return new Fna(b,c,d,e,f,k,l,m,n,p,r,u,y,a)},Gna=function(a,b,c,d,e,f,k,l){this.l=a;
this.u=b;this.o=c;this.A=d;this.g=e;this.i=f;this.B=k;this.D=l},Hna=function(a,b,c,d){this.type=a;
this.i=b;this.g=c;this.l=d},Jna=function(a){if(!a)return null;
var b=RZ(a.type,Ina,"rect"),c=VZ(a.rectRegion,e_),d=VZ(a.anchoredRegion,Ena);a=VZ(a.shapelessRegion,e_);return new Hna(b,c,d,a)},i_=function(a){return a.i&&a.i.length?a.i[0]:a.g&&a.g.length?a.g[0]:a.l&&a.l.length?a.l[0]:null},Kna=function(a,b){this.i=a;
this.g=b},Lna=function(a,b){this.state=a;
this.ref=b},j_=function(a){if(!a)return null;
var b=RZ(a.state,Mna);a=OZ(a.ref);return b?new Lna(b,a):null},Nna=function(a,b,c,d){this.g=a||[];
this.l=b||[];this.o=c;this.i=d;this.value=!1},Ona=function(a){if(!a)return null;
var b=VZ(a.condition,j_),c=VZ(a.notCondition,j_),d=SZ(a.show_delay,!1);a=SZ(a.hide_delay,!1);return b||c?new Nna(b,c,d,a):null},Pna=function(a,b,c){(0,g.B)(a.g,g.Ra(b,!1),c);
(0,g.B)(a.l,g.Ra(b,!0),c)},k_=function(a,b,c,d,e,f,k,l,m,n,p,r,u,y){this.id=a;
this.author=b;this.type=c;this.style=d;this.o=e;this.segment=f;this.l=k||[];this.B=l||[];this.i=m;this.A=n;this.u=p;this.data=r;this.g=u;this.itct=y},Sna=function(a){if(!a)return null;
var b=OZ(a.id),c=OZ(a.author),d=RZ(a.type,Qna),e=RZ(a.style,l_),f=QZ(NZ(a.TEXT)),k=QZ(a.data);k=0!=k.length?JSON.parse(k):{};var l=NZ(a.segment);var m=l?l:null;m?(OZ(m.timeRelative),l=OZ(m.spaceRelative),l=(m=VZ(m.movingRegion,Jna))?new Kna(l,m):null):l=null;m=VZ(a.action,Cna);var n=VZ(a.trigger,Ona),p=NZ(a.appearance);(p=h_(p?p:null))||(p=h_({}));var r=RZ(a.coordinate_system,Rna,"video_relative"),u=SZ(a.closeable,!0),y=QZ(a.log_data);a=QZ(a.itct);return b&&d?new k_(b,c,d,e,f,l,m,n,p,r,u,k,y,a):null},
n_=function(a){return m_(a,function(b){return"click"==b.trigger})},m_=function(a,b){return(0,g.Nj)(a.l,b,void 0)},Tna=function(a,b,c){(0,g.B)(a.l,b,c)},Una=function(a,b){return g.Xa(a.l,b,void 0)},o_=function(a,b,c){(0,g.B)(a.B,b,c)},Vna=function(a,b){(0,g.F)(a.B,b,void 0)},q_=function(a){return(a=p_(a))?i_(a):null},p_=function(a){a.segment?(a=a.segment,a=a.g.length?a.g[0]:null):a=null;
return a},r_=function(a,b){var c=q_(a);
return c&&b?ZZ(b,c.i,c.g?c.g:"xy"):1},t_=function(a,b,c){this.g={};
this.l=!1;this.u="ivTrigger:"+a;this.i=c;Pna(b,function(d,e){var f=s_(e.state,e.ref);this.i.subscribe(f,(0,g.z)(this.o,this,f,d));this.g[f]=d},this)},s_=function(a,b){var c="ivTriggerCondition:"+a;
return b?c+":"+b:c},u_=function(){this.g=!1;
this.u=this.i=null},v_=function(a,b,c){a.i?(a.i.setSize(b,c),a.i.clear()):(b=new AZ(b,c,void 0,void 0,void 0),a.i=b,a.i.Ep(),a.u=g.Rd("DIV"),a.u.appendChild(a.i.ka()));
return a.i},w_=function(a,b,c){var d=document.createElementNS("http://www.w3.org/2000/svg",a);
b&&g.Kb(b,function(f,k){d.setAttribute(k,f)});
for(var e=2;e<arguments.length;e++)d.appendChild(arguments[e]);return d},x_=function(a,b){var c=g.jo(g.io.getInstance());
b.setAttribute("result",c);a.appendChild(b);return c},Wna=function(a,b){var c=x_(a,w_("feGaussianBlur",{"in":b,
stdDeviation:"1.8"}));c=x_(a,w_("feDiffuseLighting",{"in":c,surfaceScale:"4",diffuseConstant:"1"},w_("feDistantLight",{azimuth:"270",elevation:"15","lighting-color":"white"})));c=x_(a,w_("feComposite",{"in":c,in2:b,operator:"in"}));return x_(a,w_("feComposite",{in2:c,"in":b,operator:"arithmetic",k2:1,k3:.5,k4:0}))},Xna=function(a,b){var c=x_(a,w_("feOffset",{"in":b,
dx:"-7",dy:"-7"}));c=x_(a,w_("feGaussianBlur",{"in":c,stdDeviation:"3"}));c=x_(a,w_("feColorMatrix",{"in":c,type:"matrix",values:"0 0 0 0 0  0 0 0 0 0  0 0 0 0 0  0 0 0 0.5 0"}));var d=x_(a,w_("feColorMatrix",{"in":b,type:"matrix",values:"0 0 0 0 0  0 0 0 0 0  0 0 0 0 0  0 0 0 100 0"}));d=x_(a,w_("feGaussianBlur",{"in":d,stdDeviation:"1"}));c=x_(a,w_("feComposite",{operator:"out","in":c,in2:d}));return x_(a,w_("feComposite",{operator:"over","in":b,in2:c}))},Yna=function(a,b){return b},Zna=function(a){var b=
w_("filter",{filterUnits:"userSpaceOnUse"}),c="SourceGraphic";
(0,g.B)(a,function(d){a:{switch(d){case "bevel":d=Wna;break a;case "dropshadow":d=Xna;break a}d=Yna}c=d(b,c)});
return b},$na=function(a){a=(0,g.Yd)(a,function(b){return b in y_});
g.qb(a,function(b,c){return y_[b]-y_[c]});
return a},aoa=function(a){return g.Xa(a,function(b){return"dropshadow"==b})?new g.gh(0,7,7,0):new g.gh(0,0,0,0)},z_=function(a,b,c){var d=new tZ;
d.moveTo(a.left+b+c,a.top+c);d.Zb(a.left+a.width-b-c,a.top+c);uZ(d,b,b,-90);d.Zb(a.left+a.width-c,a.top+a.height-b-c);uZ(d,b,b,0);d.Zb(a.left+b+c,a.top+a.height-c);uZ(d,b,b,90);d.Zb(a.left+c,a.top+b+c);uZ(d,b,b,180);d.close();return d},A_=function(a,b,c,d){var e=a.u;
e?a=new nZ(e.l*b/100,e.u*c/100,e.o*b/100,e.A*c/100,e.g,e.i,e.B,e.D):(b=a.g,a=new mZ(a.bgColor,d?Math.max(b,.9):b));return a},B_=function(a,b){var c=g.kh(a),d=aoa(b);
g.Oa(d)?(c.top-=d.top,c.right+=d.right,c.bottom+=d.bottom,c.left-=d.left):(c.top-=d,c.right+=Number(void 0),c.bottom+=Number(void 0),c.left-=Number(void 0));return new g.jh(c.left,c.top,c.right-c.left,c.bottom-c.top)},C_=function(a,b,c){if(c.length&&(b=g.Fd(document,"g",void 0,b),b.length)){var d=$na(c);
if(d){c="effects:"+(d?d.join("|"):"");var e=c in a.g?a.g[c]:null;e?a=e:(d=Zna(d),a=0<d.childNodes.length?pZ(a,c,d):null)}else a=null;a&&b[0].setAttribute("filter","url(#"+a+")")}},D_=function(){u_.call(this);
this.o=0},boa=function(a,b){var c=a.top-b.y,d=b.x-a.left-a.width,e=b.y-a.top-a.height,f=a.left-b.x,k=Math.max(c,d,e,f);
if(0>k)return"i";switch(k){case c:return"t";case d:return"r";case e:return"b";case f:return"l"}return"i"},E_=function(a){u_.apply(this,arguments)},F_=function(a){u_.apply(this,arguments)},G_=function(a){D_.apply(this,arguments)},H_=function(a,b,c,d,e){g.G.call(this);
this.g=a;this.R=b;this.A=c;this.X=d;this.Y=e;this.F=!1;this.ca=new hZ(this);g.H(this,this.ca);this.N=this.u=this.B=this.P=this.i=null;this.V=!1;this.aa=this.H=this.I=null;this.Qm=new g.xl(this.TC,100,this);g.H(this,this.Qm);this.D=new g.M(this.Uv,500,this);g.H(this,this.D);this.O=this.l=this.o=null},coa=function(a,b){var c=(0,g.z)(function(d,e,f){e=f?I_(this,e,(0,g.z)(f,this)):I_(this,e);
this.ca.da(b,d,e)},a);
c("mouseover","G",a.Tw);c("mouseout","F",a.pg);c("click","D");c("touchend","D")},doa=function(a){if(a.g.u){if(m_(a.g,function(d){return"close"==d.type}))var b=a.i;
else a.o=g.Rd("DIV","annotation-close-button"),g.Ph(a.o,!1),g.Ep(a.o,"annotation_id",a.g.id),a.i.appendChild(a.o),b=a.o;var c=function(d){d.stopPropagation()};
a.ca.da(b,"click",I_(a,"E",c));a.ca.da(b,"touchend",I_(a,"E",c))}},I_=function(a,b,c){return(0,g.z)(function(d){if(this.Y)c&&c(d);
else if(d.event.target instanceof Element){var e=d.event.target;g.Ph(e,!1);try{var f=document.elementFromPoint(d.event.clientX,d.event.clientY);if(g.he(f,null,"annotation",void 0)){var k=document.createEvent("MouseEvent");k.initMouseEvent(d.event.type,d.event.bubbles,d.event.cancelable,d.event.view,d.event.detail,d.event.screenX,d.event.screenY,d.event.clientX,d.event.clientY,d.event.ctrlKey,d.event.altKey,d.event.shiftKey,d.event.metaKey,d.event.button,d.event.relatedTarget);f.dispatchEvent(k)}}finally{g.Ph(e,
!0)}}e=UY(d.target);d=new g.ud(d.clientX,d.clientY);"F"==b&&e.contains(d)||this.X.M(b,this.g)},a)},L_=function(a){if(a.i||a.l){var b=q_(a.g);
if(b){var c=J_(a);if(a.i){b=d_(b,c);var d=g.pJ(a.A).getVideoContentRect();g.Nh(a.i,b.width,b.height);g.Dh(a.i,b.left,b.top);a.P=new g.jh(d.left+b.left,d.top+b.top,b.width,b.height);var e=(e=q_(a.g))&&d?YZ(d,e.o,e.g?e.g:"xy"):1;var f=r_(a.g,d);d=a.g.i;d.padding?d=d.padding:(d="speech"==a.g.style?1.6:.8,d=new g.gh(d,d,d,d));d=new g.gh(360*d.top*f/100,640*d.right*e/100,360*d.bottom*f/100,640*d.left*e/100);a.u&&(d.right+=1.5*c.g.height/100);a.i.style.padding=d.top+"px "+d.right+"px "+d.bottom+"px "+d.left+
"px";"label"==a.g.style&&a.B&&(a.B.style.padding=a.i.style.padding);d=c.g;var k=!1,l=0,m=0;var n=g.pJ(a.A).getVideoContentRect();var p=g.wJ(a.A);g.lh(n,p)?n=null:(p.top+=20,p.height-=40,"player_relative"!=a.g.A&&(p.left-=n.left,p.top-=n.top),n=p);n&&(l=n.top-(b.top+b.height),m=b.top-(n.top+n.height),k=0<l||0<m);if(k&&n){d=l;e=m;if(a.u){f=K_(a,23,b,d,e);if(a.o){var r=43-f.width;0<r&&(b.left+f.left-r>n.left&&(f.left-=r),f.width+=r)}r=f;g.Nh(a.u,f.width,f.height);g.Dh(a.u,f.left,f.top)}a.o&&(r?b=new g.ud(r.left+
r.width-23-18,a.V?r.top+2:r.top+r.height-18-2):(r=K_(a,18,b,d,e),b=new g.ud(r.left,r.top),g.Nh(a.o,r.width,r.height)),g.Dh(a.o,b));a.N=new g.jh(a.P.left+r.left,a.P.top+r.top,r.width,r.height);a.I=a.ca.da(g.pJ(a.A),"mousemove",a.cF,a)}else a.u&&(r=e/f*d.height*4.2/100,r=new g.xd(r,r),"highlight"==a.g.type||"label"==a.g.style?(e=1.5*d.height/100,r=new g.jh(b.width-r.width-e,b.height-r.height-e,r.width,r.height)):r=new g.jh(b.width-r.width-3*d.height/100,(b.height-r.height)/2,r.width,r.height),g.Nh(a.u,
r.width,r.height),g.Dh(a.u,r.left,r.top)),a.o&&(r=9<=d.left+d.width-(b.left+b.width),e=9<=b.top-d.top,g.Dh(a.o,r&&e?new g.ud(b.width-9,-9):r?new g.ud(b.width-9,45<b.height?9:b.height-9):e?new g.ud(45<b.width?b.width-9-18:-9,-9):b.width/d.width>b.height/d.height?new g.ud(45<b.width?b.width-9-18:-9,b.height-9):new g.ud(-9,45<b.height?9:b.height-9)))}a.l&&a.l.l(a.g,c);if(a.i){c=a.i;b=a.g.i;c.style.color="highlightText"==a.g.style?b.A:b.i;r=g.pJ(a.A).getVideoContentRect();c.style.fontSize=360*b.textSize*
r_(a.g,r)/100+"px";r=a.g.style;c.style.textAlign=b.textAlign?b.textAlign:"title"==r||"highlightText"==r?"center":"left";b.o&&(c.style.fontWeight=b.o);a=a.i;c=a.style.overflow;r=(b=g.Hd("annotation-link-icon",a))?WY(b):!1;e=(d=g.Hd("annotation-close-button",a))?WY(d):!1;r&&g.Ph(b,!1);e&&g.Ph(d,!1);m=f="";if(n=g.Hd("inner-text",a))f=n.style.overflow,m=n.style.position,n.style.overflow="visible",n.style.position="static";a.style.overflow="scroll";if(a.scrollHeight>a.offsetHeight||a.scrollWidth>a.offsetWidth){l=
k=cna(a);p=5;for(var u=Math.floor(k/2);u;)a.scrollHeight<=a.offsetHeight&&a.scrollWidth<=a.offsetWidth?(p=l,l=Math.min(l+u,k)):l=Math.max(l-u,p),u=Math.floor(u/2),a.style.fontSize=l+"px";l!=p&&(a.scrollHeight>a.offsetHeight||a.scrollWidth>a.offsetWidth)&&(a.style.fontSize=p+"px")}a.style.overflow=c;n&&(n.style.overflow=f,n.style.position=m);e&&g.Ph(d,!0);r&&g.Ph(b,!0)}}}},K_=function(a,b,c,d,e){var f=0<e;
b=new g.jh(0,c.height-b,Math.max(c.width,b),b);0<d&&(b.top=c.height,20<d&&(b.height+=d-20),g.J(a.i,"annotation-extend-down"));f&&(b.top=-b.height,20<e&&(c=e-20,b.top-=c,b.height+=c),g.J(a.i,"annotation-extend-up"),a.V=!0);return b},M_=function(a){return"label"!=a.g.style||a.l.g},J_=function(a){var b=g.pJ(a.A).getVideoContentRect();
if("player_relative"==a.g.A){var c=g.pJ(a.A).getPlayerSize();b=new g.jh(-b.left,-b.top,c.width,c.height)}else b=new g.jh(0,0,b.width,b.height);return new f_(b,a.O?q_(a.O):null)},N_=function(a,b){return b?new g.jh(a.x+b.left,a.y+b.top,b.width,b.height):null},O_=function(a,b,c){g.G.call(this);
this.i=a;this.annotation=b;this.view=c;this.g=null;this.l=this.isVisible=!1;eoa(b,a)},eoa=function(a,b){Vna(a,function(c){return new t_(a.id,c,b)})},P_=function(a){a.i.unsubscribe("resize",a.Sw,a);
a.i.unsubscribe("onVideoAreaChange",a.Jy,a)},Q_=function(a){a.g&&(a.g.stop(),a.g=null)},R_=function(a,b,c){kZ.call(this,a,b,c);
this.channelId=b.channel_id;this.customMessage=b.custom_message;this.profileImageUrl=b.image_url;this.title=b.title;this.metaInfo=b.meta_info;this.url=WZ({pause_on_navigation:b.pause_on_navigation,target:b.target||"new",value:b.url})},S_=function(a,b,c){kZ.call(this,a,b,c);
this.imageUrl=b.image_url;this.displayDomain=b.display_domain;this.showLinkIcon=b.show_link_icon;this.o=b.button_icon_url;this.title=b.title;this.customMessage=b.custom_message;this.url=WZ({pause_on_navigation:b.pause_on_navigation,target:b.target||"new",value:b.url});this.g=null;if(a=b.signin_url)this.g=WZ({target:"current",value:a});this.I=b.signin_title||null;this.H=b.signin_message||null},T_=function(a,b,c){S_.call(this,a,b,c);
this.F=b.ypc_flow_type;this.B=b.innertube_request_params},U_=function(a,b,c){kZ.call(this,a,b,c);
this.o=b.image_url;this.playlistVideoCount=b.playlist_video_count;this.customMessage=b.custom_message;this.title=b.title;this.metaInfo=b.meta_info;this.url=WZ({pause_on_navigation:b.pause_on_navigation,target:b.target||"new",value:b.url})},V_=function(a,b,c){kZ.call(this,a,b,c);
this.B=this.id.replace(/[^a-z0-9-]/gi,"-");this.title=b.title;this.choices=b.choices;this.g=b.hasOwnProperty("old_vote")?b.old_vote:null;this.o=null;if(a=b.signin_url)this.o=WZ({target:"current",value:a});this.F=b.hasOwnProperty("xsrf_token")?b.xsrf_token:null},W_=function(a,b,c){S_.call(this,a,b,c);
this.offers=[];a=b.offers||[];for(b=0;b<a.length;b++)this.offers.push(new foa(a[b]))},foa=function(a){this.merchant=g.qc(a.merchant);
this.price=g.qc(a.price)},X_=function(a,b,c){S_.call(this,a,b,c);
this.P=b.ypc_item_type;this.F=b.ypc_item_id;this.B=b.ypc_flow_type},Y_=function(a,b,c){kZ.call(this,a,b,c);
this.o=b.image_url;this.videoDuration=b.video_duration||null;this.customMessage=b.custom_message;this.title=b.title;this.metaInfo=b.meta_info;this.isLiveNow=!!b.is_live_now;this.url=WZ({pause_on_navigation:b.pause_on_navigation,target:b.target||"new",value:b.url})},Z_=function(a,b,c){kZ.call(this,a,b,c);
this.F=b.image_url;this.o=b.badge_symbol||"";this.priceText=b.price_text||"";this.title=b.title;this.metaInfo=b.meta_info;this.B=!!b.is_paygated;this.H=!!b.user_has_entitlement;this.url=WZ({target:b.target||"new",value:b.url})},goa=function(a){this.g=a;
this.i={}},hoa=function(a){var b={};
b=(b["iv-event"]=1,b);g.vJ(a.g,"iv",b,void 0)},c0=function(a,b,c,d){if(b){var e=$_(a,b);
a.i[b]=e["p-time"];e["iv-event"]=e.link||e["l-class"]||e["link-id"]?2:7;b=a0(a,"cta_annotation_shown",e,c);b0(a,e,ioa(b,d))}},d0=function(a,b,c,d,e,f){if(b){var k=$_(a,b);
k["iv-event"]=3;k["i-time"]=a.i[b]||"";d&&g.ec(k,d);b=a0(a,"cta_annotation_clicked",k,e);b0(a,k,b,c,f)}},e0=function(a,b){if(b){var c=$_(a,b);
c["iv-event"]=4;c["i-time"]=a.i[b]||"";var d=a0(a,"cta_annotation_closed",c);b0(a,c,d)}},ioa=function(a,b){return b?(0,g.F)(a,g.Ra(function(c,d){return g.en(d,c)},b)):a},a0=function(a,b,c,d){d=d?g.gb(d):[];
var e=c["a-type"];if(30==e||31==e&&g.Q(g.V(a.g).experiments,"enable_async_click_tracking")){a:{c=c["a-id"];a=a.g.getVideoData();if(a.Yt){if((b=a.Yt[b])&&g.Su(b)){a=g.lc("[ANNOTATION_ID]");0<=b.indexOf("[ANNOTATION_ID]")?b=b.replace("[ANNOTATION_ID]",c):0<=b.indexOf(a)&&(b=b.replace(a,c));break a}}else if(a.gn){b=g.fq(a.gn,{label:b,value:"a_id="+c});break a}b=""}b&&d.push(b)}return d},b0=function(a,b,c,d,e){var f=1,k=-1;
if(d){var l=!1;var m=function(){f--;f||l||(clearTimeout(k),l=!0,d())};
k=setTimeout(function(){l=!0;d()},1E3)}(0,g.B)(c||[],function(n){f++;
g.Sq(n,m)});
e&&(f++,0!=e&&a.g.sendVideoStatsEngageEvent(e,m));g.vJ(a.g,"iv",b,m)},$_=function(a,b){var c={};
if(b){var d=new g.Um(b);(0,g.B)(d.Fd(),function(e){c[e]=escape(d.get(e,""))})}c["p-time"]=a.g.getCurrentTime().toFixed(2);
c.ps=g.V(a.g).playerStyle;return c},f0=function(a,b,c,d,e){e=$_(a,e);
e["iv-event"]=c;b&&(e.ei=b);e["a-id"]||(e["a-id"]="card:drawer");e["a-type"]=51;b0(a,e,d)},g0=function(a,b,c,d){c&&(c=$_(a,c),c["iv-event"]=b,b0(a,c,d))},joa=function(a,b,c,d,e,f,k){this.g=a;
this.l=b;this.rb=c;this.videoData=d;this.logger=e;this.Z=f;this.i=k},h0=function(a,b,c){this.g=a;
this.o=b;this.u=c;this.i=new g.Pn},koa=function(a,b){var c=[];
(0,g.B)(b.choices,function(k){c.push({C:"li",G:b.B+"-"+k.index.toString(),J:[{C:"label",J:[{C:"input",G:"iv-card-poll-choice-input",L:{type:"checkbox",role:"radio",name:b.B+k.index.toString(),value:k.index.toString(),"data-poll-choice-index":k.index.toString()}},{C:"span",G:"iv-card-poll-choice-text",J:[{C:"span",G:"iv-card-poll-choice-percent"},i0(this,"span",void 0,k.desc)]}]},{C:"div",G:"iv-card-poll-result",J:[{C:"div",G:"iv-card-poll-result-bar"}]}]})},a);
var d={C:"ul",L:{role:"radiogroup"},J:c},e={};b.o&&(e["aria-label"]=g.FM("$POLL_TITLE - Sign in to vote.",{POLL_TITLE:b.title}));var f=["iv-card","iv-card-poll"];d=[{C:"div",G:"iv-card-content",J:[i0(a,"h2",e,b.title),{C:"form",J:[{C:"fieldset",J:[d]}]}]}];b.o&&(f.push("iv-card-unavailable"),d.push({C:"div",W:["iv-card-sign-in"],J:[{C:"h2",U:"Want to vote?"},{C:"a",W:["iv-card-sign-in-button","iv-button"],L:{href:XZ(b.o)},J:[{C:"span",W:["iv-button-content"],U:"Sign in"}]}]}));f=new g.T({C:"div",
W:f,J:d});d=f.element;j0(b,d);hna(a.g.g,d,g.Ra(a.B,b),a);(0,g.B)(g.Gd("iv-card-poll-choice-input",d),function(k){this.g.g.da(k,"focus",g.Ra(this.l,!0));this.g.g.da(k,"blur",g.Ra(this.l,!1))},a);
b.o&&(d=g.Hd("iv-card-sign-in-button",d),a.o(d,b.o,b.id,b.Yc,b.l,b.i.click,5));return f},n0=function(a,b,c,d){var e=b.displayDomain?{C:"div",
G:"iv-card-image-text",U:b.displayDomain}:"",f=k0(a,b),k=["iv-card"];b.g&&k.push("iv-card-unavailable");e=[{C:"a",G:"iv-click-target",L:{href:XZ(b.url)},J:[l0(b.imageUrl,e),{C:"div",G:"iv-card-content",J:[i0(a,"h2",void 0,b.title),f]}]}];b.g&&e.push({C:"div",W:["iv-card-sign-in"],J:[i0(a,"h2",void 0,b.I||""),{C:"p",U:b.H},{C:"a",W:["iv-card-sign-in-button","iv-button"],L:{href:XZ(b.g)},J:[i0(a,"span","iv-button-content","Sign in")]}]});k=new g.T({C:"div",W:k,J:e});m0(a,k,b,c,d);return k},p0=function(a,
b,c){var d=["yt-badge",
"standalone-ypc-badge-renderer-icon",b.H?"standalone-ypc-badge-renderer-icon-purchased":"standalone-ypc-badge-renderer-icon-available"],e={};d=b.B&&b.o?{C:"span",W:d,L:e,U:b.o}:"";c={C:"div",W:["iv-card",c],J:[{C:"a",G:"iv-click-target",L:{href:XZ(b.url)},J:[l0(b.F,d?{C:"div",G:"iv-card-image-text",J:[d,b.priceText]}:""),{C:"div",G:"iv-card-content",J:[{C:"h2",G:"iv-card-primary-link",U:b.title},o0(a,b)]}]}]};c=new g.T(c);m0(a,c,b);return c},q0=function(a,b){return b.customMessage?i0(a,"div","iv-card-message",
b.customMessage):""},l0=function(a,b){var c="background-image: url("+a+");",d=[];
b&&d.push(b);return{C:"div",G:"iv-card-image",L:{style:c},J:d}},o0=function(a,b){if(!b.metaInfo||0==b.metaInfo.length)return"";
var c=[];(0,g.B)(b.metaInfo,function(d){c.push(i0(this,"li","",d))},a);
return{C:"ul",G:"iv-card-meta-info",J:c}},i0=function(a,b,c,d){c?g.v(c)?c={"class":c}:g.La(c)&&(c={"class":c.join(" ")}):c={};
c.dir=g.Qn(a.i,d);return{C:b,L:c,U:d}},k0=function(a,b){if(!b.customMessage)return"";
var c=["iv-card-action","iv-card-primary-link"],d={};b.o&&(c.push("iv-card-action-icon"),d.style="background-image: url("+b.o+");");d.dir=g.Qn(a.i,b.customMessage);var e=[{C:"span",U:b.customMessage}];b.showLinkIcon&&(e.push("\u00a0"),e.push({C:"span",G:"iv-card-link-icon"}));return{C:"div",W:c,L:d,J:e}},j0=function(a,b){var c=0;
(0,g.B)(a.choices,function(m){c+=m.count});
c=c||1;for(var d=0;d<a.choices.length;d++){var e=a.choices[d],f=g.Hd(a.B+"-"+e.index.toString(),b);e=e.count/c;null==a.g&&(e=0);g.L(f.getElementsByTagName("label")[0],"iv-card-poll-choice-checked",a.g==d);f.getElementsByTagName("input")[0].checked=a.g==d;var k=Math.floor(100*e).toFixed(0),l=g.Hd("iv-card-poll-choice-percent",f);g.ce(l,g.FM("$PERCENT%",{PERCENT:k}));f=g.Hd("iv-card-poll-result-bar",f);g.vh(f,"transform","scaleX("+e.toFixed(2)+")")}g.L(b,"iv-card-poll-voted",null!=a.g);g.L(b,"iv-card-poll-expanded",
null!=a.g&&1<a.choices.length)},r0=function(a,b,c,d){d?(c&&a.g.videoData.sa||a.g.Z.pauseVideo(),a.g.Z.isFullscreen()&&a.g.Z.toggleFullscreen(),d0(a.g.logger,b.l,d,void 0,b.i.click,5),(a=g.Us())&&g.Hs(a,b.A)):b.url&&a.u(b.url,b.id,b.Yc,b.l,b.i.click||[],5)},m0=function(a,b,c,d,e){c.g&&s0(a,g.Gd("iv-card-sign-in-button",b.element),c,c.g,e);
c.url&&s0(a,g.Gd("iv-click-target",b.element),c,c.url,d)},s0=function(a,b,c,d,e){(0,g.B)(b,function(f){if(e){var k=(0,g.z)(function(l){l.stopPropagation();
l.preventDefault();e();return!1},this);
this.g.g.da(f,"click",k)}else d&&this.o(f,d,c.id,c.Yc,c.l,c.i.click,5)},a)},t0=function(a){var b=0;
-1!=a.indexOf("h")&&(a=a.split("h"),b=3600*a[0],a=a[1]);-1!=a.indexOf("m")&&(a=a.split("m"),b=60*a[0]+b,a=a[1]);-1!=a.indexOf("s")?(a=a.split("s"),b=1*a[0]+b):b=1*a+b;return b},v0=function(a){var b;
(b=a)&&!(b=1<a.length?"/"==a.charAt(0)&&"/"!=a.charAt(1):"/"==a)&&(b=u0(a),b="com"==b[0]&&"youtube"==b[1]||"be"==b[0]&&"youtu"==b[1]);return b?-1==a.indexOf("/redirect?"):!1},u0=function(a){a=a.replace(/^(https?:)?\/\//,"");
a=a.split("/",1);return!a||1>a.length||!a[0]?[]:a[0].toLowerCase().split(".").reverse()},loa=function(a){a=XZ(a);
if(!a)return null;a=a.replace(/https?:\/\//g,"");var b;(b=!v0(a))||(b=g.Og(g.Ng(a)[5]||null)||"",b=b.split("/"),b="/"+(1<b.length?b[1]:""),b="/watch"!=b);if(b)return null;b=g.dq(a);if(!b||!b.v)return null;if(b=b.t)return t0(b);a=a.split("#",2);return!a||2>a.length?null:(a=g.bq(a[1]))&&a.t?t0(a.t):-1},w0=function(a){a=XZ(a);
a=a.replace(/https?:\/\//g,"");return v0(a)?(a=g.dq(a))&&a.v?a.v:null:null},moa=function(a,b,c){c=c.replace(/\/(u|b)\/[0-9]+/g,"");
var d=/^[0-9]+$/;a&&d.test(a)&&(c="/b/"+a+c);b&&d.test(b)&&(c="/u/"+b+c);return c},x0=function(a,b){return b?b:v0(a)?"current":"new"},y0=function(a,b){g.G.call(this);
this.Ca=a;this.context=b;this.Js=!1;this.X=0},noa=function(a){return(0,g.C)()-a.X},ooa=function(a,b,c,d,e,f){var k=XZ(b);
if(k){var l=x0(k,b.target),m=(0,g.z)(function(){b.g&&this.context.Z.pauseVideo();var p=this.context.videoData.ac||!1,r=g.dq(k||"");p&&r&&(r.v||r.list)?g.rX(this.context.Z.app,r.v,c,r.list,!1,void 0,void 0):g.LK(k||"","current"==l?"_top":void 0,c)},a);
"new"==l&&(m(),m=null);var n={};n.interval=noa(a);d0(a.context.logger,d,m,n,e,f);v0(k)||(a=g.Us(),d=c.itct,a&&d&&g.Hs(a,g.Ds(d)))}},B0=function(a,b,c){y0.call(this,b,c);
var d=this;this.i=a;this.R=null;this.V=this.xa=this.u=this.ua=!1;this.aa=null;this.N=new g.M(g.Ga,c.rb.dd?4E3:3E3);g.H(this,this.N);this.la=new g.M(g.Ga);g.H(this,this.la);this.A=new h0(c,(0,g.z)(this.wi,this),(0,g.z)(this.nm,this));this.F=new g.T({C:"div",G:"iv-drawer",L:{id:"iv-drawer"},J:[{C:"div",G:"iv-drawer-header",L:{"aria-role":"heading"},J:[{C:"span",G:"iv-drawer-header-text"},{C:"button",W:["iv-drawer-close-button","ytp-button"],L:{"aria-label":"Hide cards",tabindex:"0"}}]},{C:"div",G:"iv-drawer-content"}]});
g.H(this,this.F);this.B=this.F.element;this.wa=new g.qP(this.F,330);g.H(this,this.wa);this.ya=g.Hd("iv-drawer-header-text",this.B);this.o=g.Hd("iv-drawer-content",this.B);this.l=[];this.na=this.O=this.D=this.Y=this.g=null;this.I=[];this.addCueRange(0,1E3*c.videoData.lengthSeconds,"",function(){d.xa&&z0(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.xa=d.u)&&A0(d)});
this.P=this.H=this.ba=null},soa=function(a,b){var c=b&&b.data&&b.data.card_type;
if(c&&C0[c]){c=new C0[c](b.id,b.data,b.g);if(!a.ua){g.Vn(a.ka(),["html5-stop-propagation","iv-drawer-manager"]);g.FJ(a.i,a.B,5);poa(a);a.O=g.Hd("ytp-cards-button",a.i.getRootNode());var d=g.Hd("iv-drawer-close-button",a.B);a.na=d;a.ua=!0}D0(a,c.id);var e=qoa(a,c);if(e){d={Hb:c,Ko:e.element,rw:!1};var f=roa(a,d);g.kb(a.l,f,0,d);e.g(a.o,f);a.pl();c.autoOpen?a.addCueRange(c.startMs,0x8000000000000,c.id,g.Ra(a.EL,d)):(e=1E3*a.context.Z.getCurrentTime(),5E3>e&&e>c.startMs&&a.Ez(d),a.addCueRange(c.startMs,
c.startMs+1,c.id,g.Ra(a.Ez,d)),E0(a))}}},toa=function(a,b){b.data.autoOpenMs&&a.addCueRange(b.data.autoOpenMs,0x8000000000000,"",function(){z0(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.data.autoCloseMs&&a.addCueRange(b.data.autoCloseMs,0x8000000000000,"",function(){A0(a)});
var c=b.data.headerText;g.ce(a.ya,c);a.O&&a.O.setAttribute("title",c);b.data.eventId&&(a.R=b.data.eventId);a.ba=g.Ds(b.data.trackingParams);a.P=g.Ds(b.data.closeTrackingParams);a.H=g.Ds(b.data.iconTrackingParams)},D0=function(a,b){var c=uoa(a,b);
c&&(c==a.g&&(a.g=null),a.i.removeCueRange(c.Hb.id),g.Xd(c.Ko),g.cb(a.l,c),a.pl(),E0(a))},z0=function(a,b,c,d){if(!a.u){a.wa.show();
a.Y=new g.M(function(){g.J(a.context.Z.getRootNode(),"ytp-iv-drawer-open")},0);
a.Y.start();a.aa=g.wr(a.o,"mousewheel",(0,g.z)(a.EE,a));a.u=!0;a.X=(0,g.C)();f0(a.context.logger,a.R,7,void 0,d&&d.Hb?d.Hb.l:void 0);var e=g.Us();e&&a.ba&&a.P&&iZ(e,[a.ba,a.P]);var f={TRIGGER_TYPE:b};(0,g.B)(a.l,function(k){k.rw||(k.rw=!0,c0(a.context.logger,k.Hb.l,k.Hb.i.uD,f));e&&iZ(e,[k.Hb.A])});
TY(a.i);c&&(a.D=new g.M(function(){a.ha=a.O;a.na.focus()},330),a.D.start())}},A0=function(a){a.u&&(a.wa.hide(),g.xr(a.aa),a.aa=null,g.Wn(a.context.Z.getRootNode(),"ytp-iv-drawer-open"),a.u=!1,TY(a.i),a.D&&a.D.stop(),a.D=new g.M(function(){a.ha&&(a.ha.focus(),a.ha=null)},330),a.D.start())},poa=function(a){var b=g.Hd("iv-drawer-close-button",a.B);
a.context.g.da(b,"click",a.XB,a);a.context.g.da(a.o,"touchend",function(){a.N.start()});
a.context.g.da(a.o,"scroll",a.gC,a);a.context.i.subscribe("onHideControls",function(){a.V=!0});
a.context.i.subscribe("onShowControls",function(){a.V=!1});
a.context.i.subscribe("onVideoAreaChange",function(){a.V=g.Un(a.i.getRootNode(),"ytp-autohide")});
a.I.push(g.Op("iv-button-shown",a.MD,a));a.I.push(g.Op("iv-button-hidden",a.LD,a));a.I.push(g.Op("iv-teaser-shown",a.PD,a));a.I.push(g.Op("iv-teaser-hidden",a.OD,a));a.I.push(g.Op("iv-teaser-clicked",a.ND,a))},qoa=function(a,b){switch(b.type){case "simple":return n0(a.A,b);
case "collaborator":var c=a.A,d={C:"div",W:["iv-card","iv-card-channel"],J:[{C:"a",W:["iv-click-target"],L:{href:XZ(b.url),"data-ytid":b.channelId},J:[l0(b.profileImageUrl),{C:"div",G:"iv-card-content",J:[q0(c,b),{C:"h2",G:"iv-card-primary-link",U:b.title},o0(c,b)]}]}]};d=new g.T(d);m0(c,d,b);return d;case "donation":return c=a.A,d=(0,g.z)(c.A,c,b),n0(c,b,d,d);case "episode":return p0(a.A,b,"iv-card-episode");case "movie":return p0(a.A,b,"iv-card-movie");case "playlist":return c=a.A,d={C:"div",W:["iv-card",
"iv-card-playlist"],J:[{C:"a",G:"iv-click-target",L:{href:XZ(b.url)},J:[l0(b.o,{C:"div",G:"iv-card-image-overlay",J:[{C:"span",G:"iv-card-playlist-video-count",U:b.playlistVideoCount.toString()}]}),{C:"div",G:"iv-card-content",J:[q0(c,b),i0(c,"h2","iv-card-primary-link",b.title),o0(c,b)]}]}]},d=new g.T(d),m0(c,d,b),d;case "poll":return koa(a.A,b);case "productListing":c=a.A;var e=0!=b.offers.length;d=["iv-card"];var f="",k=k0(c,b);e&&(d.push("iv-card-product-listing"),f="iv-card-primary-link",e=b.offers[0],
k=[],e.price&&k.push({C:"div",G:"iv-card-offer-price",U:e.price}),e.merchant&&k.push({C:"div",G:"iv-card-offer-merchant",U:e.merchant}),k={C:"div",J:k});d={C:"div",W:d,L:{tabindex:"0"},J:[{C:"a",W:["iv-card-image","iv-click-target"],L:{style:"background-image: url("+b.imageUrl+");",href:XZ(b.url),"aria-hidden":"true",tabindex:"-1"}},{C:"div",G:"iv-card-content",J:[b.sponsored?{C:"div",G:"iv-card-sponsored",J:["Sponsored",{C:"div",G:"iv-ad-info-container",J:[{C:"div",G:"iv-ad-info",U:"{{adInfo}}"},
{C:"div",G:"iv-ad-info-icon-container",J:[{C:"div",G:"iv-ad-info-icon"},{C:"div",G:"iv-ad-info-callout"}]}]}]}:"",{C:"a",G:"iv-click-target",L:{href:XZ(b.url)},J:[i0(c,"h2",f,b.title),k]}]}]};d=new g.T(d);f=g.Sd("span");g.ce(f,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");d.jb(f,"adInfo");m0(c,d,b);return d;case "tip":return c=a.A,d=(0,g.z)(c.D,c,b),n0(c,b,d,d);case "video":return c=a.A,d=b.isLiveNow?{C:"span",W:["yt-badge",
"yt-badge-live"],U:"LIVE NOW"}:"",d={C:"div",W:["iv-card","iv-card-video"],J:[{C:"a",G:"iv-click-target",L:{href:XZ(b.url)},J:[l0(b.o,b.videoDuration?{C:"span",G:"iv-card-video-duration",U:b.videoDuration}:""),{C:"div",G:"iv-card-content",J:[q0(c,b),i0(c,"h2","iv-card-primary-link",b.title),o0(c,b),d]}]}]},d=new g.T(d),m0(c,d,b),d}return null},roa=function(a,b){if(0==a.l.length)return 0;
var c=g.Ya(a.l,function(d){return b.Hb.startMs>d.Hb.startMs||b.Hb.startMs==d.Hb.startMs&&b.Hb.timestamp>=d.Hb.timestamp?!0:!1});
return-1==c?0:c+1},voa=function(a){return a.g?"productListing"==a.g.Hb.type:(0,g.Ni)(a.l,function(b){return"productListing"==b.Hb.type})},E0=function(a){g.L(a.i.getRootNode(),"ytp-cards-shopping-active",voa(a))},F0=function(a,b){if(a.F.Ea()){var c=new dZ([0,
a.o.scrollTop],[0,b.Ko.offsetTop],600,gna);a.context.l.da(c,"animate",function(d){a.o.scrollTop=d.y});
a.context.l.da(c,"finish",function(d){a.o.scrollTop=d.y});
c.play()}else g.IB(a.F,!0),a.o.scrollTop=b.Ko.offsetTop,g.IB(a.F,!1)},G0=function(a){return a.g&&a.g.Hb?a.g.Hb:a.l[0]&&a.l[0].Hb?a.l[0].Hb:null},uoa=function(a,b){return g.Xa(a.l,function(c){return c.Hb.id==b})},H0=function(a,b,c){y0.call(this,a,b);
this.annotation=c;this.isActive=!1},woa=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(a.annotation.data.start_ms,a.annotation.data.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},I0=function(a,b,c){H0.call(this,a,b,c);
this.i=null;this.D=!1;this.l=null;this.o=!1;this.u=0;this.g=this.B=this.A=null},J0=function(a,b,c){H0.call(this,a,b,c);
this.F=this.u=this.H=!1;this.B=5E3;this.o=null;this.D=g.Rd("DIV","iv-promo-contents");this.i=this.l=this.g=null;this.A=new g.M(function(){this.g.setAttribute("aria-hidden",!0);g.Ph(this.l,!1);g.Ph(this.i,!0)},700,this);
g.H(this,this.A)},xoa=function(a){var b=a.annotation.data;
if("cta"==a.annotation.style)var c=6;else if("video"==a.annotation.style||"playlist"==a.annotation.style)c=7;a.B=b.collapse_delay_ms||a.B;var d=["iv-promo","iv-promo-inactive"];a.ka().setAttribute("aria-hidden",!0);a.ka().setAttribute("aria-label","Promotion");a.ka().tabIndex=0;var e=a.annotation.Ib(),f=b.image_url;if(f){var k=g.Rd("DIV",["iv-promo-img","iv-click-target"]);f=g.Rd("IMG",{src:f,"aria-hidden":"true"});k.appendChild(f);b.video_duration&&!b.is_live?(f=g.Rd("SPAN","iv-promo-video-duration",
b.video_duration),k.appendChild(f)):b.playlist_length&&(f=g.Rd("SPAN","iv-promo-playlist-length",b.playlist_length.toString()),k.appendChild(f));e&&a.wi(k,e,a.annotation.id,b.session_data,a.annotation.g,void 0,c)}e?(f=g.Rd("A","iv-promo-txt"),g.nd(f,XZ(e)),a.g=f):a.g=g.Rd("DIV","iv-promo-txt");switch(a.annotation.style){case "cta":case "website":var l=g.Rd("P",null,g.Rd("STRONG",null,b.text_line_1));var m=g.Rd("P",null,g.Rd("SPAN","iv-promo-link",b.text_line_2));if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");
g.Q(a.context.rb.experiments,"web_action_cta_larger_ui")&&d.push("iv-promo-website-card-cta-larger-ui");var n=g.Rd("BUTTON",["iv-promo-round-expand-icon","ytp-button"]);f=g.Rd("BUTTON",["iv-button","iv-promo-button"],g.Rd("SPAN","iv-button-content",f));var p=g.Rd("DIV","iv-promo-button-container");p.appendChild(f);e&&a.wi(a.ka(),e,a.annotation.id,b.session_data,a.annotation.g,void 0,c)}g.J(a.g,"iv-click-target");e&&a.wi(a.g,e,a.annotation.id,b.session_data,a.annotation.g,void 0,c);break;case "playlist":case "video":l=
g.Rd("P",null,g.Rd("SPAN",null,b.text_line_1)),m=g.Rd("P",null,g.Rd("STRONG",null,b.text_line_2)),b.is_live&&(l=m,m=g.Rd("SPAN",["yt-badge","iv-promo-badge-live"],"LIVE NOW")),g.J(a.g,"iv-click-target"),e&&a.wi(a.g,e,a.annotation.id,b.session_data,a.annotation.g,void 0,c),d.push("iv-promo-video")}l&&a.g.appendChild(l);m&&a.g.appendChild(m);a.D.appendChild(a.g);p&&a.D.appendChild(p);c=g.Rd("DIV","iv-promo-actions");a.i=g.Rd("BUTTON",["iv-promo-expand","ytp-button"]);a.i.title="Expand";a.context.g.da(a.i,
"click",g.Ra(a.Gp,5E3),a);c.appendChild(a.i);g.Ph(a.i,!1);a.context.g.da(a.ka(),"mouseover",a.VC,a);a.context.g.da(a.ka(),"mouseout",a.UC,a);a.context.g.da(a.ka(),"touchend",g.Ra(a.Gp,5E3),a);a.l=g.Rd("BUTTON",["iv-promo-close","ytp-button"]);a.l.title="Close";a.context.g.da(a.l,"click","cta"==a.annotation.style&&b.text_line_3?a.NC:a.MC,a);c.appendChild(a.l);g.Vn(a.ka(),d);k&&(a.ka().appendChild(k),n&&k.appendChild(n));a.ka().appendChild(a.D);a.ka().appendChild(c)},K0=function(a){a.u||a.F||a.o||(g.J(a.ka(),
"iv-promo-collapsed"),a.u=!0,a.A.start())},L0=function(a){a.A.stop();
a.u&&(g.Xn(a.ka(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.u=!1,a.g&&a.g.removeAttribute("aria-hidden"),g.Ph(a.i,!1),g.Ph(a.l,!0))},N0=function(a,b){a.o||(a.o=g.Dg(function(){M0(this);
K0(this)},b,a))},M0=function(a){a.o&&(g.w.clearTimeout(a.o),a.o=null)},O0=function(a){g.TJ.call(this,a);
this.I=!1;this.H=0;this.i={};this.P={};this.D=new goa(a);this.A=new g.Jr(this);g.H(this,this.A);this.B=this.l=null;this.A.K(this.player,"onVideoAreaChange",(0,g.z)(this.M,this,"onVideoAreaChange"));this.A.K(this.player,"onHideControls",(0,g.z)(this.M,this,"onHideControls"));this.A.K(this.player,"onShowControls",(0,g.z)(this.M,this,"onShowControls"));this.A.K(this.player,"resize",(0,g.z)(this.M,this,"resize"));this.A.K(this.player,"presentingplayerstatechange",(0,g.z)(this.M,this,"presentingplayerstatechange"));
this.subscribe("onHideControls",this.mI,this);this.subscribe("onShowControls",this.mK,this);this.subscribe("presentingplayerstatechange",this.vJ,this);this.subscribe("resize",this.yr,this);this.subscribe("G",this.mE,this);this.subscribe("F",this.pg,this);this.subscribe("D",this.lH,this);this.subscribe("E",this.OH,this);g.V(this.player).I.subscribe("vast_info_card_add",this.Iy,this);this.R=new g.Jr(this);g.H(this,this.R);this.R.K(this.player,g.pD("annotations_module"),this.kE);this.R.K(this.player,
"crx_annotations_module",this.lE);this.O=g.Rd("DIV",["video-legacy-annotations","html5-stop-propagation"]);this.V=g.Rd("DIV","video-custom-annotations");this.u=new g.T({C:"div",W:["ytp-player-content","ytp-iv-player-content"]});g.H(this,this.u);g.FJ(this.player,this.u.element,4);this.u.hide();this.o=new g.T({C:"div",W:["ytp-iv-video-content"]});g.H(this,this.o);g.Ud(this.o.element,g.Rd("DIV","video-annotations",this.O,this.V));this.F=this.g=null;this.N=[];yoa(this)&&this.load();var b=g.Sd("STYLE");
(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.pf(this,function(){g.Xd(b)});
if(a=b.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},P0=function(a){switch(a){case "annotation-editor":case "live-dashboard":return!0}return!1},yoa=function(a){var b=g.V(a.player);
a=a.player.getVideoData();return 1==(b.Lf||a.Lf)&&!a.DA||null!==b.I.get(a.videoId)},Q0=function(a,b,c){a.I=!0;
a.B=g.wq(b,c)},R0=function(a,b){for(var c={},d=0;d<b.attributes.length;d++){var e=b.attributes[d];
c[e.name]=e.nodeValue}for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],e.tagName){if(c[e.tagName])var f=c[e.tagName];else if("data"==e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"==typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"==e.tagName?1==e.childNodes.length&&3==e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(R0(a,e))}return c},S0=function(a,b,c){return!(a.loaded&&a.H==b&&a.player.getVideoData().videoId==
c)},Aoa=function(a,b){var c=zoa(a,b);
if(!c&&"marker"!=b.type)return null;o_(b,function(e){e=(0,g.z)(this.KK,this,b.id,e);this.subscribe("ivTrigger:"+b.id,e)},a);
var d=new O_(a.wa,b,c);g.H(d,c);return d},Boa=function(a,b){var c=g.Rd("DIV",["annotation",
"annotation-type-custom"]);g.Ph(c,!1);var d=null;switch(b.type){case "branding":if(g.V(a.player).Ec)break;a.u.element.appendChild(c);d=new I0(c,T0(a),b);break;case "promotion":g.FJ(a.player,c,4),d=new J0(c,T0(a),b)}d&&d.Gn();return d},Coa=function(a){var b=a.player.getVideoData();
if(b.Dd){var c=g.V(a.player),d=c.I.get(b.videoId);if(d){var e={format:"XML",Dc:{},method:"POST",withCredentials:!0};"gaming"==c.playerStyle&&(e.Dc.gaming="1");e.Xc=(0,g.z)(function(f,k,l){S0(this,f,k)||(f=g.qq(l)&&l.responseXML?l.responseXML:null)&&U0(this,f)},a,a.H,b.videoId);
g.ms()&&(e.Xc=V0(a,e.Xc));e.qb={ic_only:"1"};W0(e,d);a.I=!0;g.wq(b.Dd,e)}}},W0=function(a,b){a.method="POST";
a.qb=a.qb||{};b.ul&&(a.qb.ic_coll=b.ul);b.vl&&(a.qb.ic_xml=b.vl);b.ys&&(a.qb.ic_track=b.ys)},Doa=function(a){var b=new g.T({C:"div"});
g.Ph(b.element,!1);var c=new B0(a.player,b.element,T0(a));g.H(c,b);b.g(a.u.element);c.Gn();return c},T0=function(a){if(!a.F){var b=new hZ(a);
g.H(a,b);var c=new g.bn(a);g.H(a,c);a.F=new joa(b,c,g.V(a.player),a.player.getVideoData(),a.D,a.player,a.wa)}return a.F},U0=function(a,b){var c=!1;
Eoa(b);for(var d=b.getElementsByTagName("annotation"),e=0;e<d.length;e++){var f=R0(a,d[e]),k=null;try{k=Sna(f)}catch(l){}if(k){a:{switch(k.type){case "branding":case "promotion":f=!0;break a}f=!1}if(f){if(f=Boa(a,k))g.H(a,f),a.P[k.id]=f}else if("card"==k.type||"drawer"==k.type)a.g||(a.g=Doa(a),g.H(a,a.g)),"card"==k.type?soa(a.g,k):toa(a.g,k),c=!0;else if(f=Aoa(a,k))g.H(a,f),a.i[k.id]=f}}c&&(TY(a.player),a.yr());g.Kb(a.i,function(l){if(l.view){var m=l.annotation;(l=l.view)&&m.segment&&m.segment.i&&
(m=this.i[m.segment.i])&&(l.O=m.annotation)}},a)},Eoa=function(a){if((a=a.getElementsByTagName("annotations"))&&!(1>a.length)&&(a=a[0].getAttribute("itct"))){var b=g.Us();
if(b){var c=g.Ts();c&&g.Fs(b,c,[g.Ds(a)])}}},Foa=function(a,b,c,d){d?X0(a,b,c):Y0(a,b,c)},Y0=function(a,b,c){if(b=a.i[b])Q_(b),c&&c.i?(a=(0,g.z)(a.Tv,a,b),b.g=new g.M(a,2E3),b.g.start()):a.Tv(b)},X0=function(a,b,c){if(b=a.i[b])Q_(b),c&&c.o?(a=(0,g.z)(a.Qz,a,b),b.g=new g.M(a,2E3),b.g.start()):a.Qz(b)},Z0=function(a,b){var c=a.player.getVideoData();
if(!c.jl)return!1;var d=XZ(b);if(!d)return!1;d=d.replace(/https?:\/\//g,"");if(!v0(d))return!1;d=g.dq(d);return d.list||d.p?!1:(d=w0(b))?c.videoId==d?!0:"new"!=b.target&&g.V(a.player).i?!0:!1:!1},zoa=function(a,b){if(Goa(b)){var c=b.u||m_(b,function(d){return"click"==d||"rollOut"==d||"rollOut"==d});
return new H_(b,(0,g.z)(a.O.appendChild,a.O),a.player,a.wa,c)}return null},Goa=function(a){if("highlight"==a.type||"widget"==a.type)return!0;
if("text"==a.type)for(var b in l_)if(a.style==l_[b])return!0;return!1},$0=function(a,b,c,d){a.M(s_(b,d),c,d)},V0=function(a,b){return(0,g.z)(function(){if(!this.ea()){var c=Array.prototype.slice.call(arguments,0);
c.unshift(b);b=g.Ra.apply(window,c);this.N.push(g.ks(b))}},a)};
g.jJ.prototype.si=g.ca(14,function(a,b){var c=g.kJ(this).l;c&&c.si(a,b)});
g.ko.prototype.Ep=g.ca(0,function(){this.i=this.N.createElement("DIV")});
var $ma=/[^\d]+$/,ana={cm:1,"in":1,mm:1,pc:1,pt:1},bna={em:1,ex:1},YY={},ZY=null;g.A(cZ,g.sf);g.A(dZ,g.Zn);g.h=dZ.prototype;g.h.getDuration=function(){return this.duration};
g.h.play=function(a){if(a||0==this.g)this.progress=0,this.coords=this.i;else if(1==this.g)return!1;$Y(this);this.startTime=a=(0,g.C)();-1==this.g&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.A=this.startTime;this.progress||this.o();this.Qd("play");-1==this.g&&this.Qd("resume");this.g=1;var b=g.Qa(this);b in YY||(YY[b]=this);aZ();bZ(this,a);return!0};
g.h.stop=function(a){$Y(this);this.g=0;a&&(this.progress=1);eZ(this,this.progress);this.Qd("stop");this.l()};
g.h.pause=function(){1==this.g&&($Y(this),this.g=-1,this.Qd("pause"))};
g.h.T=function(){0==this.g||this.stop(!1);this.Qd("destroy");dZ.Ga.T.call(this)};
g.h.destroy=function(){this.dispose()};
g.h.qr=function(){this.Qd("animate")};
g.h.Qd=function(a){this.dispatchEvent(new cZ(a,this))};
g.A(fZ,dZ);fZ.prototype.u=g.Ga;fZ.prototype.qr=function(){this.u();fZ.Ga.qr.call(this)};
fZ.prototype.l=function(){this.u();fZ.Ga.l.call(this)};
fZ.prototype.o=function(){this.u();fZ.Ga.o.call(this)};
g.A(gZ,fZ);gZ.prototype.u=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};
g.t(hZ,g.G);hZ.prototype.da=function(a,b,c,d){c=(0,g.z)(c,d||this.i);a=g.wr(a,b,c);this.g.push(a);return a};
hZ.prototype.om=function(a,b,c,d){c=(0,g.z)(c,d||this.i);a=g.Gr(a,b,c);this.g.push(a);return a};
hZ.prototype.Na=function(a){g.xr(a);g.cb(this.g,a)};
hZ.prototype.T=function(){g.xr(this.g);this.g.length=0;g.G.prototype.T.call(this)};g.A(lZ,g.Qf);g.h=lZ.prototype;g.h.zp=null;g.h.xj=null;g.h.ka=function(){return this.xj};
g.h.addEventListener=function(a,b,c,d){g.Cf(this.xj,a,b,c,d)};
g.h.removeEventListener=function(a,b,c,d){g.Kf(this.xj,a,b,c,d)};
g.h.T=function(){lZ.Ga.T.call(this);var a=this.xj;if(a)if(g.vf(a))a.fe&&g.zf(a.fe);else if(a=g.Ff(a)){var b=0,c;for(c in a.listeners)for(var d=a.listeners[c].concat(),e=0;e<d.length;++e)g.Lf(d[e])&&++b}};g.A(qZ,lZ);qZ.prototype.fill=null;g.A(sZ,lZ);tZ.prototype.xe=null;tZ.prototype.xd=null;tZ.prototype.Ck=!0;var jna=[2,2,6,6,0];g.h=tZ.prototype;g.h.clear=function(){this.Ta.length=0;this.Ba.length=0;this.Nd.length=0;delete this.xe;delete this.xd;delete this.Ck;return this};
g.h.moveTo=function(a,b){0==g.Va(this.Ta)?this.Nd.length-=2:(this.Ta.push(0),this.Ba.push(1));this.Nd.push(a,b);this.xd=this.xe=[a,b];return this};
g.h.Zb=function(a){var b=g.Va(this.Ta);if(null==b)throw Error("Path cannot start with lineTo");1!=b&&(this.Ta.push(1),this.Ba.push(0));for(b=0;b<arguments.length;b+=2){var c=arguments[b],d=arguments[b+1];this.Nd.push(c,d)}this.Ba[this.Ba.length-1]+=b/2;this.xd=[c,d]};
g.h.close=function(){var a=g.Va(this.Ta);if(null==a)throw Error("Path cannot start with close");4!=a&&(this.Ta.push(4),this.Ba.push(1),this.xd=this.xe);return this};
g.h.clone=function(){var a=new this.constructor;a.Ta=this.Ta.concat();a.Ba=this.Ba.concat();a.Nd=this.Nd.concat();a.xe=this.xe&&this.xe.concat();a.xd=this.xd&&this.xd.concat();a.Ck=this.Ck;return a};
g.h.transform=function(a){if(!this.Ck)throw Error("Non-simple path");a.transform(this.Nd,0,this.Nd,0,this.Nd.length/2);this.xe&&a.transform(this.xe,0,this.xe,0,1);this.xd&&this.xe!=this.xd&&a.transform(this.xd,0,this.xd,0,1);return this};
g.h.isEmpty=function(){return 0==this.Ta.length};g.A(vZ,qZ);g.A(xZ,g.ko);xZ.prototype.o=null;xZ.prototype.nj=function(){return this.Rg?g.Oh(this.ka()):g.Da(this.width)&&g.Da(this.height)?new g.xd(this.width,this.height):null};
xZ.prototype.resume=function(){};g.A(nZ,rZ);g.A(mZ,rZ);g.A(yZ,sZ);yZ.prototype.clear=function(){g.Vd(this.ka())};
yZ.prototype.setSize=function(a,b){var c=this.ka(),d={width:a,height:b},e;for(e in d)c.setAttribute(e,d[e])};
g.A(zZ,vZ);var CZ;g.A(AZ,xZ);var mna=0;g.h=AZ.prototype;g.h.Ep=function(){var a=oZ(this,"svg",{width:this.width,height:this.height,overflow:"hidden"}),b=oZ(this,"g");this.B=oZ(this,"defs");this.o=new yZ(b,this);a.appendChild(this.B);a.appendChild(b);this.i=a;this.l&&(this.ka().setAttribute("preserveAspectRatio","none"),this.O?this.sA():this.ka().setAttribute("viewBox","0 0 "+(this.l?this.l+" "+this.I:"")))};
g.h.sA=function(){if(this.Rg){var a=this.nj();0==a.width?this.ka().style.visibility="hidden":(this.ka().style.visibility="",this.o.ka().setAttribute("transform","scale("+a.width/this.l+" "+a.height/this.I+") translate(0 0)"))}};
g.h.setSize=function(a,b){g.Nh(this.ka(),a,b)};
g.h.nj=function(){if(!g.xh)return this.Rg?g.Oh(this.ka()):AZ.Ga.nj.call(this);var a=this.width,b=this.height,c=g.v(a)&&-1!=a.indexOf("%"),d=g.v(b)&&-1!=b.indexOf("%");if(!this.Rg&&(c||d))return null;if(c){var e=this.ka().parentNode;var f=g.Oh(e);a=parseFloat(a)*f.width/100}d&&(e=e||this.ka().parentNode,f=f||g.Oh(e),b=parseFloat(b)*f.height/100);return new g.xd(a,b)};
g.h.clear=function(){this.o.clear();g.Vd(this.B);this.g={}};
g.h.dj=function(){AZ.Ga.dj.call(this);this.O&&this.P.Na(nna(),"tick",this.sA)};
g.h.T=function(){delete this.g;delete this.B;delete this.o;this.P.dispose();delete this.P;AZ.Ga.T.call(this)};g.t(EZ,g.TJ);g.h=EZ.prototype;
g.h.load=function(){g.TJ.prototype.load.call(this);if(!GZ(g.V(this.player).playerStyle)){var a=g.qB(this.player.getVideoData());if(a)a=DZ(a,FZ(this)),HZ(this,a);else{var b=this.player.getVideoData();a=b.videoId;this.o&&this.o.abort();a={method:"POST",Xc:(0,g.z)(this.dI,this,a),Dc:{v:a},withCredentials:!0};"gaming"==g.V(this.player).playerStyle&&(a.Dc.gaming="1");this.P&&(a.Dc.ptype="embedded");var c=this.player.getVideoData().Ru;c&&(a.qb={ad_tracking:c});if(b=g.pB(b))if(b=g.Wc(b),b=g.Tc(b))this.o=
g.wq(b,a)}}};
g.h.unload=function(){HZ(this,null);this.o&&(this.o.abort(),this.o=null);g.TJ.prototype.unload.call(this)};
g.h.Yb=function(a,b){if(!GZ(g.V(this.player).playerStyle))return null;if("loadCustomEndscreenRenderer"==a){var c=DZ(b,"new");HZ(this,c);return!0}return null};
g.h.getOptions=function(){return GZ(g.V(this.player).playerStyle)?["loadCustomEndscreenRenderer"]:[]};
g.h.dI=function(a,b){var c=this.o=null;if(200==b.status){var d=b.responseText;")]}"==d.substring(0,3)&&(d=d.substring(3),c=JSON.parse(d),c=DZ(c,FZ(this)))}HZ(this,c)};
g.h.ob=function(){if(this.i&&this.i.elements){var a=this.player.getVideoContentRect();if(a&&0!=a.width&&0!=a.height){var b=this.player.getPlayerSize();if(b&&0!=b.width&&0!=b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<a1.length;f++){var k=Math.abs(b.width-a1[f]);if(-1==e||d>=k)e=f,d=k}d=b1[e];this.l&&g.vh(this.l.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.i.elements.length;++b)if(f=this.i.elements[b].id,e=this.g[f],k=this.B[f],e&&k){var l=k.width*c/k.aspectRatio;
f=Math.round(l*a.height);var m=a.left+Math.round(k.left*a.width),n=a.top+Math.round(k.top*a.height);g.Nh(e.element,Math.round(k.width*a.width),f);g.Dh(e.element,m,n);g.Xn(e.element,Hoa);m=k.left+k.width/2;k=k.top+l/2;g.J(e.element,.5>=m&&.5>=k?"ytp-ce-top-left-quad":.5<m&&.5>=k?"ytp-ce-top-right-quad":.5>=m&&.5<k?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.Xn(e.element,b1);g.J(e.element,d);(e=g.Fd(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.vh(e,"height",f+"px")}}}}};
g.h.oE=function(a){if(this.i)if("ytp-ce-in-endscreen"==a.getId())this.H=!1,this.i.skip&&1==this.player.getPlayerState()?(g.sJ(this.player,!0),this.player.seekTo(Infinity),this.H=!0):(LZ(this,this.i.impressionUrls),(a=g.Us())&&this.i.visualElement&&g.Gs(a,this.i.visualElement));else if(!this.H){a=a.getId().substring(15);var b=this.g[a],c=this.B[a];g.J(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.J(b,"ytp-ce-shown");LZ(this,c.impressionUrls);
(b=g.Us())&&g.Gs(b,c.visualElement);g.V(this.player).tb&&this.player.ma("endscreenelementshown",a)}};
g.h.pE=function(a){if("ytp-ce-in-endscreen"!=a.getId()&&!this.H){a=a.getId().substring(15);var b=this.g[a];g.Wn(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden",!0);b=this.player.getRootNode();g.Wn(b,"ytp-ce-shown");g.V(this.player).tb&&this.player.ma("endscreenelementhidden",a)}};
g.h.ZK=function(a){var b=this;a.target===window&&(new g.M(function(){for(var c in b.g)g.Xn(b.g[c].element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.h.hy=function(a,b){if(a.targetUrl&&(!b||"keypress"!=b.type||13==b.keyCode)){for(var c=b.target;c&&!g.Un(c,"ytp-ce-element");){g.Un(c,"subscribe-label")&&MZ(this,a);if(g.Un(c,"ytp-ce-channel-subscribe"))return;c=g.$d(c)}if(!c||g.Un(c,"ytp-ce-element-hover")){b.preventDefault();b.stopPropagation();if(c=this.g[a.id])this.xr(c,a),c.element.blur();b.ctrlKey||b.metaKey||"new"==a.Mn?(MZ(this,a),this.yz(),this.player.pauseVideo(),c=g.Wc(a.targetUrl),c=g.Tc(c),g.LK(c,void 0,a.Yc)):(c=this.player.getVideoData().ac,
c=(0,g.z)(this.KL,this,c,a.targetUrl,a.Yc),c=(0,g.z)(this.yz,this,c),MZ(this,a,c))}}};
g.h.KL=function(a,b,c){var d=g.dq(b);a&&d&&(d.v||d.list)?g.rX(this.player.app,d.v,c,d.list,!1,void 0,void 0):g.KK(b,c)};
g.h.Dq=function(a,b){g.Un(a.element,"ytp-ce-element-hover")||("VIDEO"==b.type||"PLAYLIST"==b.type?g.J(a.element,"ytp-ce-element-hover"):g.V(this.player).g?(new g.M(function(){g.J(a.element,"ytp-ce-element-hover")},200)).start():g.J(a.element,"ytp-ce-element-hover"),LZ(this,b.sD),KZ(this,b.id,!0))};
g.h.xr=function(a,b){g.Wn(a.element,"ytp-ce-element-hover");g.Wn(a.element,"ytp-ce-force-expand");KZ(this,b.id,!1)};
g.h.yz=function(a){this.player.sendVideoStatsEngageEvent(17,a)};
var a1=[346,426,470,506,570,640,853,1280,1920],b1="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),Hoa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var yna={mN:"current",uO:"new"};var Ana={CLOSE:"close",yO:"openUrl",AB:"subscribe"},Bna={hN:"click",CLOSE:"close",PN:"hidden",YO:"rollOut",tB:"rollOver",vB:"shown"};var Dna={CP:"xx",DP:"xy",EP:"yx",FP:"yy"};g.t(g_,$Z);var Ina={QA:"anchored",UO:"rect",bP:"shapeless"};var Mna={CLOSED:"closed",HO:"playerControlShow",tB:"rollOver",vB:"shown"};k_.prototype.Ib=function(){var a=Una(this,function(b){return"openUrl"==b.type&&null!=b.url});
return a?a.url:null};
k_.prototype.showLinkIcon=function(){return m_(this,function(a){return null!=a.url&&a.url.showLinkIcon})};
var l_={QA:"anchored",TA:"branding",CHANNEL:"channel",lN:"cta",RN:"highlightText",fO:"label",PLAYLIST:"playlist",KO:"popup",fP:"speech",AB:"subscribe",oP:"title",VIDEO:"video",yP:"website"},Qna={TA:"branding",YM:"card",sN:"drawer",QN:"highlight",nO:"marker",PO:"promotion",TEXT:"text",AP:"widget"},Rna={wP:"video_relative",IO:"player_relative"};t_.prototype.o=function(a,b,c,d){this.g[a]=b?!c:c;a=g.Ob(this.g,function(e){return e});
this.l!=a&&(this.l=a,this.i.M(this.u,a,d))};u_.prototype.ka=function(){return this.u};
u_.prototype.l=function(){};var y_={bevel:1,dropshadow:2};g.t(D_,u_);
D_.prototype.l=function(a,b){var c=q_(a);if(c){var d=d_(c,b);if(!(0>=d.width||0>=d.height)){var e;if(e=(c=(c=p_(a))&&c.g?c.g:null)&&c.length?c[0]:null){var f=g.mh(b_(b,c_(e,new g.jh(e.D,e.F,e.Fi,e.l),b.g))),k=d.clone();c=new g.jh(f.x,f.y,1,1);var l=Math.max(k.left+k.width,c.left+c.width),m=Math.max(k.top+k.height,c.top+c.height);k.left=Math.min(k.left,c.left);k.top=Math.min(k.top,c.top);k.width=l-k.left;k.height=m-k.top;c=a.i;k=B_(k,c.effects);l=v_(this,k.width,k.height);m=A_(c,k.width,k.height,this.g);
d=new g.jh(d.left-k.left,d.top-k.top,d.width,d.height);var n=new g.ud(f.x-k.left,f.y-k.top);this.o=17*ZZ(b.g,e.i,e.g?e.g:"xy");e=c.cornerRadius;f=a.i;var p=this.g&&n_(a),r=p?f.borderWidth+1:f.borderWidth;p=(f=r?new wZ(r,p?f.i:f.borderColor):null)?f.g/2:0;r=boa(d,n);var u=this.A(d,e,n,r),y=n.x;n=n.y;var D=d.width,E=d.height,K=d.left;d=d.top;var X=new tZ;X.moveTo(K+e+p,d+p);"t"==r&&(X.Zb(u.start,d+p),X.Zb(y,n),X.Zb(u.end,d+p));X.Zb(K+D-e-p,d+p);uZ(X,e,e,-90);"r"==r&&(X.Zb(K+D-p,u.start),X.Zb(y,n),X.Zb(K+
D-p,u.end));X.Zb(K+D-p,d+E-e-p);uZ(X,e,e,0);"b"==r&&(X.Zb(u.end,d+E-p),X.Zb(y,n),X.Zb(u.start,d+E-p));X.Zb(K+e+p,d+E-p);uZ(X,e,e,90);"l"==r&&(X.Zb(K+p,u.end),X.Zb(y,n),X.Zb(K+p,u.start));X.Zb(K+p,d+e+p);uZ(X,e,e,180);X.close();BZ(l,X,f,m);if(m=this.ka())g.J(m,"annotation-shape"),g.J(m,"annotation-speech-shape"),g.Dh(m,k.left,k.top),g.Nh(m,k.width,k.height),C_(l,m,c.effects)}}}};
D_.prototype.A=function(a,b,c,d){function e(f,k,l,m){f=Math.min(Math.max(m-2*b,0),f);k=g.qd(k-f/2,l+b,l+m-f-b);return new g.bj(k,k+f)}
return"t"==d||"b"==d?e(this.o,c.x,a.left,a.width):"l"==d||"r"==d?e(this.o,c.y,a.top,a.height):new g.bj(0,0)};g.t(E_,u_);E_.prototype.l=function(a,b){var c=q_(a);if(c){var d=d_(c,b);if(!(0>=d.width||0>=d.height)){var e=a.i;c=B_(d,e.effects);var f=v_(this,c.width,c.height),k=new wZ(!e.l&&this.g?1:e.l,e.bgColor),l=new mZ("#000",0);d=z_(new g.jh(0,0,d.width,d.height),e.cornerRadius,k?k.g/2+1:0);BZ(f,d,k,l);f=this.ka();g.J(f,"annotation-shape");e=e.g;VY(f,this.g?Math.max(e,.9):e);g.Dh(f,c.left,c.top);g.Nh(f,c.width,c.height)}}};g.t(F_,u_);
F_.prototype.l=function(a,b){var c=q_(a);if(c){var d=d_(c,b);if(!(0>=d.width||0>=d.height)){c=a.i;var e=B_(d,c.effects),f=v_(this,e.width,e.height),k=new g.jh(0,0,d.width,d.height);d=A_(c,d.width,d.height,this.g);var l=c.cornerRadius;var m=a.i;var n=this.g&&n_(a),p=n?m.borderWidth+1:m.borderWidth;m=p?new wZ(p,n?m.i:m.borderColor):null;k=z_(k,l,m?m.g/2+1:0);BZ(f,k,m,d);if(k=this.ka())g.J(k,"annotation-shape"),g.J(k,"annotation-popup-shape"),g.Dh(k,e.left,e.top),g.Nh(k,e.width,e.height),C_(f,k,c.effects)}}};g.t(G_,D_);G_.prototype.A=function(a,b,c,d){function e(f,k,l,m){f=Math.min(Math.max(m-2*b,0),f);k=k<=l+m/2?Math.max(l+m/4-f/2,l+b):Math.min(l+3*m/4-f/2,l+m-f-b);return new g.bj(k,k+f)}
return"t"==d||"b"==d?e(this.o,c.x,a.left,a.width):"l"==d||"r"==d?e(this.o,c.y,a.top,a.height):new g.bj(0,0)};g.t(H_,g.G);g.h=H_.prototype;g.h.Tw=function(){this.F||(this.o&&g.Ph(this.o,!0),this.u&&g.Ph(this.u,!0),this.l&&(this.l.g=!0,VY(this.i,M_(this)?1:0),this.l.l(this.g,J_(this))),this.D.isActive()&&this.D.stop(),this.F=!0,this.H=this.ca.om(g.pJ(this.A),"mouseleave",function(a){this.Qm.stop();this.pg(a)}))};
g.h.pg=function(){this.F&&(this.N?this.D.start():this.Uv(),this.l&&(this.l.g=!1,VY(this.i,M_(this)?1:0),this.l.l(this.g,J_(this))),this.F=!1,this.H&&(this.ca.Na(this.H),this.H=null))};
g.h.Uv=function(){this.o&&g.Ph(this.o,!1);this.u&&g.Ph(this.u,!1)};
g.h.cF=function(a){this.aa=a;this.Qm.vj()};
g.h.TC=function(){var a=this.aa,b=new g.ud(a.clientX,a.clientY),c=g.Hh(this.A.getRootNode()),d=N_(c,this.P);c=(this.u&&WY(this.u)||this.o&&WY(this.o))&&N_(c,this.N);d&&d.contains(b)||c&&c.contains(b)?this.Tw(a):this.pg(a)};
g.h.show=function(){var a=this.g.i;a=(a&&0==a.g||"title"==this.g.style||"highlightText"==this.g.style?!1:!0)&&!this.l;var b=!this.i;if(a){var c=J_(this),d=null;"highlight"==this.g.type||"label"==this.g.style?d=new E_:"popup"==this.g.style?d=new F_:"anchored"==this.g.style?d=new D_:"speech"==this.g.style&&(d=new G_);d&&(d.l(this.g,c),this.l=d,c=d.ka())&&(g.Ph(c,!1),g.J(c,"annotation-type-"+this.g.type.toLowerCase()),this.R(c))}if(b){c=["annotation"];"highlightText"!=this.g.style||c.push("annotation-no-mouse");
c.push("annotation-type-"+this.g.type.toLowerCase());this.i=g.Rd("DIV",c);g.Ph(this.i,!1);this.g.o&&(this.B=g.Rd("DIV","inner-text"),"label"==this.g.style&&(g.J(this.B,"player-label-text"),this.B.style.backgroundColor=this.g.i.bgColor),g.ce(this.B,this.g.o),this.i.appendChild(this.B));g.Ep(this.i,"annotation_id",this.g.id);this.R(this.i);coa(this,this.i);if(n_(this.g)&&this.g.showLinkIcon()){if(d=this.g.Ib())c=this.i,d=new g.Om(XZ(d)),c.title=d.g+d.i;this.u=g.Rd("SPAN","annotation-link-icon");g.Ph(this.u,
!1);this.i.appendChild(this.u)}doa(this);n_(this.g)||(this.i.style.cursor="default")}if(a||b){a:{a=this.g.segment.g;if(a.length&&(a=i_(a[0]))){a=a.u;break a}a=0}this.i&&(this.i.style.zIndex=a);this.l&&this.l.ka()&&(this.l.ka().style.zIndex=a)}g.Ph(this.i,!0);VY(this.i,M_(this)?1:0);L_(this);this.l&&this.l.ka()&&g.Ph(this.l.ka(),!0)};
g.h.hide=function(){this.i&&g.Ph(this.i,!1);this.l&&this.l.ka()&&g.Ph(this.l.ka(),!1);this.I&&(this.ca.Na(this.I),this.I=null)};g.t(O_,g.G);g.h=O_.prototype;g.h.hide=function(){this.isVisible=!1;this.view&&(P_(this),this.view.hide())};
g.h.show=function(){this.isVisible=!0;this.view&&(this.view.show(),this.i.subscribe("resize",this.Sw,this),this.i.subscribe("onVideoAreaChange",this.Jy,this))};
g.h.destroy=function(){if(this.view){P_(this);var a=this.view,b=a.ca;g.xr(b.g);b.g.length=0;a.Qm.dispose();a.D.dispose();a.i&&g.Xd(a.i);a.l&&a.l.ka()&&g.Xd(a.l.ka())}Q_(this)};
g.h.Jy=function(){L_(this.view)};
g.h.Sw=function(){L_(this.view)};g.t(R_,kZ);g.t(S_,kZ);g.t(T_,S_);g.t(U_,kZ);g.t(V_,kZ);g.t(W_,S_);g.t(X_,S_);g.t(Y_,kZ);g.t(Z_,kZ);h0.prototype.l=function(a,b){var c=g.he(b.target,"label");c&&g.L(c,"iv-card-poll-choice-focused",a)};
h0.prototype.B=function(a,b){var c=g.he(b.target,null,"iv-card-poll",void 0);if(c)if(a.o)g.Hd("iv-card-sign-in-button",c).click();else{var d=parseInt(dna(b.target),10);if(null==a.g)a.choices[d].count++,a.g=d;else if(a.g!=d){var e=a.choices[a.g];e.count=Math.max(e.count-1,0);a.choices[d].count++;a.g=d}else e=a.choices[a.g],e.count=Math.max(e.count-1,0),a.g=null;j0(a,c);g.Aq(this.g.videoData.Dd,{Dc:{action_poll_vote:1},qb:{poll_id:a.id,index:d,session_token:a.F}});d0(this.g.logger,a.l,void 0,{"link-id":d},
a.i.click,5);(c=g.Us())&&g.Hs(c,a.A)}};
h0.prototype.A=function(a){var b=g.x("yt.www.ypc.bootstrap.api.loadOffersForInnertubeRequestParams"),c;b&&(c=function(){b(a.F,a.B)});
r0(this,a,!0,c)};
h0.prototype.D=function(a){var b=g.x("yt.www.ypc.bootstrap.api.loadOffers");b&&(b=g.Ra(b,a.P,a.F,a.B));r0(this,a,!1,b)};g.t(y0,g.G);g.h=y0.prototype;g.h.addCueRange=function(a,b,c,d,e){a=new g.mD(a,b,{id:c});g.H(this,a);a.namespace="annotations_module";d&&SY(a).subscribe("onEnter",d,this);e&&SY(a).subscribe("onExit",e,this);g.yJ(this.context.Z,[a])};
g.h.Gn=function(){this.context.i.subscribe("resize",this.pl,this)};
g.h.ka=function(){return this.Ca};
g.h.wi=function(a,b,c,d,e,f,k){this.context.g.da(a,"click",g.Ra(this.nm,b,c,d,e,f||[],k||0),this);this.context.g.da(a,"touchstart",g.Ra(function(){this.Js=!1}),this);
this.context.g.da(a,"touchmove",g.Ra(function(){this.Js=!0}),this)};
g.h.nm=function(a,b,c,d,e,f,k){if(this.Js)return!1;k&&(k.stopPropagation(),k.preventDefault());ooa(this,a,c,d,e,f);return!1};
g.h.show=function(){this.X=(0,g.C)()};
g.h.hide=function(){};
g.h.destroy=function(){g.Xd(this.ka())};
g.h.pl=function(){};g.t(B0,y0);g.h=B0.prototype;g.h.isAvailable=function(){var a;if(a=!!this.l.length)(a=this.i.getRootNode())?(a=g.Oh(a),a=173<a.width&&173<a.height):a=!1;return a};
g.h.pl=function(){var a=this.isAvailable();g.Ph(this.ka(),a);g.L(this.context.Z.getRootNode(),"ytp-iv-drawer-enabled",a);TY(this.i)};
g.h.destroy=function(){this.i.si(!1);this.i.getRootNode().removeChild(this.B);g.Pp(this.I);g.xr(this.aa);this.Y&&this.Y.dispose();this.D&&this.D.dispose();y0.prototype.destroy.call(this)};
g.h.EE=function(a){this.N.start();a.preventDefault();a=a||window.event;var b=0;"MozMousePixelScroll"==a.type?b=0==(a.axis==a.HORIZONTAL_AXIS)?a.detail:0:window.opera?b=a.detail:b=0==a.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?a.wheelDeltaY/-30:a.wheelDeltaY/-1.2:a.wheelDelta/-1.6:a.wheelDeltaY/-3;if(a=b)this.o.scrollTop+=a};
g.h.Ez=function(a){if(!g.Un(this.i.getRootNode(),"ytp-cards-teaser-shown")){if(this.g!=a){var b=g.Us(),c=this.g?this.g.Hb.u:this.H;b&&c&&jZ(b,[c]);this.g=a;E0(this)}WY(this.ka())&&(2==this.context.Z.getPresentingPlayerType()?b=1==(isNaN(void 0)?this.context.Z.getAdState():void 0):(b=isNaN(void 0)?this.context.Z.getPlayerState():void 0,b=1==b||0==b&&0===this.context.Z.getCurrentTime()),b&&a.Hb.teaserDurationMs&&this.i.si(!0,{teaserText:a.Hb.teaserText,durationMs:a.Hb.teaserDurationMs}));this.la.isActive()||
((!this.u||!this.N.isActive()&&this.V)&&F0(this,a),this.la.start(910+a.Hb.teaserDurationMs))}};
g.h.EL=function(a){this.u||(this.g=a,E0(this),F0(this,a),z0(this,"YOUTUBE_DRAWER_AUTO_OPEN",!1,a))};
g.h.XB=function(){if(this.u){f0(this.context.logger,this.R,4,G0(this).i.close);var a=g.Us();a&&this.P&&g.Hs(a,this.P);A0(this)}};
g.h.gC=function(){g.L(this.B,"iv-drawer-scrolled",0<this.o.scrollTop)};
g.h.MD=function(){var a=g.Us(),b=G0(this);b=b?b.u:this.H;a&&b&&iZ(a,[b])};
g.h.LD=function(){var a=g.Us(),b=G0(this);b=b?b.u:this.H;a&&b&&jZ(a,[b])};
g.h.PD=function(){var a=G0(this);g0(this.context.logger,8,a.l,a.i.RL);var b=g.Us();b&&a&&iZ(b,[a.D,a.u])};
g.h.OD=function(){var a=g.Us(),b=G0(this);a&&b&&jZ(a,[b.D])};
g.h.ND=function(a){var b=G0(this),c=g.Us();this.g?a?(a=this.context.logger,g0(a,9,b.l,b.i.os),a.g.sendVideoStatsEngageEvent(4,void 0),c&&g.Hs(c,b.D)):(a=this.context.logger,g0(a,12,b.l,b.i.os),a.g.sendVideoStatsEngageEvent(4,void 0),c&&g.Hs(c,b.u)):(a=this.context.logger,f0(a,this.R,12,b.i.os),a.g.sendVideoStatsEngageEvent(4,void 0),c&&this.H&&g.Hs(c,this.H))};
var C0={collaborator:R_,donation:T_,episode:Z_,movie:Z_,playlist:U_,poll:V_,productListing:W_,simple:S_,tip:X_,video:Y_};g.t(H0,y0);H0.prototype.Gn=function(){y0.prototype.Gn.call(this);woa(this)};
H0.prototype.show=function(){y0.prototype.show.call(this);var a=g.Us(),b=this.annotation.data;a&&b&&(b=b.session_data)&&iZ(a,[g.Ds(b.itct)])};
H0.prototype.hide=function(){y0.prototype.hide.call(this);var a=g.Us(),b=this.annotation.data;a&&b&&(b=b.session_data)&&jZ(a,[g.Ds(b.itct)])};g.t(I0,H0);g.h=I0.prototype;g.h.LL=function(a,b,c,d){this.l.stop();if(!this.o){var e=g.Oh(a);this.g||(g.Mh(a,e.width),g.Mh(b,e.width));g.vh(c,"top",e.height-Math.max(Math.min(e.height,d)/2+10,20)+"px");g.vh(c,"right","1px");this.o=!0;g.Ph(a,!0);this.A=new g.M(function(){g.J(this.ka(),"iv-branding-active")},0,this);
this.A.start()}};
g.h.rD=function(a,b){g.Wn(this.ka(),"iv-branding-active");this.B=new g.M((0,g.z)(function(){g.Ph(a,!1);this.g||g.Mh(b,0)},this),250);
this.B.start();this.o=!1};
g.h.show=function(){if(!this.isActive){H0.prototype.show.call(this);if(!this.D){g.J(this.ka(),"iv-branding");var a=this.annotation.data;this.u=a.image_width;this.i=g.Rd("IMG",{src:a.image_url,"class":"branding-img iv-click-target",width:a.image_width,height:a.image_height});g.Ph(this.i,!1);var b=g.Rd("DIV","branding-img-container",this.i);this.ka().appendChild(b);var c=g.Rd("DIV","iv-branding-context-name");g.ce(c,a.channel_name);var d=g.Rd("DIV","iv-branding-context-subscribe");if(b=a.standalone_subscribe_button_data)this.g=
new g.hV(b.subscribeText,b.subscribeCount,b.unsubscribeText,b.unsubscribeCount,!!b.enabled,!!b.classic,a.channel_id,!!b.subscribed,b.feature,a.session_data.itct,b.signinUrl,this.context.Z),this.g.g(d);b=g.Rd("DIV","iv-branding-context-subscribe-caret");c=g.Rd("DIV","branding-context-container-inner",b,c,d);g.Ph(c,!1);d=g.Rd("DIV","branding-context-container-outer",c);g.vh(d,"right",this.u+"px");this.ka().appendChild(d);var e=this.annotation.Ib();e&&this.wi(this.i,e,this.annotation.id,a.session_data,
this.annotation.g);this.l=new g.M(g.Ra(this.rD,c,d),500,this);g.H(this,this.l);this.context.g.da(this.ka(),"mouseover",(0,g.z)(this.LL,this,c,d,b,a.image_height));this.context.g.da(this.ka(),"mouseout",(0,g.z)(this.l.start,this.l,void 0));this.D=!0}c0(this.context.logger,this.annotation.g);g.Ph(this.ka(),!0);this.isActive=!0;if(this.i){a=this.i;var f=void 0===f?0:f;b=UY(a).width;c=g.Da(void 0)?void 0:b;g.Dh(a,c);f=new gZ(a,[c,a.offsetTop],[c-b-f,a.offsetTop],200,fna);g.H(this,f);this.context.l.da(f,
"begin",g.Ra(g.Ph,a,!0));f.play()}}};
g.h.hide=function(){this.isActive&&(H0.prototype.hide.call(this),g.Ph(this.ka(),!1),this.isActive=!1)};
g.h.destroy=function(){this.g&&(this.g.dispose(),this.g=null);H0.prototype.destroy.call(this)};g.t(J0,H0);g.h=J0.prototype;g.h.show=function(){this.isActive||(H0.prototype.show.call(this),this.H||(xoa(this),this.H=!0),g.Ph(this.ka(),!0),this.annotation&&this.annotation.g&&c0(this.context.logger,this.annotation.g),g.Dg(function(){g.Wn(this.ka(),"iv-promo-inactive")},100,this),this.ka().removeAttribute("aria-hidden"),this.isActive=!0,M0(this),L0(this),N0(this,this.B))};
g.h.hide=function(){this.isActive&&(g.J(this.ka(),"iv-promo-inactive"),this.isActive=!1,this.ka().setAttribute("aria-hidden",!0))};
g.h.nm=function(a,b,c,d,e,f,k){return this.u?!1:H0.prototype.nm.call(this,a,b,c,d,e,f,k)};
g.h.Gp=function(a,b){b.stopPropagation();L0(this);N0(this,a);this.g.focus()};
g.h.VC=function(a){this.F=!0;this.Gp(500,a)};
g.h.UC=function(){this.F=!1;K0(this)};
g.h.MC=function(a){a.stopPropagation();this.hide();e0(this.context.logger,this.annotation.g)};
g.h.NC=function(a){a.stopPropagation();M0(this);this.u=!0;g.J(this.ka(),"iv-promo-collapsed-no-delay");this.A.start();e0(this.context.logger,this.annotation.g)};
g.h.destroy=function(){this.A.dispose();H0.prototype.destroy.call(this)};g.t(O0,g.TJ);g.h=O0.prototype;g.h.Yb=function(a,b){if(!P0(g.V(this.player).playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":var c=g.Yn(b);c&&U0(this,c);return!0;case "removeCustomAnnotationById":return b&&this.g&&(D0(this.g,b),TY(this.player)),!0}return null};
g.h.getOptions=function(){return P0(g.V(this.player).playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.h.yr=function(){if(this.o){var a=g.pJ(this.player).getVideoContentRect(!0);g.Nh(this.o.element,a.width,a.height);g.Dh(this.o.element,a.left,a.top)}if(this.g){var b=g.wJ(this.player);a=this.g;b=b.width;g.L(a.B,"iv-drawer-small",426>=b);g.L(a.B,"iv-drawer-big",1280<=b)}};
g.h.vJ=function(a){this.hc(a.state);g.U(a.state,2)&&(this.ud()&&this.ue()&&2!=this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.si(!1))};
g.h.load=function(){g.TJ.prototype.load.call(this);this.hc(g.oJ(this.player));this.H++;var a=this.player.getVideoData(),b=a.videoId,c=(0,g.z)(this.eI,this,b,this.H),d=(0,g.z)(function(){this.B=null},this);
g.ms()&&(c=V0(this,c));c={format:"XML",Xc:c,onError:d,Dc:{}};a.isPharma&&(c.Dc.pharma="1");c.method="POST";c.withCredentials=!0;d=g.V(this.player);"gaming"==d.playerStyle&&(c.Dc.gaming="1");(b=d.I.get(b))&&W0(c,b);b=b&&(b.vl||b.ul);if(!a.il||b)a.Dd?Q0(this,a.Dd,c):(this.l=(0,g.z)(this.nE,this,c),this.player.addEventListener("videodatachange",this.l));g.FJ(this.player,this.o.element,4);this.yr()};
g.h.hc=function(a){a=!a.isCued()&&!g.U(a,1024);g.IB(this.u,a);g.IB(this.o,a)};
g.h.nE=function(a){var b=this.player.getVideoData();b.Dd&&(this.l&&(this.player.removeEventListener("videodatachange",this.l),this.l=null),Q0(this,b.Dd,a))};
g.h.unload=function(){hoa(this.D);g.BJ(this.player,"annotations_module");g.Kb(this.i,function(a){a.destroy()});
g.Kb(this.P,function(a){a.destroy()});
this.F=null;this.g&&(this.g.destroy(),this.g=null,TY(this.player));this.I=!1;this.B&&(this.B.abort(),this.B=null);this.i={};this.P={};this.u.hide();g.TJ.prototype.unload.call(this);g.HB(this.o);this.l&&(this.player.removeEventListener("videodatachange",this.l),this.l=null)};
g.h.eI=function(a,b,c){this.B=null;if(!S0(this,b,a)&&(a=g.qq(c)&&c.responseXML?c.responseXML:null)){U0(this,a);g.J(this.player.getRootNode(),"iv-module-loaded");a=[];for(var d in this.i){b=this.i[d].annotation;if(b.segment)if(c=b.segment,c.g.length)if(c=c.g[0].i||c.g[0].g||c.g[0].l,!c||2>c.length)c=null;else{var e=c.length-1;c=0>=c[0].t&&0>=c[e].t?null:{start:c[0].t,end:c[e].t}}else c=null;else c=null;if(e=c)if(c=1E3*e.start,e=1E3*e.end,0==c&&(c++,e++),!(e<c)){var f={id:d,namespace:"annotations_module"};
"marker"==b.type&&(f.style="ytp-chapter-marker",f.tooltip=b.o,f.visible=!0);b=new g.mD(c,e,f);a.push(b)}}g.yJ(this.player,a)}};
g.h.Iy=function(a){a==this.player.getVideoData().videoId&&(this.loaded?Coa(this):this.load())};
g.h.kE=function(a){a=a.getId();var b=this.i[a];b&&!b.l&&(b=b.annotation,X0(this,a),c0(this.D,b.g))};
g.h.lE=function(a){Y0(this,a.getId())};
g.h.Tv=function(a){a&&(a.hide(),$0(this,"shown",!1,a.annotation.id),this.El(a.annotation,"hidden"))};
g.h.Qz=function(a){a&&(a.show(),$0(this,"shown",!0,a.annotation.id),this.El(a.annotation,"shown"))};
g.h.KK=function(a,b,c){var d=this.i[a];if(d&&b.value!=c){b.value=c;var e=!1;o_(d.annotation,function(f){e=e||f.value});
Foa(this,a,b,e)}};
g.h.lH=function(a){if(a&&a.id){var b=a.Ib();if(b){var c=XZ(b);if(c){var d=(0,g.z)(this.El,this,a,"click");if("new"==x0(c,b.target)||Z0(this,b))d(),d=null;d0(this.D,a.g,d)}}}};
g.h.El=function(a,b){Tna(a,function(c){if(c.trigger==b&&"openUrl"==c.type&&c.url){var d=this.player.getVideoData(),e;if(!(e=!Z0(this,c.url))){e=w0(c.url);var f=loa(c.url);e?(d.videoId==e?this.player.seekTo(f||0):(d=T0(this).Z,g.rX(d.app,e,void 0,void 0,void 0,void 0,void 0),f&&T0(this).Z.dc()&&T0(this).Z.seekTo(f)),d=!0):d=!1;e=!d}e&&(e=g.V(this.player),(d=XZ(c.url))?(f=u0(d),e&&"com"==f[0]&&"google"==f[1]&&"plus"==f[2]&&(e=g.Ra(moa,e.pageId,e.jc),d=new g.Om(d),e=e(d.i),d.i=e,d=d.toString())):d=null,
d&&(this.player.pauseVideo(),c=x0(d,c.url.target),e=a.itct,"ei"in g.dq(d)&&(d=g.dh(d,"ei")),g.LK(d,"current"==c?"_top":void 0,{itct:e})))}},this)};
g.h.mI=function(){$0(this,"playerControlShow",!1)};
g.h.mK=function(){$0(this,"playerControlShow",!0)};
g.h.mE=function(a){$0(this,"rollOver",!0,a.id)};
g.h.pg=function(a){$0(this,"rollOver",!1,a.id)};
g.h.OH=function(a){a&&a.id&&(this.i[a.id].l=!0,Y0(this,a.id),e0(this.D,a.g),this.El(a,"close"),$0(this,"closed",!0,a.id))};
g.h.ud=function(){return!!this.g&&this.g.isAvailable()};
g.h.ue=function(){this.ud();return!!this.g&&this.g.u};
g.h.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.ud();this.g&&(a?c?z0(this.g,c,b):z0(this.g,"YOUTUBE_DRAWER_AUTO_OPEN",b):A0(this.g))};
g.h.si=function(a,b){this.player.M(a?"cardsteasershow":"cardsteaserhide",b)};
g.h.T=function(){g.V(this.player).I.unsubscribe("vast_info_card_add",this.Iy,this);g.Wn(this.player.getRootNode(),"ytp-iv-drawer-open");for(var a=this.N,b=0,c=a.length;b<c;b++)g.ns(a[b]);this.N.length=0;g.TJ.prototype.T.call(this)};g.pU.annotations_module=O0;g.pU.creatorendscreen=EZ;})(_yt_player);
