(function(g){var window=this;var c1=function(a){var b={languageCode:a.i,languageName:a.l,displayName:g.dz(a),kind:a.o,name:a.u,id:a.Da,is_servable:a.B,is_default:a.isDefault,is_translateable:a.D,vss_id:a.A};a.g&&(b.translationLanguage=a.g);return b},d1=function(a){return a.g?a.g.languageCode:a.i},Ioa=function(a,b){var c=new g.cz;
c.i=a.i;c.l=a.l;c.u=a.u;c.o=a.o;c.isDefault=!1;c.B=a.B;c.D=a.D;c.A=a.A;c.F=a.F;c.g=b;return c},e1=function(a){if(!Joa.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(Koa,"#$1$1$2$2$3$3"));a=a.toLowerCase();a=parseInt(a.substr(1),16);return[a>>16,a>>8&255,a&255]},Loa=function(){this.i=[];
this.g=[]},f1=function(a,b){return b?a.g.concat(a.i):a.g},g1=function(a,b){switch(b.o){case "asr":var c=a.i;
g.Xa(c,(0,g.z)(b.Eq,b))||c.push(b);break;default:c=a.g,g.Xa(c,(0,g.z)(b.Eq,b))||c.push(b)}},h1=function(){g.G.call(this);
this.i=new Loa;this.u=[]},i1=function(a,b,c){h1.call(this,a);
this.g=null;this.u=b.gu;this.l=c},j1=function(){this.Ta=[]},k1=function(a,b,c,d,e,f){g.G.call(this);
this.I=a;this.o=b;this.A=new j1;this.g=null;this.F=d;this.P=f;this.i=this.l=null;this.D=c;this.B=e||!1;this.H=new g.M(this.qw,1E3,this);g.H(this,this.H);this.u=new g.Jr(this);g.H(this,this.u);g.Q(g.V(b).experiments,"html5_disable_captions_seek_complete")?this.u.K(b,"seekto",this.Zw):this.u.K(b,"seekcomplete",this.nF);this.Zw(b.getCurrentTime());this.qw()},l1=function(a,b){b-=a.o.lc();
var c=a.g;a.g=g.Va(a.D.nf(b).g);c!=a.g&&a.P&&a.P()},m1=function(a,b){var c=g.rv(b,a.I,{}).Ib(),d={format:"RAW",
withCredentials:!0};a.B&&(d.responseType="arraybuffer");a.i=g.Xq(c,d,3,100).then((0,g.z)(a.SJ,a));a.l=b;c=a.A;d=a.l.g[0].i;var e=g.ob(c.Ta,d);0<=e||0>e&&1==(-e-1)%2||(e=-e-1,0<e&&1==d-c.Ta[e-1]&&e<c.Ta.length&&1==c.Ta[e]-d?(g.bb(c.Ta,e),g.bb(c.Ta,e-1)):0<e&&1==d-c.Ta[e-1]?c.Ta[e-1]=d:e<c.Ta.length&&1==c.Ta[e]-d?c.Ta[e]=d:(g.kb(c.Ta,e,0,d),g.kb(c.Ta,e+1,0,d)))},n1=function(a,b){h1.call(this,g.V(b));
this.g=a;this.B=b;this.l=null;this.o=!1;this.A=g.Oy(g.V(this.B))&&!this.g.i},o1=function(a,b){var c=[],d;
for(d in a.g.g){var e=a.g.g[d];if(g.iU(e,b||null)){var f="en",k="English",l=".en",m="";if(e=e.info.captionTrack)f=e.languageCode,k=e.displayName,l=e.vssId,m=e.kind;c.push(new g.cz({id:d,languageCode:f,languageName:k,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m}))}}return c},Moa=function(a,b){return null!=b&&b in a.g.g?a.g.g[b]:null},p1=function(a,b,c){var d=[],e;
for(e in a.g.g){var f=a.g.g[e];if(g.iU(f,c||null)){var k=f.info.captionTrack;k&&k.languageCode==b&&d.push(f)}}return d.length?d[0]:null},q1=function(a,b,c,d,e){h1.call(this,e||null);
c=c||g.dq(a).hl||"";c=c.split("_").join("-");this.o=g.fq(a,{hl:c});this.l=b;this.A=!!d;this.B={};this.g=null},r1=function(a,b,c,d,e,f,k){f=void 0===f?!1:f;
k=void 0===k?null:k;g.mD.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.l=f;this.i=k},s1=function(a,b,c,d,e){g.mD.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.i=[]},u1=function(a){a=void 0===a?{}:a;
var b="_"+t1++;return new s1(0,0x8000000000000,0,b,a)},w1=function(a,b,c,d,e,f){var k={};
g.Sa(k,b);g.Sa(k,a.params);g.Sa(k,c);var l={};g.Sa(l,b.xb);a.params.xb&&g.Sa(l,a.params.xb);g.Sa(l,c.xb);k.xb=l;g.T.call(this,{C:"div",G:"caption-window",L:{id:"caption-window-"+a.id,dir:1==k.Qe?"rtl":"ltr",tabindex:"0","aria-live":"assertive",lang:k.lang},J:[{C:"span",G:"captions-text"}]});this.A=[];this.O=!1;this.o=a;this.V=this.R=null;this.Ra=e;this.Oa=f;this.F=null;this.X=.96*e;this.xa=.96*f;this.l=k;this.Ma=c;this.u=this.i["captions-text"];this.Ca=null!=this.u.style["box-decoration-break"]||
null!=this.u.style["-webkit-box-decoration-break"];this.Y=d/360*16;this.type=0;this.la=this.Y*v1(l);a=new g.Pr(this.element,!0);g.H(this,a);a.subscribe("dragstart",this.mF,this);a.subscribe("dragmove",this.lF,this);a.subscribe("dragend",this.kF,this);this.ua=this.na=0;b="";this.l.windowOpacity&&(a=e1(this.l.windowColor),b="rgba("+a[0]+","+a[1]+","+a[2]+","+this.l.windowOpacity+")");a={"background-color":b,display:!1===this.l.isVisible?"none":"","text-align":Noa[this.l.textAlign]};this.Ca&&(a["border-radius"]=
b?this.la/8+"px":"");if(this.B=2==this.o.params.Qe||3==this.o.params.Qe)b=this.element,c="vertical-rl",1==this.l.aA&&(c="vertical-lr"),g.Md&&(c="vertical-lr"==c?"tb-lr":"tb-rl"),g.vh(b,"-o-writing-mode",c),g.vh(b,"-webkit-writing-mode",c),g.vh(b,"writing-mode",c),g.vh(b,"text-orientation","upright"),g.J(b,"ytp-vertical-caption"),3==this.o.params.Qe&&(g.vh(b,"text-orientation",""),g.vh(b,"transform","rotate(180deg)"));g.vh(this.element,a);switch(this.l.Kf){case 0:case 1:case 2:g.J(this.element,"ytp-caption-window-top");
break;case 6:case 7:case 8:g.J(this.element,"ytp-caption-window-bottom")}},v1=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0==a.offset||2==a.offset)b*=.8;return b},x1=function(a,b){var c={},d=b.background?b.background:a.l.xb.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.l.xb.backgroundOpacity;d=e1(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.Ca&&(c["box-decoration-break"]="clone",c["border-radius"]=a.la/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.Y*v1(b)+"px";d=1;e=b.color||a.l.xb.color;if(b.color||null!=b.textOpacity)e=e1(e),d=null==b.textOpacity?a.l.xb.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",c.color=
e,c.fill=e;var f=b.charEdgeStyle;0==f&&(f=null);if(f){e="rgba(34, 34, 34, "+d+")";var k="rgba(204, 204, 204, "+d+")";b.ou&&(k=e=b.ou);var l=a.Y/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),r=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=r;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+k);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;5>p;p++)d.push("0 0 "+n+"px "+
e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.Eq()?'"Carrois Gothic SC", sans-serif-smallcaps':
'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.l.xb.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7==b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.He&&(c["font-style"]="italic");b.underline&&(c["text-decoration"]="underline");
b.qD&&(c.visibility="hidden");return c},y1=function(a){a.F=g.Sd("SPAN");
g.J(a.F,"caption-visual-line");a.u.appendChild(a.F)},z1=function(a,b){var c=g.Sd("SPAN");
g.vh(c,x1(a,b));c.classList.add("ytp-caption-segment");a.F.appendChild(c);c.previousElementSibling&&(g.vh(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.vh(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},A1=function(a,b,c){a.O=a.O||!!c;
var d={};g.Sa(d,a.l.xb);g.Sa(d,c||b.i);g.Sa(d,a.Ma.xb);var e=!a.F;e&&y1(a);c=a.R&&a.V&&g.ac(d,a.V)?a.R:z1(a,d);for(var f=g.v(b.text),k=f?b.text.split("\n"):[b.text],l=0;l<k.length;l++){var m=0<l||!b.l,n=k[l];m&&!e?(y1(a),c=z1(a,d)):m&&e&&(e=!1);n&&c.appendChild(f?g.Td(n):n)}if(!f)for(e=b.text.querySelectorAll("RT".toString()),f=0;f<e.length;f++)g.vh(e[f],x1(a,d)),g.vh(e[f],"font-size","50%");a.V=d;a.R=c;a.A.push(b)},B1=function(){},D1=function(){this.o=this.i=this.mode=this.l=0;
this.u=new C1(this);this.A=new C1(this);this.g=[];this.clear()},Ooa=function(a,b,c){if(255==a&&255==b||!a&&!b)return{ll:a,
nl:b,result:0};a=E1[a];b=E1[b];if(a&128){if(!(b&128)&&0!=c.g&&c.i==b)return{ll:a,nl:b,result:1}}else if(b&128&&1<=a&&31>=a)return{ll:a,nl:b,result:2};return{ll:a,nl:b,result:3}},Poa=function(a,b,c,d){255==b&&255==c||!b&&!c?(45==++a.o&&a.reset(),a.u.g.clear(),a.A.g.clear()):(a.o=0,F1(a.u,b,c,d))},Qoa=function(a,b){a.g.sort(function(e,f){var k=e.time-f.time;
return 0==k?e.order-f.order:k});
for(var c=0;c<a.g.length;c++){var d=a.g[c];a.i=d.time;0==d.type?Poa(a,d.iu,d.ju,b):1==d.type&&a.l&496&&F1(a.A,d.iu,d.ju,b)}a.g.length=0},G1=function(){this.g=0},H1=function(){this.i=this.l=this.g=0},I1=function(){this.timestamp=this.Md=0},J1=function(a){this.l=[];
for(var b=0;15>=b;b++){this.l[b]=[];for(var c=0;32>=c;c++)this.l[b][c]=new I1}this.g=this.i=this.row=0;this.style=new G1;this.u=a;this.o=0},K1=function(a,b){if(3==a.style.g){for(var c=0,d=0,e=a.u.i+0,f="",k="",l=e,m=1;15>=m;++m){for(var n=!1,p=d?d:1;32>=p;++p){var r=a.l[m][p];
if(0!=r.Md){0==c&&(c=m,d=p);n=String.fromCharCode(r.Md);var u=r.timestamp;u<e&&(e=u);r.timestamp=l;k&&(f+=k,k="");f+=n;n=!0}if((0==r.Md||32==p)&&n){k="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.u(c,d,e,l,f)}else for(d=c=0,f=e=a.u.i+0,k=1;15>=k;++k)for(l="",m=1;32>=m;++m)if(p=a.l[k][m],r=p.Md,0!=r&&(0==c&&(c=k,d=m),n=String.fromCharCode(r),u=p.timestamp,u<=e&&(e=u),l+=n,p.reset()),32==m||0==r)l&&b.u(c,d,e,f,l),e=f,l="",d=c=0},Voa=function(a,b){switch(a){case 0:return Roa[(b&127)-32];
case 1:return Soa[b&15];case 2:return Toa[b&31];case 3:return Uoa[b&31]}return 0},L1=function(a){return a.l[a.row][a.i]},M1=function(a,b,c){2<=b&&1<a.i&&(--a.i,L1(a).Md=0);
var d=L1(a);d.timestamp=a.u.i+0;d.Md=Voa(b,c);32>a.i&&a.i++},N1=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++)a.l[b+e][f].Sf(a.l[c+e][f])},O1=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.l[b+d][e].reset()},P1=function(a){a.row=0<a.g?a.g:1;
a.i=1;O1(a,0,15)},Q1=function(a){this.o=a;
this.u=0;this.style=new G1;this.A=new J1(a);this.B=new J1(a);this.D=new J1(a);this.i=this.A;this.l=this.B;this.g=this.i},R1=function(a,b,c){var d=a.i,e=!1;
switch(a.style.get()){case 4:if(0<d.g)break;case 1:case 2:K1(d,c),P1(a.i),P1(a.l),d.row=15,d.g=b,e=!0}a.style.set(3);a.g=d;a.g.style=a.style;a.o.mode=1<<d.o;e?d.i=1:d.g!=b&&(d.g>b?(K1(d,c),O1(d,d.row-d.g,b)):d.row<b&&(b=d.g),d.g=b)},S1=function(a){a.style.set(1);
a.g=a.l;a.g.g=0;a.g.style=a.style;a.o.mode=1<<a.g.o},T1=function(a){a.style.set(4);
a.g=a.D;a.g.style=a.style;a.o.mode=1<<a.g.o},C1=function(a){this.i=a;
this.g=new H1;this.u=0;this.l=new Q1(a);this.A=new Q1(a);this.o=this.l},F1=function(a,b,c,d){a.g.update();
b=Ooa(b,c,a.g);switch(b.result){case 0:return;case 1:case 2:return}var e=b.ll;c=b.nl;if(32<=e||!e)a.i.mode&a.i.l&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.o.g,b&96&&M1(a,0,b),c&96&&M1(a,0,c),0!=b&&0!=c&&3==a.style.g&&K1(a,d));else if(e&16)a:if(!a.g.matches(e,c)&&(b=a.g,b.l=e,b.i=c,b.g=2,b=e&8?a.A:a.l,a.o=b,a.i.mode=1<<(a.u<<2)+(b.u<<1)+(4==b.style.g?1:0),(a.i.mode|1<<(a.u<<2)+(b.u<<1)+(4!=b.style.g?1:0))&a.i.l))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];a=c&16?4*((c&14)>>1):
0;c=b.g;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!=c.row){if(d<c.g&&(d=c.g,d==c.row))break;var f=1+c.row-c.g,k=1+d-c.g;N1(c,k,f,c.g);b=f;e=c.g;k<f?(f=k+e-f,0<f&&(b+=f,e-=f)):(f=f+e-k,0<f&&(e-=f));O1(c,b,e)}}c.row=d;c.i=a+1}else switch(e&7){case 1:switch(c&112){case 32:M1(b.g,0,32);break a;case 48:57==c?(d=b.g,L1(d).Md=0,32>d.i&&d.i++):M1(b.g,1,c&15)}break;case 2:c&32&&M1(b.g,2,c&31);break;case 3:c&32&&M1(b.g,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:S1(b);break;case 33:d=
b.g;1<d.i&&(--d.i,L1(d).Md=0);break;case 36:d=b.g;b=L1(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.l[a][c]==b){for(;32>=c;c++)d.l[a][c].reset();break}break;case 37:R1(b,2,d);break;case 38:R1(b,3,d);break;case 39:R1(b,4,d);break;case 40:M1(b.g,0,32);break;case 41:b.style.set(2);b.g=b.i;b.g.g=0;b.g.style=b.style;b.o.mode=1<<b.g.o;break;case 42:d=b.D;d.g=15;d.style.set(4);P1(d);T1(b);break;case 43:T1(b);break;case 44:a=b.i;switch(b.style.get()){case 1:case 2:case 3:K1(a,d)}O1(a,0,15);break;case 45:b:{a=
b.g;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.i=1;break b}case 3:}2>a.g&&(a.g=2,a.row<a.g&&(a.row=a.g));b=a.row-a.g+1;K1(a,d);N1(a,b,b+1,a.g-1);O1(a,a.row,1)}break;case 46:O1(b.l,0,15);break;case 47:K1(b.i,d),b.l.updateTime(b.o.i+0),d=b.l,b.l=b.i,b.i=d,S1(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.g,32<(d.i+=c&3)&&(d.i=32)}}},U1=function(a){g.G.apply(this,arguments)},V1=function(a){U1.call(this);
this.l={};this.F={};this.H={};this.u="_"+t1++;this.A=a;this.D={};this.i=this.g=null;this.B=!0},W1=function(a,b){var c=a.getAttribute(b);
if(null!=c)return parseFloat(c)},X1=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"==c},Y1=function(a,b){var c=W1(a,b);
return void 0!=c?c:null},$1=function(a,b){var c=a.getAttribute(b);
if(null!=c)return Z1.test(c),c},a2=function(a,b){var c={},d=b.getAttribute("ws");
g.Sa(c,d?a.H[d]:a.A);d=Y1(b,"mh");null!=d&&(c.zq=d);d=Y1(b,"ju");null!=d&&(c.textAlign=d);d=Y1(b,"pd");null!=d&&(c.Qe=d);d=Y1(b,"sd");null!=d&&(c.aA=d);d=$1(b,"wfc");null!=d&&(c.windowColor=d);d=W1(b,"wfo");void 0!=d&&(c.windowOpacity=d/255);return c},b2=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Sa(c,a.F[d]);d=Y1(b,"ap");null!=d&&(c.Kf=d);d=W1(b,"cc");null!=d&&(c.yl=d);d=W1(b,"ah");null!=d&&(c.Ie=d);d=W1(b,"rc");null!=d&&(c.rk=d);d=W1(b,"av");null!=d&&(c.ug=d);return c},c2=function(a,b,c,d){var e={};
g.Sa(e,b2(a,b));g.Sa(e,a2(a,b));d?g.ac(e,a.A)?(d=a.u,e=a.A):d="_"+t1++:d=b.getAttribute("id")||"_"+t1++;a=W1(b,"t")+c;b=W1(b,"d")||0x8000000000000;if(2==e.Qe||3==e.Qe)c=e.rk,e.rk=e.yl,e.yl=c;return new s1(a,b,0,d,e)},d2=function(a,b,c,d,e,f,k){w1.call(this,a,b,c,d,e,f,k);
this.type=1},e2=function(a,b,c){this.B=c;
this.version=this.A=this.o=this.g=0;this.i=new DataView(a);this.l=[]},f2=function(a){var b=a.g;
a.g+=1;return a.i.getUint8(b)},g2=function(a){var b=a.g;
a.g+=4;return a.i.getUint32(b)},h2=function(a,b){U1.call(this);
this.i=a;this.track="CC3"==b.l?4:0;this.g=new D1;this.g.l=1<<this.track},j2=function(a){if(g.v(a))return!1;
a=new e2(a,8,0);return i2(a)},i2=function(a){if(!(a.g<a.i.byteLength)||1380139777!=g2(a))return!1;
a.version=f2(a);if(1<a.version)return!1;f2(a);f2(a);f2(a);return!0},k2=function(a,b,c,d,e,f,k){w1.call(this,a,b,c,d,e,f,k);
g.J(this.element,"ytp-caption-window-rollup");this.type=2;this.D=[];this.I=this.H=this.ba=0;this.N=NaN;this.ya=0;this.Fa=null;this.ha=new g.M(this.XJ,433,this);g.H(this,this.ha)},Woa=function(a,b){return(a.B?b.offsetHeight:b.offsetWidth)+1},Xoa=function(a){if(isNaN(a.N)){var b=a.l.yl;
if(b){var c=g.Sd("SPAN");g.ce(c,"\u2013".repeat(b));g.vh(c,x1(a,a.l.xb));a.u.appendChild(c);a.N=c.offsetWidth;a.u.removeChild(c)}else a.N=0}return a.N},Yoa=function(a,b){if(!b)return"";
a.B&&1!=a.o.params.aA&&(b*=-1);return"translate"+(a.B?"X":"Y")+"("+b+"px)"},l2=function(a){a.D=[].concat(g.ea(document.getElementsByClassName("caption-visual-line")));
for(var b=a.o.params.rk,c=0,d=0,e=a.D.length-1;c<b&&-1<e;){var f=a.D[e];d+=a.B?f.offsetWidth:f.offsetHeight;c++;e--}a.D.length<b&&(d*=b/a.D.length);a.H=d;a.I=Math.max(Xoa(a),a.ya,Woa(a,a.u))},Zoa=function(a,b){l2(a);
var c=a.D.reduce(function(e,f){return(a.B?f.offsetWidth:f.offsetHeight)+e},0);
c=a.H-c;if(c!=a.ba){var d=0<c&&0==a.ba;b||isNaN(c)||d||(g.J(a.element,"ytp-rollup-mode"),g.fo(a.ha));g.vh(a.u,"transform",Yoa(a,c));a.ba=c}l2(a)},m2=function(){U1.call(this)},n2=function(a,b,c,d,e,f,k,l,m){switch(k.tagName){case "b":l.bold=!0;
break;case "i":l.He=!0;break;case "u":l.underline=!0}for(var n=0;n<k.childNodes.length;n++){var p=k.childNodes[n];if(3==p.nodeType){p=new r1(b,c,d,e.id,p.nodeValue,f||0<n,g.Xb(l)?void 0:l);m.push(p);var r=e;g.H(r,p);r.i.push(p)}else r={},g.Sa(r,l),n2(a,b,c,d,e,!0,p,r,m)}},o2=function(a){var b=0;
a=g.q(a.split(":"));for(var c=a.next();!c.done;c=a.next())b=60*b+parseFloat(c.value);return 1E3*b},p2=function(a,b,c,d){d=Object.assign({zq:0},d);
return new s1(a,b,c,"_"+t1++,d)},q2=function(a){g.G.call(this);
this.i=a;this.g=null},t2=function(a){g.TJ.call(this,a);
this.u=g.V(a);this.l=a.getVideoData();this.xa=g.pJ(a);this.I=a;var b=null,c=g.Ro("yt-html5-player-modules::subtitlesModuleData");c&&(b=new g.Bo(c));this.aa=b;this.o={xb:{}};this.A={xb:{}};this.H=[];this.N={};this.V={};this.P=!1;this.na=g.jU(this.l,this.I);this.ya=!!this.l.captionTracks.length;this.Ca=!!this.l.Ui;this.la="3"==this.u.l;b=a.app.o;c=!(!b||!b.Fk());this.ua=!(!b||!b.rh());this.B=this.la&&c&&!this.na;this.R=!this.B&&this.la&&this.ua&&this.na;this.i=this.D=this.F=this.O=this.ha=null;this.Y=
new q2(this.u);g.H(this,this.Y);c=b=this.g=null;this.B||(b=new g.bo(this.qA,void 0,this),g.H(this,b),c=new g.M(this.tL,2E3,this),g.H(this,c));this.X=b;this.ba=c;this.ca=new g.Jr(this);g.H(this,this.ca);this.B||this.ca.K(a,"resize",this.Ds);this.ca.K(a,"onPlaybackAudioChange",this.uH);this.ca.K(a,g.pD("captions"),this.wE,this);this.ca.K(a,"crx_captions",this.xE,this);r2(this,s2(this,"display-settings")||{})},u2=function(a){if(1==a.u.Of||1==a.l.Of||"alwayson"==g.fB(a.l,"yt:cc"))return!0;
if(2==a.u.Of){var b=s2(a,"module-enabled");if(null!=b)return!!b}if(a.l.captionTracks.length)var c=a.player.getAudioTrack().Jo;return"ON"==c||"on"==g.fB(a.l,"yt:cc")},v2=function(a,b){if(a.g&&(void 0===b||!b)||!a.l.captionTracks.length)return!1;
var c=a.player.getAudioTrack();return!!c.Hl||"FORCED_ON"==c.Jo},x2=function(a,b){if(a.i){if(a.D&&a.D.g)return a.D.g;
var c=b;c||(c=a.Ca?!1:a.ya?!1:!0);c=f1(a.i.i,c);for(var d=[a.l.Nf,a.u.Nf,g.fB(a.l,"yt:cc_default_lang")],e=0;e<d.length;e++)for(var f=0;f<c.length;f++)if(d1(c[f])==d[e])return c[f];return a.D&&a.D.Xo?a.D.Xo:(d=c.find(function(k){return k.isDefault}))?d:c[0]||w2(a)}return null},w2=function(a){return a.D&&a.D.Hl},y2=function(a){var b=w2(a);
return!!b&&a.g==b},z2=function(a,b){for(var c=a.I.app.o.ka().textTracks,d=a.g.toString(),e=0;e<c.length;e++){var f=c[e];
f.id==d&&(b?"showing"!=f.mode&&(f.mode="showing"):"showing"==f.mode&&(f.mode="disabled"))}},B2=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.P=c,a.P&&A2(a,"module-enabled",!!b));a.g=b;v2(a)&&(a.g=w2(a));a.load()},$oa=function(a,b){var c=a.xa.getVideoContentRect(!0).height;
if(!c)return null;var d=a.xa.getPlayerSize();switch(null!=b.params.zq?b.params.zq:1<b.i.length?1:0){case 1:return new d2(b,a.o,a.A,c,d.width,d.height,a.u.experiments);case 2:return new k2(b,a.o,a.A,c,d.width,d.height,a.u.experiments);default:return new w1(b,a.o,a.A,c,d.width,d.height,a.u.experiments)}},r2=function(a,b,c){var d=C2.xb;
a.o={};g.Sa(a.o,C2);a.o.xb={};g.Sa(a.o.xb,d);a.A={xb:{}};var e=b.backgroundOverride?a.A:a.o,f=b.background||d.background;Z1.test(f);e.xb.background=f;e=b.colorOverride?a.A:a.o;f=b.color||d.color;Z1.test(f);e.xb.color=f;e=b.windowColorOverride?a.A:a.o;f=b.windowColor||C2.windowColor;Z1.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.A:a.o;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.xb.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.A:a.o;f=b.fontSizeIncrement;null==f&&(f=d.fontSizeIncrement);
e.xb.fontSizeIncrement=f;f=b.fontStyleOverride?a.A:a.o;e=b.fontStyle;null==e&&(e=d.bold&&d.He?3:d.bold?1:d.He?2:0);f=f.xb;switch(e){case 1:f.bold=!0;delete f.He;break;case 2:delete f.bold;f.He=!0;break;case 3:f.bold=!0;f.He=!0;break;default:delete f.bold,delete f.He}e=b.textOpacityOverride?a.A:a.o;f=b.textOpacity;null==f&&(f=d.textOpacity);e.xb.textOpacity=f;e=b.windowOpacityOverride?a.A:a.o;f=b.windowOpacity;null==f&&(f=C2.windowOpacity);e.windowOpacity=f;e=b.charEdgeStyleOverride?a.A:a.o;f=b.charEdgeStyle;
null==f&&(f=d.charEdgeStyle);e.xb.charEdgeStyle=f;e=b.fontFamilyOverride?a.A:a.o;f=b.fontFamily;null==f&&(f=d.fontFamily);e.xb.fontFamily=f;a.loaded&&a.Ds();c&&A2(a,"display-settings",b)},E2=function(a,b){if(b&&!a.F){var c=u1({Qe:0,
lang:"en"});a.F=[c,new r1(c.start,c.end-c.start,0,c.id,"Captions look like this")];g.yJ(a.player,a.F)}else!b&&a.F&&(D2(a,a.F),a.F=null)},D2=function(a,b){g.AJ(a.player,b);
(0,g.B)(b,function(c){g.cb(this.H,c)},a);
a.X.uj()},s2=function(a,b){if(!a.aa)return null;
try{var c=a.aa.get(b)}catch(d){a.aa.remove(b)}return c},A2=function(a,b,c){if(a.aa)try{a.aa.set(b,c)}catch(d){}};
g.yD.prototype.Wi=g.ca(13,function(){for(var a=g.Fd(document,"track",void 0,this.g),b=0;b<a.length;b++)g.Xd(a[b])});
g.bW.prototype.Wi=g.ca(12,function(){this.g.Wi()});
g.yD.prototype.Fk=g.ca(11,function(){return!!this.g.textTracks});
g.bW.prototype.Fk=g.ca(10,function(){return this.g.Fk()});
g.yD.prototype.Pi=g.ca(9,function(a){for(var b=0;b<a.length;b++)this.g.appendChild(a[b])});
g.bW.prototype.Pi=g.ca(8,function(a){this.g.Pi(a)});
g.oC.prototype.rh=g.ca(7,function(){});
g.yD.prototype.rh=g.ca(6,function(){return!(!this.g.textTracks||!this.g.textTracks.addEventListener)});
g.bW.prototype.rh=g.ca(5,function(){return this.g.rh()});
g.cz.prototype.Eq=g.ca(3,function(a){return a?this.toString()==a.toString():!1});
g.gt.prototype.Ql=g.ca(2,function(a){return(a=this.Vf(a))?a.i:0});
g.cw.prototype.Ql=g.ca(1,function(){return 0});
var apa=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Adlm|Arab|Hebr|Nkoo|Rohg|Thaa))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i,Koa=/#(.)(.)(.)/,Joa=/^#(?:[0-9a-f]{3}){1,2}$/i,Z1=/^#(?:[0-9a-f]{3}){1,2}$/i;g.t(h1,g.G);h1.prototype.Xy=function(){return!1};
h1.prototype.T=function(){this.vg();g.G.prototype.T.call(this)};
g.t(i1,h1);i1.prototype.uq=function(a,b,c){b=this.qj(a,b);var d=(0,g.z)(function(e){this.g=null;c(e.responseText,a)},this);
this.vg();this.g=g.wq(b,{format:"RAW",onSuccess:d,withCredentials:!0})};
i1.prototype.wq=function(a){if(this.l)for(var b=g.q(this.l.captionTracks),c=b.next();!c.done;c=b.next())g1(this.i,c.value);a()};
i1.prototype.qj=function(a,b){var c=a.Ib(),d={fmt:b};a.g&&(d.tlang=d1(a));return g.fq(c,d)};
i1.prototype.vg=function(){this.g&&this.g.abort()};
j1.prototype.contains=function(a){a=g.ob(this.Ta,a);return 0<=a||0>a&&1==(-a-1)%2};
j1.prototype.length=function(){return this.Ta.length/2};
g.t(k1,g.G);g.h=k1.prototype;g.h.T=function(){g.G.prototype.T.call(this);this.i&&this.i.cancel()};
g.h.Zw=function(a){var b=this;if(this.D.Ug())var c=this.u.K(this.o,"progresssync",function(){b.D.index.Fb()&&(b.reset(),b.g=null,l1(b,b.o.getCurrentTime()),b.u.Na(c))});
else l1(this,a)};
g.h.nF=function(){l1(this,this.o.getCurrentTime())};
g.h.reset=function(){this.A=new j1;this.i&&(this.i.cancel(),this.i=null)};
g.h.qw=function(){var a;if(a=null!==this.g)a=this.g,a=a.g.yf(a);!a||this.i||this.g&&30<this.g.startTime-this.o.getCurrentTime()||(a=this.g,a=a.g.bi(a),a.g[0].duration&&(this.A.contains(a.g[0].i)||m1(this,a),this.g=g.Va(a.g)));this.H.start()};
g.h.SJ=function(a){var b=!(this.B?a.response:a.responseText)||400<=a.status,c=g.jw(a);c?(a=g.rv(this.l,this.I,{}),b=this.l,g.mv(b.i,a,c),b.requestId=a.get("req_id"),m1(this,this.l)):(b||null===this.F||(this.B?this.F(a.response,1E3*(this.l.g[0].startTime+this.o.lc())):this.F(a.responseText,1E3*(this.l.g[0].startTime+this.o.lc()))),this.i=this.l=null)};
g.t(n1,h1);g.h=n1.prototype;g.h.uq=function(a,b,c){this.vg();b=Moa(this,a.getId());b||(b=a.i,b=this.g.i?p1(this,b,"386"):p1(this,b));if(b){var d=1E3*(b.index.Ql(b.index.he())-b.index.Ic(b.index.he()));this.l=new k1(new g.Ju,this.B,b,function(e,f){c(e,a,f,d)},this.A||g.Bu(b.info),(0,g.z)(function(){this.l&&this.l.reset();
this.o=!0},this))}};
g.h.Xy=function(){var a=this.o;this.o=!1;return a};
g.h.wq=function(a){var b;this.A?b=[new g.cz({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.cz({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:b=this.g.i?o1(this,"386"):o1(this);b=g.q(b);for(var c=b.next();!c.done;c=b.next())g1(this.i,c.value);a()};
g.h.vg=function(){this.l&&(this.l.dispose(),this.l=null)};
g.h.qj=function(){return""};
g.t(q1,h1);q1.prototype.uq=function(a,b,c){b=this.qj(a,b);var d=(0,g.z)(function(e){this.g=null;c(e.responseText,a)},this);
this.vg();this.g=g.wq(b,{format:"RAW",onSuccess:d,withCredentials:!0})};
q1.prototype.wq=function(a){var b=this.o,c={type:"list",tlangs:1,v:this.l,vssids:1};this.A&&(c.asrs=1);b=g.fq(b,c);c=(0,g.z)(function(d){this.g=null;if((d=d.responseXML)&&d.firstChild){for(var e=g.q(d.getElementsByTagName("track")),f=e.next();!f.done;f=e.next()){var k=f.value;f=k.getAttribute("lang_code");var l=k.getAttribute("lang_translated"),m=k.getAttribute("name"),n=k.getAttribute("kind"),p=k.getAttribute("id"),r="true"==k.getAttribute("lang_default"),u="true"==k.getAttribute("cantran");k=k.getAttribute("vss_id");
g1(this.i,new g.cz({languageCode:f,languageName:l,name:m,kind:n,id:p,is_servable:!0,is_translateable:u,vss_id:k,is_default:r}))}d=d.getElementsByTagName("target");e=d.length;for(f=0;f<e;f++)l=d[f].getAttribute("lang_code"),m=d[f].getAttribute("lang_translated"),n=d[f].getAttribute("lang_original"),p=d[f].getAttribute("id"),r="true"==d[f].getAttribute("lang_default"),l={languageCode:l,languageName:m,languageOriginal:n,id:p,isDefault:r},this.B[l.languageCode]=l.languageName,this.u.push(l)}a()},this);
this.vg();this.g=g.wq(b,{format:"RAW",onSuccess:c,withCredentials:!0})};
q1.prototype.qj=function(a,b){var c=this.o,d={v:this.l,type:"track",lang:a.i,name:a.getName(),kind:a.o,fmt:b};a.g&&(d.tlang=d1(a));return c=g.fq(c,d)};
q1.prototype.vg=function(){this.g&&this.g.abort()};var Noa=["left","right","center","justify"];var C2={windowColor:"#080808",windowOpacity:0,textAlign:2,Kf:7,Ie:50,ug:100,xb:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.t(r1,g.mD);r1.prototype.toString=function(){return g.mD.prototype.toString.call(this)};g.t(s1,g.mD);s1.prototype.toString=function(){return g.mD.prototype.toString.call(this)};
var t1=0;g.t(w1,g.T);g.h=w1.prototype;g.h.mF=function(a,b){var c=g.Lh(this.element,this.element.parentElement);this.na=a-c.x;this.ua=b-c.y;g.J(this.element,"ytp-dragging")};
g.h.lF=function(a,b){var c=g.Oh(this.element),d=a-this.na-.02*this.Ra,e=b-this.ua-.02*this.Oa,f=(d+c.width/2)/this.X*3;f=Math.floor(g.qd(f,0,2));var k=(e+c.height/2)/this.xa*3;k=Math.floor(g.qd(k,0,2));var l=f+3*k;d=(d+f/2*c.width)/this.X;d=100*g.qd(d,0,1);c=(e+k/2*c.height)/this.xa;c=100*g.qd(c,0,1);this.o.params.Kf=l;this.o.params.ug=c;this.o.params.Ie=d;this.l.Kf=l;this.l.ug=c;this.l.Ie=d;this.sz()};
g.h.kF=function(){g.Wn(this.element,"ytp-dragging")};
g.h.sz=function(){this.oh(this.A)};
g.h.oh=function(a){var b=Math.min(this.tv(),this.X),c=this.qv(),d="";3==this.o.params.Qe&&(d="rotate(180deg)");g.vh(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.xo(a);a={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.l.Ie+2;d=this.l.Kf;switch(d){case 0:case 3:case 6:a.left=e+"%";break;case 1:case 4:case 7:a.left=e+"%";e=this.u.offsetWidth;
b||e?(b=b||e+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-e+"%"}b=.96*this.l.ug+2;switch(d){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.vh(this.element,a)};
g.h.xo=function(a){var b;for(b=0;b<a.length&&a[b]==this.A[b];b++);if(this.O||this.A.length>b)b=0,this.O=!1,this.A=[],this.F=this.V=this.R=null,g.Vd(this.u);for(;b<a.length;b++)A1(this,a[b])};
g.h.tv=function(){return 0};
g.h.qv=function(){return 0};
g.h.toString=function(){return g.T.prototype.toString.call(this)};B1.prototype.u=function(){};D1.prototype.clear=function(){this.o=this.i=this.mode=0;this.g=[];this.reset()};
D1.prototype.reset=function(){this.mode=0;this.u.reset(0);this.A.reset(1)};
var E1=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];G1.prototype.set=function(a){this.g=a};
G1.prototype.get=function(){return this.g};
H1.prototype.clear=function(){this.g=0};
H1.prototype.update=function(){this.g=2==this.g?1:0};
H1.prototype.matches=function(a,b){return 0!=this.g&&a==this.l&&b==this.i};
I1.prototype.Sf=function(a){this.Md=a.Md;this.timestamp=a.timestamp};
I1.prototype.reset=function(){this.timestamp=this.Md=0};
J1.prototype.updateTime=function(a){for(var b=1;15>=b;++b)for(var c=1;32>=c;++c)this.l[b][c].timestamp=a};
J1.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.l[b][c];a=0==d.Md?a+"_":a+String.fromCharCode(d.Md)}a+="\n"}return a};
J1.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.l[b][c].reset();this.o=a;this.g=0;this.i=this.row=1};
var Roa=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],Soa=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],Toa=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],Uoa=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];Q1.prototype.reset=function(a,b){this.u=b;this.style.set(2);this.i=this.A;this.l=this.B;this.g=this.i;var c=(a<<2)+(b<<1);this.A.reset(c);this.B.reset(c);this.D.reset((a<<2)+(b<<1)+1)};
C1.prototype.reset=function(a){this.u=a;this.g.clear();this.o=this.l;this.l.reset(a,0);this.A.reset(a,1)};g.t(U1,g.G);U1.prototype.reset=function(){};g.t(V1,U1);V1.prototype.reset=function(){this.D={};this.i=this.g=null;this.B=!0};
V1.prototype.o=function(a,b){var c=a.firstChild;c.getAttribute("format");b=b||0;Number.isFinite(b);c=Array.from(c.childNodes);c=g.q(c);for(var d=c.next();!d.done;d=c.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "head":var e=d;break;case "body":var f=d}if(e)for(e=Array.from(e.childNodes),e=g.q(e),c=e.next();!c.done;c=e.next())if(c=c.value,1==c.nodeType)switch(c.tagName){case "pen":d=c.getAttribute("id");var k=this.l,l={},m=c.getAttribute("p");m&&g.Sa(l,this.l[m]);m=X1(c,"b");null!=m&&(l.bold=
m);m=X1(c,"i");null!=m&&(l.He=m);m=X1(c,"u");null!=m&&(l.underline=m);m=Y1(c,"et");null!=m&&(l.charEdgeStyle=m);m=Y1(c,"of");null!=m&&(l.offset=m);m=$1(c,"bc");null!=m&&(l.background=m);m=$1(c,"ec");null!=m&&(l.ou=m);m=$1(c,"fc");null!=m&&(l.color=m);m=Y1(c,"fs");null!=m&&0!=m&&(l.fontFamily=m);m=W1(c,"sz");void 0!=m&&(l.fontSizeIncrement=m/100-1);m=W1(c,"bo");void 0!=m&&(l.backgroundOpacity=m/255);m=W1(c,"fo");void 0!=m&&(l.textOpacity=m/255);m=Y1(c,"rb");null!=m&&(l.tk=m);c=Y1(c,"hg");null!=c&&
(l.OP=c);k[d]=l;break;case "ws":d=c.getAttribute("id");this.H[d]=a2(this,c);break;case "wp":d=c.getAttribute("id"),this.F[d]=b2(this,c)}if(f){e=b;c=[];f=Array.from(f.childNodes);f=g.q(f);for(d=f.next();!d.done;d=f.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "w":this.g=c2(this,d,e,!1);g.H(this,this.g);(d=this.D[this.g.id])&&d.end>this.g.start&&(d.end=this.g.start);this.D[this.g.id]=this.g;c.push(this.g);break;case "p":var n=e;k=[];l=d.getAttribute("w")||this.u;m=!!X1(d,"a");n=(W1(d,"t")||
0)+n;var p=W1(d,"d")||5E3;m||(!this.B&&this.i&&this.i.windowId==l&&this.i.end>n&&(this.i.end=n),this.i&&"\n"==this.i.text&&(this.i.text=""));var r=m?6:5,u=this.l[d.getAttribute("p")],y=d.childNodes;y.length&&(this.B=null!=d.getAttribute("d"));for(var D=0;D<y.length;D++){var E=y[D];0<D&&(m=!0);var K=void 0;1==E.nodeType&&(K=E);if(K&&"s"==K.tagName)if((E=this.l[K.getAttribute("p")])&&1==E.tk){E=n;var X=p,la=l,Ja=m,Fa=r;var Ka=K;var fd=y[D+1];var wd=y[D+2],kc=y[D+3];Ka.getAttribute("p");W1(Ka,"t");W1(fd,
"t");W1(wd,"t");W1(kc,"t");K=g.Sd("RUBY");Ka=Ka.textContent;var Pk=g.Sd("SPAN");Pk.innerText=Ka;K.appendChild(Pk);fd.getAttribute("p");Pk=g.Sd("RP");Ka=fd.textContent;Pk.innerText=Ka;K.appendChild(Pk);fd=this.l[wd.getAttribute("p")];Ka=wd.textContent;wd=g.Sd("RT");wd.innerText=Ka;K.appendChild(wd);if(4==fd.tk||6==fd.tk)g.vh(K,"ruby-position","over"),g.vh(K,"-webkit-ruby-position","before");else if(5==fd.tk||7==fd.tk)g.vh(K,"ruby-position","under"),g.vh(K,"-webkit-ruby-position","after");kc.getAttribute("p");
Ka=kc.textContent;kc=g.Sd("RP");kc.innerText=Ka;K.appendChild(kc);E=new r1(E,X,Fa,la,K,Ja,null);D+=3}else kc=K,E=n,X=p,la=l,Ja=m,Fa=r,K=kc.textContent?kc.textContent:"",Ka=this.l[kc.getAttribute("p")],kc=W1(kc,"t")||0,E=new r1(E+kc,X-kc,Fa,la,K,Ja,Ka);else E=new r1(n,p,r,l,E.textContent||"",m,u);k.push(E);this.i=E}if(0<k.length)for(k[0].windowId==this.u&&(this.g=c2(this,d,e,!0),g.H(this,this.g),c.push(this.g)),d=g.q(k),k=d.next();!k.done;k=d.next())k=k.value,k.windowId=this.g.id,l=this.g,g.H(l,k),
l.i.push(k),c.push(k)}e=c}else e=[];return e};g.t(d2,w1);d2.prototype.xo=function(a){var b=this.o.i;w1.prototype.xo.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.i==e)var d=f;else{d={};g.Sa(d,c.i);g.Sa(d,bpa);var e=c.i;var f=d}A1(this,c,d)}};
var bpa={qD:!0};g.t(e2,B1);e2.prototype.u=function(a,b,c,d,e){if(c<d){var f="_"+t1++;c=c/1E3-this.B;d=d/1E3-this.B;a=new s1(c,d-c,5,f,{textAlign:0,Kf:0,Ie:2.5*b,ug:5.33*a});e=new r1(c,d-c,5,f,e);this.l.push(a);this.l.push(e)}};
g.t(h2,U1);h2.prototype.o=function(a){a=new e2(a,a.byteLength,this.i);if(i2(a)){for(;a.g<a.i.byteLength;)for(0==a.version?a.o=g2(a)*(1E3/45):1==a.version&&(a.o=4294967296*g2(a)+g2(a)),a.A=f2(a);0<a.A;a.A--){var b=f2(a),c=f2(a),d=f2(a);b&4&&(b&3)==this.track&&(0==this.track||1==this.track)&&(b=this.g,b.g.push({time:a.o,type:this.track,iu:c,ju:d,order:b.g.length}))}Qoa(this.g,a);return a.l}return[]};
h2.prototype.reset=function(){this.g.clear()};g.t(k2,w1);g.h=k2.prototype;g.h.sz=function(){g.go(this.ha)};
g.h.XJ=function(){g.Wn(this.element,"ytp-rollup-mode");this.oh(this.Fa,!0)};
g.h.qv=function(){return this.B?this.I:this.H};
g.h.tv=function(){return this.B?this.H:this.I};
g.h.oh=function(a,b){this.Fa=a;if(this.o.params.rk){for(var c=0,d=0;d<this.A.length&&c<a.length;d++)this.A[d]==a[c]&&c++;0<c&&c<a.length&&(a=this.A.concat(a.slice(c)));this.ya=this.I;this.H=this.I=0;w1.prototype.oh.call(this,a);Zoa(this,b);w1.prototype.oh.call(this,a)}else w1.prototype.oh.call(this,a)};g.t(m2,U1);
m2.prototype.o=function(a,b){for(var c=[],d=a.split(cpa),e=1;e<d.length;e++){var f=d[e],k=b;if(""!=f&&!dpa.test(f)){var l=F2.exec(f);if(l&&4<=l.length){var m=o2(l[1]),n=o2(l[2])-m;m+=k;var p,r=p=void 0,u=void 0,y=void 0,D=l[3];l={textAlign:2};D=g.q(D?D.split(" "):[]);for(var E=D.next();!E.done;E=D.next())if(E=E.value.split(":"),2==E.length){var K=E[1];switch(E[0]){case "line":E=K.split(",");E[0].endsWith("%")&&(y=E[0],l.ug=Number.parseInt(y,10),2==E.length&&(u=E[1].trim()));break;case "position":E=K.split(",");
r=E[0];l.Ie=Number.parseInt(r,10);2==E.length&&(p=E[1].trim());break;case "align":switch(K){case "start":l.textAlign=0;break;case "middle":l.textAlign=2;break;case "end":l.textAlign=1}}}y||(l.ug=100,u||(u="end"));if(!r)switch(l.textAlign){case 0:l.Ie=0;break;case 1:l.Ie=100;break;default:l.Ie=50}r=0;switch(u){case "center":r+=3;break;case "end":r+=6;break;default:r+=0}switch(p){case "line-left":r+=0;break;case "center":r+=1;break;case "line-right":r+=2;break;default:switch(l.textAlign){case 0:r+=
0;break;case 2:r+=1;break;case 1:r+=2}}l.Kf=0>r||8<r?7:r;p=l;f=f.substring(F2.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");r=p;p=f;f={};if(0>p.indexOf("<")&&0>p.indexOf("&"))k=p2(m,n,5,r),n=new r1(m,n,5,k.id,p,!1,g.Xb(f)?void 0:f),c.push(k),c.push(n),g.H(k,n),k.i.push(n);else for(u=p.split(epa),1==u.length?(p=5,r=p2(m,n,p,r)):(y=p=6,r=Object.assign({yl:32},r),r=new s1(m,n,y,"_"+t1++,r)),c.push(r),y=m,l=0;l<u.length;l++)D=u[l],0==l%2?(E=g.Yn("<html>"+D+"</html>"),E.getElementsByTagName("parsererror").length?
(K=E.createElement("span"),K.appendChild(E.createTextNode(D))):K=E.firstChild,n2(this,y,n-(y-m),p,r,0<l,K,f,c)):y=o2(D)+k}F2.lastIndex=0}}return c};
var dpa=/^NOTE/,cpa=/(?:\r\n|\r|\n){2,}/,F2=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),epa=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.t(q2,g.G);q2.prototype.clear=function(){this.g&&this.g.dispose();this.g=null};
q2.prototype.reset=function(){this.g&&this.g.reset()};
q2.prototype.T=function(){this.clear();g.G.prototype.T.call(this)};g.t(t2,g.TJ);g.h=t2.prototype;g.h.T=function(){if(this.B||this.R){var a=this.I.app.o;a&&a.Wi()}else E2(this,!1);g.TJ.prototype.T.call(this)};
g.h.yk=function(){return this.la?this.B||this.R:v2(this)?!0:u2(this)};
g.h.load=function(){g.TJ.prototype.load.call(this);this.D=this.player.getAudioTrack();if(this.i)this.g&&(this.Y.clear(),this.B?z2(this,!0):3!=this.player.getPresentingPlayerType()&&this.i.uq(this.g,"srv3",(0,g.z)(this.EK,this))),this.g&&!y2(this)?this.player.ma("captionschanged",c1(this.g)):this.player.ma("onCaptionsTrackListChanged");else{var a;this.na?a=new n1(this.l.ga,this.player):this.ya?a=new i1(this.u,this.l,this.player.getAudioTrack()):a=new q1(this.l.Ui,this.l.videoId,this.l.Nf||this.u.Nf||
g.fB(this.l,"yt:cc_default_lang")||this.u.Vb,this.l.Ho,this.u);this.i=a;g.H(this,this.i);a.wq((0,g.z)(this.DK,this))}};
g.h.unload=function(){this.B&&this.g?z2(this,!1):(this.ba&&g.ho(this.ba),g.BJ(this.player,"captions"),this.H=[],this.i&&this.i.vg(),this.Y.clear(),this.F&&g.yJ(this.player,this.F),this.Ds());g.TJ.prototype.unload.call(this);var a=g.W(this.player.app);a&&a.o&&g.cC(a.o.l);this.player.ma("captionschanged",{})};
g.h.DK=function(){var a;this.P||u2(this)?a=x2(this,this.P):v2(this)&&(a=w2(this));if(this.B||this.R){for(var b=f1(this.i.i,!0),c=[],d=0;d<b.length;d++){var e=b[d],f={kind:"subtitles",label:g.dz(e),srclang:d1(e),id:e.toString()};this.R||(f.src=this.i.qj(e,"vtt"));e==a&&(f["default"]=1);c.push(g.Rd("TRACK",f))}this.I.app.o.Pi(c);a=this.I.app.o.ka();this.ua&&this.ca.K(a.textTracks,"change",this.FK)}else!this.g&&a&&B2(this,a),this.player.ma("onCaptionsTrackListChanged"),this.player.ma("onApiChange")};
g.h.FK=function(){for(var a=this.I.app.o.ka().textTracks,b=null,c=0;c<a.length;c++)if("showing"==a[c].mode)a:{b=f1(this.i.i,!0);for(var d=0;d<b.length;d++)if(b[d].toString()==a[c].id){b=b[d];break a}b=null}(this.loaded?this.g:null)!=b&&B2(this,b,!0)};
g.h.ZL=function(){!this.g&&this.B||this.unload()};
g.h.EK=function(a,b,c,d){if(a){this.i.Xy()&&(this.H=[],g.BJ(this.I,"captions"),this.X.uj(),this.Y.reset());var e=this.Y;c=c||0;d=d||0;if(!g.v(a)){var f=new DataView(a);if(8<=f.byteLength&&1718909296==f.getUint32(4)&&(f=g.Ct(f,0,1835295092),a=a.slice(f.dataOffset,f.dataOffset+f.size),!j2(a))){a=new Uint8Array(a);f=[];for(var k=0,l=0;k<a.length;){var m=a[k++];if(128>m)f[l++]=String.fromCharCode(m);else if(191<m&&224>m){var n=a[k++];f[l++]=String.fromCharCode((m&31)<<6|n&63)}else if(239<m&&365>m){n=
a[k++];var p=a[k++],r=a[k++];m=((m&7)<<18|(n&63)<<12|(p&63)<<6|r&63)-65536;f[l++]=String.fromCharCode(55296+(m>>10));f[l++]=String.fromCharCode(56320+(m&1023))}else n=a[k++],p=a[k++],f[l++]=String.fromCharCode((m&15)<<12|(n&63)<<6|p&63)}a=f.join("")}}if(a)try{if(g.v(a)){if("WEBVTT"==a.substring(0,6)){b=a;var u=c;e.g||(e.g=new m2);var y=e.g.o(b,u);.01>Math.random()&&g.Cp(Error("Deprecated subtitles format in web player: WebVTT"));var D=y}else b:{y=a;u=g.Yn(y);if(!u||!u.firstChild){var E=Error("Invalid caption track data");
E.params=y;throw E;}if("timedtext"==u.firstChild.tagName){if(3==parseInt(u.firstChild.getAttribute("format"),10)){if(!e.g){y={};var K=d1(b);K&&(y.lang=K,apa.test(K)&&(y.Qe=1));e.g=new V1(y,e.i)}D=e.g.o(u,c);break b}var X=Error("Unsupported subtitles format in web player (Format2)");X.params=y;throw X;}if("transcript"==u.firstChild.tagName){var la=Error("Unsupported subtitles format in web player (Format1)");la.params=y;throw la;}var Ja=Error("Invalid caption track data");Ja.params=y;throw Ja;}var Fa=
D}else{D=a;u=c;K=d;if(!j2(D))throw Error("Invalid binary caption track data");e.g||(e.g=new h2(K,b));Fa=e.g.o(D,u)}var Ka=Fa}catch(fd){g.N(fd),e.clear(),Ka=[]}else Ka=[];g.yJ(this.player,Ka);!this.P||this.R||y2(this)||g.Ey(this.u)||g.Fy(this.u)||(g.ho(this.ba),Ka=u1({Kf:0,Ie:5,ug:5,rk:2,textAlign:0,Qe:0,lang:"en"}),this.O=[Ka],e=["Click "," for settings"],this.ha||(Fa=new g.EB(g.bP()),g.H(this,Fa),this.ha=Fa.element),Fa=Ka.end-Ka.start,(b=g.dz(this.g))&&this.O.push(new r1(Ka.start,Fa,0,Ka.id,b)),
this.O.push(new r1(Ka.start,Fa,0,Ka.id,e[0]),new r1(Ka.start,Fa,0,Ka.id,this.ha,!0),new r1(Ka.start,Fa,0,Ka.id,e[1],!0)),g.yJ(this.player,this.O),g.fo(this.ba));!this.P||this.R||y2(this)||(A2(this,"module-enabled",!0),this.D&&(this.D.g=this.g),(Ka=g.W(this.player.app))&&Ka.o&&g.cC(Ka.o.l));this.P=!1}};
g.h.wE=function(a){this.H.push(a);this.X.uj()};
g.h.xE=function(a){g.cb(this.H,a);this.i instanceof n1&&this.i.A&&g.AJ(this.player,[a]);this.X.uj()};
g.h.nL=function(a){if(a instanceof s1){var b=this.N[a.id];b&&b.o!=a&&(b.dispose(),delete this.N[a.id],b=null);b||(b=$oa(this,a))&&(this.N[a.id]=b)}else b=a.windowId,this.V[b]||(this.V[b]=[]),this.V[b].push(a)};
g.h.tL=function(){D2(this,this.O);this.O=null};
g.h.qA=function(){this.X.stop();g.Yb(this.V);this.H.sort(g.oD);var a=this.H;if(this.F){var b=(0,g.Yd)(a,function(c){return-1==this.F.indexOf(c)},this);
b.length&&(a=b)}(0,g.B)(a,this.nL,this);g.Kb(this.N,function(c,d){this.V[d]?(c.element.parentNode||g.FJ(this.player,c.element,4),c.oh(this.V[d])):(c.dispose(),delete this.N[d])},this)};
g.h.xL=function(){r2(this,{},!0)};
g.h.FC=function(){var a=C2.xb;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.He?3:a.bold?1:a.He?2:0,textOpacity:a.textOpacity,windowColor:C2.windowColor,windowOpacity:C2.windowOpacity};var b=s2(this,"display-settings")||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&
(a.backgroundOpacity=b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&
(a.fontSizeIncrement=b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);
null!=b.windowOpacity&&(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.h.vA=function(a,b){var c={};g.Sa(c,s2(this,"display-settings"));g.Sa(c,a);r2(this,c,b);this.player.M("captionssettingschanged")};
g.h.Ds=function(){!this.B&&this.loaded&&(g.Kb(this.N,function(a,b){a.dispose();delete this.N[b]},this),this.qA())};
g.h.Yb=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.qd(b,-2,4);this.vA({fontSizeIncrement:c});return c;case "reload":b&&!this.B&&B2(this,this.g,!0);break;case "stickyLoading":void 0!=b&&this.u.tb&&A2(this,"module-enabled",!!b);break;case "track":if(!this.i)return{};if(b){if(this.B)break;if(!g.Oa(b))break;if(g.Xb(b)){B2(this,null,!0);break}for(var d=f1(this.i.i,!0),e=0;e<d.length;e++){var f=d[e];f.i!=b.languageCode||c&&f.l!=b.languageName||(c=b.translationLanguage?Ioa(f,b.translationLanguage):
f)}!c||c==this.g&&this.loaded||B2(this,c,!0)}else return this.loaded&&this.g&&!y2(this)?c1(this.g):{};return"";case "tracklist":return this.i?(0,g.F)(f1(this.i.i,!(!b||!b.includeAsr)),function(k){return c1(k)}):[];
case "translationLanguages":return this.i?this.i.u:[];case "sampleSubtitles":this.B||void 0==b||E2(this,!!b)}};
g.h.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.u.tb&&a.push("stickyLoading");return a};
g.h.sj=function(){var a=this.g;return a?{cc:a.A}:{}};
g.h.gA=function(){this.loaded&&this.g&&!y2(this)?(A2(this,"module-enabled",!1),this.unload(),v2(this,!0)&&B2(this,w2(this),!1)):B2(this,y2(this)||!this.g?x2(this,!0):this.g,!0)};
g.h.uH=function(){var a=y2(this);v2(this,a)?B2(this,this.player.getAudioTrack().Hl,!1):this.l.captionTracks.length&&(this.loaded&&this.unload(),this.yk()&&(a?B2(this,x2(this),!1):this.load()))};g.pU.captions=t2;})(_yt_player);
