(function(g){var window=this;var G2=function(a,b,c){var d=b.oa();g.L(a.element,"ytp-suggestion-set",!!d.videoId);var e=b.getPlaylistId();c=b.yc(c?c:"mqdefault.jpg");var f=b instanceof g.FA&&b.lengthSeconds?g.DP(b.lengthSeconds):null,k=!!e;e=k&&"RD"==(new g.qD(e.substr(0,2),e.substr(2))).type;var l=b instanceof g.FA?b.sa:null;d={title:b.title,author:b.author,author_and_views:d.shortViewCount?b.author+" \u2022 "+d.shortViewCount:b.author,aria_label:b.Qi||g.FM("Watch $TITLE",{TITLE:b.title}),duration:f,url:b.tj(),is_live:l,is_list:k,
is_mix:e,background:c?"background-image: url("+c+")":""};b instanceof g.sD&&(d.playlist_length=b.getLength());a.update(d)},H2=function(a,b){g.JB.call(this,{C:"div",
W:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.player=a;this.created=!1},I2=function(a){g.T.call(this,{C:"div",
W:["ytp-upnext","ytp-player-content"],L:{"aria-label":"{{aria_label}}"},J:[{C:"div",G:"ytp-cued-thumbnail-overlay-image",L:{style:"{{background}}"}},{C:"span",G:"ytp-upnext-top",J:[{C:"span",G:"ytp-upnext-header",U:"Up Next"},{C:"span",G:"ytp-upnext-title",U:"{{title}}"},{C:"span",G:"ytp-upnext-author",U:"{{author}}"}]},{C:"a",G:"ytp-upnext-autoplay-icon",L:{role:"button",href:"{{url}}","aria-label":"Play next video"},J:[{C:"svg",L:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},J:[{C:"circle",
G:"ytp-svg-autoplay-circle",L:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{C:"circle",G:"ytp-svg-autoplay-ring",L:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{C:"path",G:"ytp-svg-fill",L:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{C:"span",G:"ytp-upnext-bottom",J:[{C:"span",G:"ytp-upnext-cancel"},{C:"span",G:"ytp-upnext-paused",U:"Autoplay is paused"}]}]});
this.A=null;var b=this.i["ytp-upnext-cancel"];this.A=new g.T({C:"button",W:["ytp-upnext-cancel-button","ytp-button"],L:{tabindex:"0","aria-label":"Cancel autoplay"},U:"Cancel"});g.H(this,this.A);this.A.da("click",this.zH,this);this.A.g(b);this.l=a;this.I=this.i["ytp-svg-autoplay-ring"];this.D=this.B=this.o=this.u=null;this.F=new g.M(this.xl,5E3,this);g.H(this,this.F);this.H=0;this.K(this.i["ytp-upnext-autoplay-icon"],"click",this.qJ);this.Xx();this.K(a,"autonavvisibility",this.Xx);this.K(a,"mdxnowautoplaying",
this.CI);this.K(a,"mdxautoplaycanceled",this.DI);this.K(a,"mdxautoplayupnext",this.uA);3==this.l.getPresentingPlayerType()&&(a=(a=g.qJ(g.kJ(this.l)))?a.DC():null)&&this.uA(a)},J2=function(a,b){if(!a.o){g.Rp("a11y-announce","Up Next "+a.u.title);
a.H=g.P();a.o=new g.M((0,g.z)(a.wo,a,b),25);a.wo(b);var c=b||g.R(g.V(a.l).experiments,"autoplay_time")||1E4;a.l.ma("onAutonavCoundownStarted",c)}g.Wn(a.element,"ytp-upnext-autoplay-paused")},L2=function(a){K2(a);
a.H=g.P();a.wo();g.J(a.element,"ytp-upnext-autoplay-paused")},K2=function(a){a.o&&(a.o.dispose(),a.o=null)},M2=function(a,b){b=void 0===b?!1:b;
if(g.Q(g.V(a.l).experiments,"autonav_notifications")&&b&&window.Notification&&document.hasFocus){var c=Notification.permission;"default"==c?Notification.requestPermission():"granted"!=c||document.hasFocus()||(c=a.u.oa(),a.xl(),a.B=new Notification("Up Next",{body:c.title,icon:c.yc()}),a.D=a.K(a.B,"click",a.iJ),a.F.start())}K2(a);a.l.nextVideo(!1,b)},N2=function(a){H2.call(this,a,"subscribecard-endscreen");
var b=a.getVideoData();this.l=new g.T({C:"div",G:"ytp-subscribe-card",J:[{C:"img",G:"ytp-author-image",L:{src:b.Kd}},{C:"div",G:"ytp-subscribe-card-right",J:[{C:"div",G:"ytp-author-name",U:b.author},{C:"div",G:"html5-subscribe-button-container"}]}]});g.H(this,this.l);this.l.g(this.element);this.o=new g.hV("Subscribe",null,"Unsubscribe",null,!0,!1,b.Hf,b.subscribed,"trailer-endscreen",null,null,a);g.H(this,this.o);this.o.g(this.l.i["html5-subscribe-button-container"]);this.hide()},O2=function(a){var b=
g.V(a),c=g.Iw||g.yh?{style:"will-change: opacity"}:void 0,d=b.i,e=["ytp-videowall-still"];
b.g&&e.push("ytp-videowall-show-text");g.T.call(this,{C:"a",W:e,L:{href:"{{url}}",target:d?b.u:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},J:[{C:"div",G:"ytp-videowall-still-image",L:{style:"{{background}}"}},{C:"span",G:"ytp-videowall-still-info",J:[{C:"span",G:"ytp-videowall-still-info-bg",J:[{C:"span",G:"ytp-videowall-still-info-content",L:c,J:[{C:"span",G:"ytp-videowall-still-info-title",U:"{{title}}"},{C:"span",G:"ytp-videowall-still-info-author",
U:"{{author_and_views}}"},{C:"span",G:"ytp-videowall-still-info-live",U:"Live"},{C:"span",G:"ytp-videowall-still-info-duration",U:"{{duration}}"}]}]}]},{C:"span",W:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],J:[{C:"span",G:"ytp-videowall-still-listlabel-icon"},"Playlist",{C:"span",G:"ytp-videowall-still-listlabel-length",J:[" (",{C:"span",U:"{{playlist_length}}"},")"]}]},{C:"span",W:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],J:[{C:"span",G:"ytp-videowall-still-listlabel-mix-icon"},
"Mix",{C:"span",G:"ytp-videowall-still-listlabel-length",U:" (50+)"}]}]});this.A=d;this.l=a;this.o=null;this.u=new g.Jr(this);g.H(this,this.u);this.da("click",this.D);this.da("keypress",this.F);this.u.K(a,"videodatachange",this.B);g.V(a).F&&g.sN(a.app.O,this.element,this);this.B()},P2=function(a){g.IJ(a.l,a.element);
var b=a.o.oa().videoId,c=a.o.getPlaylistId();g.rX(a.l.app,b,a.o.Yc,c,void 0,void 0,void 0)},Q2=function(a){H2.call(this,a,"videowall-endscreen");
this.H=a;this.B=0;this.o=[];this.D=this.u=this.A=null;this.F=this.R=!1;this.O=null;this.ca=new g.Jr(this);g.H(this,this.ca);this.I=new g.M(g.Ra(g.J,this.element,"ytp-show-tiles"),0);g.H(this,this.I);var b=new g.T({C:"button",W:["ytp-button","ytp-endscreen-previous"],L:{"aria-label":"Previous"},J:[g.IO()]});g.H(this,b);b.g(this.element);b.da("click",this.aF,this);this.N=new g.EB({C:"div",G:"ytp-endscreen-content"});g.H(this,this.N);this.N.g(this.element);b=new g.T({C:"button",W:["ytp-button","ytp-endscreen-next"],
L:{"aria-label":"Next"},J:[g.JO()]});g.H(this,b);b.g(this.element);b.da("click",this.ZE,this);this.l=new I2(a);g.H(this,this.l);g.FJ(this.player,this.l.element,4);this.hide()},R2=function(a){return g.GJ(a.player)&&a.cu()&&!a.D},S2=function(a,b){return(0,g.F)(b.suggestions,function(c){c=g.kR(g.V(a.H),c);
g.H(a,c);return c})},T2=function(a){var b=a.Ge();
b!=a.R&&(a.R=b,a.player.M("autonavvisibility"))},V2=function(a){g.TJ.call(this,a);
this.g=null;this.i=new g.Jr(this);g.H(this,this.i);this.l=g.V(a);U2(a)?this.g=new Q2(this.player):this.l.Fa?this.g=new N2(this.player):this.g=new H2(this.player);g.H(this,this.g);g.FJ(this.player,this.g.element,4);this.rz();this.i.K(a,"videodatachange",this.rz,this);this.i.K(a,g.pD("endscreen"),this.qE,this);this.i.K(a,"crx_endscreen",this.rE,this)},U2=function(a){a=g.V(a);
return a.Ca&&!a.Fa};
g.t(H2,g.JB);H2.prototype.create=function(){this.created=!0};
H2.prototype.destroy=function(){this.created=!1};
H2.prototype.cu=function(){return!1};
H2.prototype.Ge=function(){return!1};g.t(I2,g.T);g.h=I2.prototype;g.h.xl=function(){this.B&&(this.F.stop(),this.Na(this.D),this.D=null,this.B.close(),this.B=null)};
g.h.Xx=function(){g.IB(this,this.l.Ge())};
g.h.iJ=function(){window.focus();this.xl()};
g.h.hide=function(){g.T.prototype.hide.call(this)};
g.h.wo=function(a){a=a||g.R(g.V(this.l).experiments,"autoplay_time")||1E4;var b=Math.min(g.P()-this.H,a);a=Math.min(b/a,1);this.I.setAttribute("stroke-dashoffset",-211*(a+1));1<=a&&3!=this.l.getPresentingPlayerType()?M2(this,!0):this.o&&this.o.start()};
g.h.qJ=function(a){!g.be(this.A.element,g.yr(a))&&g.nR(a,this.l)&&M2(this)};
g.h.zH=function(){g.mJ(this.l,!0)};
g.h.CI=function(a){this.l.getPresentingPlayerType();this.show();J2(this,a)};
g.h.uA=function(a){this.l.getPresentingPlayerType();this.u&&this.u.oa().videoId==a.oa().videoId||(this.u=a,G2(this,a,"hqdefault.jpg"))};
g.h.DI=function(){this.l.getPresentingPlayerType();K2(this);this.hide()};
g.h.T=function(){K2(this);this.xl();g.T.prototype.T.call(this)};g.t(N2,H2);g.t(O2,g.T);O2.prototype.D=function(a){g.nR(a,this.l,this.A,this.o.Yc||void 0)&&P2(this)};
O2.prototype.F=function(a){switch(a.keyCode){case 13:case 32:g.Dr(a)||(P2(this),g.Cr(a))}};
O2.prototype.B=function(){var a=this.l.getVideoData(),b=g.V(this.l);this.A=a.ac?!1:b.i};g.t(Q2,H2);g.h=Q2.prototype;g.h.create=function(){H2.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.A=S2(this,a),this.u=a);this.Af();this.ca.K(this.player,"appresize",this.Af);this.ca.K(this.player,"onVideoAreaChange",this.Af);this.ca.K(this.player,"videodatachange",this.bF);this.ca.K(this.player,"autonavchange",this.Iq);this.ca.K(this.player,"autonavcancel",this.YE);a=this.u.autonavState;a!=this.O&&this.Iq(a);this.ca.K(this.element,"transitionend",this.GK)};
g.h.destroy=function(){g.Lr(this.ca);g.rf(this.o);this.o=[];this.A=null;H2.prototype.destroy.call(this);g.Wn(this.element,"ytp-show-tiles");this.I.stop();this.O=this.u.autonavState};
g.h.cu=function(){return 1!=this.u.autonavState};
g.h.show=function(){H2.prototype.show.call(this);g.Wn(this.element,"ytp-show-tiles");g.V(this.player).g?g.go(this.I):this.I.start();(this.F||this.D&&this.D!=this.u.clientPlaybackNonce)&&g.mJ(this.player,!1);R2(this)?(T2(this),2==this.u.autonavState?g.Q(g.V(this.player).experiments,"fast_autonav_in_background")&&3==this.player.getVisibilityState()?M2(this.l,!0):J2(this.l):3==this.u.autonavState&&L2(this.l)):(g.mJ(this.player,!0),T2(this))};
g.h.hide=function(){H2.prototype.hide.call(this);L2(this.l);T2(this)};
g.h.GK=function(a){g.yr(a)==this.element&&this.Af()};
g.h.Af=function(){if(this.A&&this.A.length){g.J(this.element,"ytp-endscreen-paginate");var a=g.wJ(this.H,!0),b=g.YB(this.H);b&&(b=b.Bc()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),k=Math.max(a.height/54,2),l=this.A.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<k);){var p=b/2,r=e/2,u=b<=f-2&&n>=r*m,y=e<=k-2&&n>=p*m;if((p+1)/r*d/c>c/(p/(r+1)*d)&&y)n-=p*m,e+=2;else if(u)n-=r*m,b+=2;else if(y)n-=p*m,e+=2;else break}d=
!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m*=c;n*=c;m*=g.qd(a.width/m||1,1,1.21);n*=g.qd(a.height/n||1,1,1.21);m=Math.floor(Math.min(a.width,m));n=Math.floor(Math.min(a.height,n));a=this.N.element;g.Nh(a,m,n);g.vh(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});c=this.l;f=this.A[0];c.u=f;G2(c,f,"hqdefault.jpg");g.L(this.element,"ytp-endscreen-takeover",R2(this));T2(this);m+=4;n+=4;for(f=c=0;f<b;f++)for(k=0;k<e;k++)if(p=c,r=0,d&&f>=b-2&&k>=e-
2?r=1:0==k%2&&0==f%2&&(2>k&&2>f?0==k&&0==f&&(r=2):r=2),p=g.rd(p+this.B,l),0!=r){u=this.o[c];u||(u=new O2(this.player),this.o[c]=u,a.appendChild(u.element));y=Math.floor(n*k/e);var D=Math.floor(m*f/b),E=Math.floor(n*(k+r)/e)-y-4,K=Math.floor(m*(f+r)/b)-D-4;g.Dh(u.element,D,y);g.Nh(u.element,K,E);g.vh(u.element,"transitionDelay",(k+f)/20+"s");g.L(u.element,"ytp-videowall-still-mini",1==r);g.L(u.element,"ytp-videowall-still-large",2<r);r=u;p=this.A[p];r.o!=p&&(r.o=p,G2(r,p,g.Un(r.element,"ytp-videowall-still-large")?
"hqdefault.jpg":"mqdefault.jpg"),p=(p=p.Yc)&&p.itct)&&(u=r.l,g.V(u).F&&g.tN(u.app.O,r.element,p));c++}g.L(this.element,"ytp-endscreen-paginate",c<l);for(b=this.o.length-1;b>=c;b--)e=this.o[b],g.Xd(e.element),g.qf(e);this.o.length=c}};
g.h.bF=function(){var a=this.player.getVideoData();this.u!=a&&(this.B=0,this.A=S2(this,a),this.u=a,this.Af())};
g.h.ZE=function(){this.B+=this.o.length;this.Af()};
g.h.aF=function(){this.B-=this.o.length;this.Af()};
g.h.DD=function(){return!!this.l.o};
g.h.Iq=function(a){1==a?(this.F=!1,this.D=this.u.clientPlaybackNonce,K2(this.l),this.Ea()&&this.Af()):(this.F=!0,this.Ea()&&R2(this)&&(2==a?J2(this.l):3==a&&L2(this.l)))};
g.h.YE=function(a){if(a){for(a=0;a<this.o.length;a++)g.JJ(this.H,this.o[a].element,!0);this.Iq(1)}else this.D=null,this.F=!1;this.Af()};
g.h.Ge=function(){return this.Ea()&&R2(this)};g.t(V2,g.TJ);g.h=V2.prototype;g.h.yk=function(){var a=this.player.getVideoData(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!U2(this.player)||b;a=a.Mc;var c=g.SW(this.player.app);return b&&!a&&!c};
g.h.Ge=function(){return this.g.Ge()};
g.h.zD=function(){return this.Ge()?this.g.DD():!1};
g.h.T=function(){g.BJ(this.player,"endscreen");g.TJ.prototype.T.call(this)};
g.h.load=function(){g.TJ.prototype.load.call(this);this.g.show()};
g.h.unload=function(){g.TJ.prototype.unload.call(this);this.g.hide();this.g.destroy()};
g.h.qE=function(a){this.yk()&&(this.g.created||this.g.create(),"load"==a.getId()&&this.load())};
g.h.rE=function(a){"load"==a.getId()&&this.loaded&&this.unload()};
g.h.rz=function(){g.BJ(this.player,"endscreen");var a=Math.max(1E3*(this.player.getVideoData().lengthSeconds-10),0);a=new g.mD(a,0x8000000000000,{id:"preload",namespace:"endscreen"});g.H(this,a);var b=new g.mD(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});g.H(this,b);g.yJ(this.player,[a,b])};g.pU.endscreen=V2;})(_yt_player);
