(function(g){var window=this;var Z3=function(a){g.JB.call(this,{C:"div",G:"ytp-miniplayer-ui"});this.player=a;this.H=!1;this.F=this.A=this.l=void 0;this.K(a,"minimized",this.QI);this.K(a,"onStateChange",this.NL)},$3=function(a){g.TJ.call(this,a);
this.g=new Z3(this.player);this.g.hide();g.FJ(this.player,this.g.element,4);a.app.F.g&&(this.load(),g.L(a.getRootNode(),"ytp-player-minimized",!0))};
g.t(Z3,g.JB);g.h=Z3.prototype;
g.h.show=function(){this.l=new g.bo(this.iF,null,this);this.l.start();if(!this.H){this.D=new g.pV(this.player,this);g.H(this,this.D);g.FJ(this.player,this.D.element,4);this.D.A=.6;this.O=new g.tU(this.player);g.H(this,this.O);this.B=new g.T({C:"div",G:"ytp-miniplayer-scrim"});g.H(this,this.B);this.B.g(this.element);this.K(this.B.element,"click",this.Cy);var a=new g.T({C:"button",W:["ytp-miniplayer-close-button","ytp-button"],L:{"aria-label":"Close"},J:[g.NO()]});g.H(this,a);a.g(this.B.element);this.K(a.element,
"click",this.Yw);this.u=new g.T({C:"div",G:"ytp-miniplayer-controls"});g.H(this,this.u);this.u.g(this.B.element);this.K(this.u.element,"click",this.Cy);var b=new g.T({C:"div",G:"ytp-miniplayer-button-container"});g.H(this,b);b.g(this.u.element);a=new g.T({C:"div",G:"ytp-miniplayer-play-button-container"});g.H(this,a);a.g(this.u.element);var c=new g.T({C:"div",G:"ytp-miniplayer-button-container"});g.H(this,c);c.g(this.u.element);this.N=new g.vS(this.player,this,!1);g.H(this,this.N);this.N.g(b.element);
b=new g.sS(this.player,this);g.H(this,b);b.g(a.element);this.I=new g.vS(this.player,this,!0);g.H(this,this.I);this.I.g(c.element);this.F=new g.NT(this.player,this);g.H(this,this.F);this.F.g(this.B.element);this.A=new g.BS(this.player,this);g.H(this,this.A);g.FJ(this.player,this.A.element,4);this.o=new g.T({C:"div",G:"ytp-miniplayer-buttons"});g.H(this,this.o);g.FJ(this.player,this.o.element,4);this.o.hide();a=new g.T({C:"button",W:["ytp-miniplayer-close-button","ytp-button"],L:{"aria-label":"Close"},
J:[g.NO()]});g.H(this,a);a.g(this.o.element);this.K(a.element,"click",this.Yw);a=new g.T({C:"button",W:["ytp-miniplayer-replay-button","ytp-button"],L:{"aria-label":"Close"},J:[g.$O()]});g.H(this,a);a.g(this.o.element);this.K(a.element,"click",this.QJ);this.K(this.player,"presentingplayerstatechange",this.jF);this.K(this.player,"appresize",this.ob);this.K(this.player,"fullscreentoggled",this.ob);this.ob();this.H=!0}0!=this.player.getPlayerState()&&g.JB.prototype.show.call(this);this.A.show();this.player.unloadModule("annotations_module")};
g.h.hide=function(){this.l&&(this.l.dispose(),this.l=void 0);g.JB.prototype.hide.call(this);this.player.app.F.g||(this.H&&this.A.hide(),this.player.loadModule("annotations_module"))};
g.h.T=function(){this.l&&(this.l.dispose(),this.l=void 0);g.JB.prototype.T.call(this)};
g.h.Yw=function(){this.player.stopVideo();this.player.ma("onCloseMiniplayer")};
g.h.QJ=function(){this.player.playVideo()};
g.h.Cy=function(a){if(a.target==this.B.element||a.target==this.u.element)g.Q(g.V(this.player).experiments,"kevlar_miniplayer_scrim_pause")?2==this.player.getPlayerState()?this.player.playVideo():this.player.pauseVideo():this.player.ma("onExpandMiniplayer")};
g.h.QI=function(){g.L(this.player.getRootNode(),"ytp-player-minimized",this.player.app.F.g);this.player.app.F.g&&0==this.player.getPlayerState()?this.o.show():this.o.hide()};
g.h.iF=function(){this.A.pd();this.F.pd();this.l&&this.l.start()};
g.h.jF=function(a){g.U(a.state,32)&&this.D.hide()};
g.h.ob=function(){var a=this.A,b=g.pJ(this.player).getPlayerSize().width;a.Oa=0;a.A=b;a.D=!1;g.DS(a)};
g.h.NL=function(a){this.player.app.F.g&&(0==a?(this.hide(),this.o.show()):(this.show(),this.o.hide()))};
g.h.fb=function(){return this.D};
g.h.Bc=function(){return!1};
g.h.jg=function(){return!1};
g.h.Vh=function(){return!1};
g.h.Jz=function(){};
g.h.cj=function(){};
g.h.Dl=function(){};
g.h.Gm=function(){return null};
g.h.Kq=function(){return new g.jh(0,0,0,0)};
g.h.handleGlobalKeyDown=function(){return!1};
g.h.handleGlobalKeyUp=function(){return!1};
g.h.cn=function(a,b,c,d,e){a.style.left="";a.style.top="";a.style.bottom="";d=g.Oh(a);var f=g.pJ(this.player).getPlayerSize().width;b&&["ytp-prev-button","ytp-next-button"].some(function(k){return g.Un(b,k)})?(c=12,a.style.top=12+(e||0)+"px"):(c-=d.width/2,a.style.bottom=25+(e||0)+"px");
a.style.left=g.qd(c,0,f-d.width)+"px"};
g.h.showControls=function(){};
g.h.Lq=function(){};
g.h.Gh=function(){};g.t($3,g.TJ);$3.prototype.init=function(){};
$3.prototype.load=function(){this.player.hideControls();this.g.show()};
$3.prototype.unload=function(){this.player.showControls();this.g.hide()};g.pU.miniplayer=$3;})(_yt_player);
