(function(g){var window=this;var mpa=function(a,b){return g.Ub(a,b)},a4=function(){},npa=function(a){if(a.zc&&"function"==typeof a.zc)return a.zc();
if(g.v(a))return a.split("");if(g.Ma(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Qb(a)},opa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.Ma(a)||g.v(a))(0,g.B)(a,b,void 0);else{if(a.Fd&&"function"==typeof a.Fd)var c=a.Fd();else if(a.zc&&"function"==typeof a.zc)c=void 0;else if(g.Ma(a)||g.v(a)){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Rb(a);d=npa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},b4=function(a){g.Wm(a,"zx",g.rc());
return a},c4=function(a,b,c){g.La(c)||(c=[String(c)]);
g.an(a.l,b,c)},d4=function(a){return(a=g.so(a))?new ActiveXObject(a):new XMLHttpRequest},e4=function(a,b){return b+" ["+a.aa+" "+a.F+" "+a.getStatus()+"]"},ppa=function(a){return"content-type"==a.toLowerCase()},f4=function(a){a.g&&a.I&&(a.g.ontimeout=null);
a.B&&(g.w.clearTimeout(a.B),a.B=null)},qpa=function(a){return g.Md&&g.Cc(9)&&g.Da(a.timeout)&&g.Ba(a.ontimeout)},g4=function(a){a.O||(a.O=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},h4=function(a,b){if(a.g){f4(a);
var c=a.g,d=a.P[0]?g.Ga:null;a.g=null;a.P=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},i4=function(a,b){a.i=!1;
a.g&&(a.o=!0,a.g.abort(),a.o=!1);a.l=b;a.u=5;g4(a);h4(a)},j4=function(a){return a.g?a.g.readyState:0},k4=function(a){if(a.i&&"undefined"!=typeof g.HX)if(a.P[1]&&4==j4(a)&&2==a.getStatus())e4(a,"Local request error detected and ignored");
else if(a.D&&4==j4(a))g.Dg(a.Iv,0,a);else if(a.dispatchEvent("readystatechange"),4==j4(a)){e4(a,"Request complete");a.i=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.Ng(String(a.F))[1]||null;if(!f&&g.w.self&&g.w.self.location){var k=g.w.self.location.protocol;f=k.substr(0,k.length-1)}e=!rpa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.u=6;try{var l=2<j4(a)?a.g.statusText:""}catch(m){l=""}a.l=l+" ["+a.getStatus()+"]";g4(a)}}finally{h4(a)}}},l4=function(a){g.Qf.call(this);
this.headers=new g.Lm;this.N=a||null;this.i=!1;this.P=this.g=null;this.aa=this.F="";this.u=0;this.l="";this.o=this.V=this.D=this.O=!1;this.A=0;this.B=null;this.Y="";this.I=this.R=!1},m4=function(a){try{return a.g?a.g.responseText:""}catch(b){return""}},spa=function(a,b){var c=[];
g.Lk(b,function(d){try{var e=g.Ho.prototype.i.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.Ba(e)?g.Go(e)&&c.push(d):c.push(d)},a);
return c},tpa=function(a,b){var c=spa(a,b);
(0,g.B)(c,function(d){g.Ho.prototype.remove.call(this,d)},a)},n4=function(a){if(a.Zc){if(a.Zc.locationOverrideToken)return{locationOverrideToken:a.Zc.locationOverrideToken};
if(null!=a.Zc.latitudeE7&&null!=a.Zc.longitudeE7)return{latitudeE7:a.Zc.latitudeE7,longitudeE7:a.Zc.longitudeE7}}return null},upa=function(a,b){g.$a(a,b)||a.push(b)},o4=function(a){var b=0,c;
for(c in a)b++;return b},vpa=function(a){return/^\s*$/.test(a)?!1:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,""))},wpa=function(a){try{return g.w.JSON.parse(a)}catch(d){var b=d}a=String(a);
if(vpa(a))try{var c=eval("("+a+")");b&&(0,g.HW)("Invalid JSON: "+a,b);return c}catch(d){}throw Error("Invalid JSON string: "+a);},xpa=function(a,b,c,d){var e=new g.Om(null,void 0);
a&&g.Pm(e,a);b&&g.Qm(e,b);c&&g.Rm(e,c);d&&(e.i=d);return e},p4=function(a){if(g.w.JSON)try{return g.w.JSON.parse(a)}catch(b){}return wpa(a)},q4=function(){this.g=[];
this.i=[]},r4=function(a,b){g.Mp[a]=!0;
var c=g.Kp();c&&c.publish.apply(c,arguments);g.Mp[a]=!1},s4=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.l=!1;this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Lm;this.g=this.i="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",ypa(this,a.capabilities||""),zpa(this,a.experiments||""),this.i=a.remoteControllerUrl||"",this.g=a.localChannelEncryptionKey||
"")},ypa=function(a,b){a.capabilities.clear();
(0,g.Yd)(b.split(","),g.Ra(mpa,Apa)).forEach(function(c){a.capabilities.add(c)})},zpa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},t4=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},u4=function(a,b){return!!b&&(a.id==b||a.uuid==b)},v4=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},Bpa=function(a){return new t4(a)},w4=function(a){return g.La(a)?(0,g.F)(a,Bpa):[]},x4=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},y4=function(a){return g.La(a)?"["+(0,g.F)(a,x4).join(",")+"]":"null"},z4=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},Cpa=function(a){return(0,g.F)(a,function(b){return{key:b.id,
name:b.name}})},A4=function(a,b){return g.Xa(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},B4=function(a,b){return g.Xa(a,function(c){return u4(c,b)})},Dpa=function(){var a=(0,g.Xs)();
a&&tpa(a,a.g.Ze(!0))},C4=function(){var a=g.$s("yt-remote-connected-devices")||[];
g.qb(a);return a},Epa=function(a){if(0==a.length)return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.F)(a,function(d,e){return 0==e?d:d.substring(c.length)})},D4=function(a){g.Zs("yt-remote-connected-devices",a,86400)},F4=function(){if(E4)return E4;
var a=g.$s("yt-remote-device-id");a||(a=z4(),g.Zs("yt-remote-device-id",a,31536E3));for(var b=C4(),c=1,d=a;g.$a(b,d);)c++,d=a+"#"+c;return E4=d},G4=function(){var a=C4(),b=F4();
g.$a(a,b);g.bt()&&g.sb(a,b);a=Epa(a);if(0==a.length)try{g.ys("remote_sid")}catch(c){}else try{g.xs("remote_sid",a.join(","),-1)}catch(c){}},H4=function(){return g.$s("yt-remote-session-browser-channel")},I4=function(){return g.$s("yt-remote-local-screens")||[]},J4=function(){g.Zs("yt-remote-lounge-token-expiration",!0,86400)},Fpa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.F)(I4(),function(d){return d.loungeToken}),c=(0,g.F)(a,function(d){return d.loungeToken});
(0,g.Ni)(c,function(d){return!g.$a(b,d)})&&J4();
g.Zs("yt-remote-local-screens",a,31536E3)},Gpa=function(a,b){g.Zs("yt-remote-session-browser-channel",a);
g.Zs("yt-remote-session-screen-id",b);var c=C4(),d=F4();g.$a(c,d)||c.push(d);D4(c);G4()},K4=function(a){a||(g.at("yt-remote-session-screen-id"),g.at("yt-remote-session-video-id"));
G4();a=C4();g.cb(a,F4());D4(a)},M4=function(){if(!L4){var a=g.Ro();
a&&(L4=new g.Bo(a))}return L4?!!L4.get("yt-remote-use-staging-server"):!1},N4=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},O4=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},Q4=function(a){a.length?P4(a.shift(),function(){Q4(a)}):R4()},Hpa=function(a){return"chrome-extension://"+a+S4},P4=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},R4=function(){var a=O4();
a&&a(!1,"No cast extension found")},T4=function(){if(Ipa){var a=2,b=O4(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;P4("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",R4,c)}},Jpa=function(){T4();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);Q4(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+S4,"//www.gstatic.com/eureka/clank"+S4])},U4=function(a,b,c){g.G.call(this);
this.A=null!=c?(0,g.z)(a,c):a;this.Vc=b;this.u=(0,g.z)(this.IC,this);this.g=!1;this.i=0;this.l=this.za=null;this.o=[]},V4=function(){},W4=function(a,b,c,d){this.g=a;
this.l=b;this.B=c;this.A=d||1;this.o=45E3;this.ca=new g.bn(this);this.i=new g.Cg;this.i.setInterval(250)},Y4=function(a,b,c){a.Mh=1;
a.Zf=b4(b.clone());a.ih=c;a.u=!0;X4(a,null)},Z4=function(a,b,c,d,e){a.Mh=1;
a.Zf=b4(b.clone());a.ih=null;a.u=c;e&&(a.xz=!1);X4(a,d)},X4=function(a,b){a.pi=(0,g.C)();
$4(a);a.sg=a.Zf.clone();c4(a.sg,"t",a.A);a.Jk=0;a.tc=a.g.Vo(a.g.Ak()?b:null);0<a.Dp&&(a.ln=new g.xl((0,g.z)(a.GA,a,a.tc),a.Dp));a.ca.da(a.tc,"readystatechange",a.pL);var c=a.Ng?g.bc(a.Ng):{};a.ih?(a.Wn="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.tc.send(a.sg,a.Wn,a.ih,c)):(a.Wn="GET",a.xz&&!g.Od&&(c.Connection="close"),a.tc.send(a.sg,a.Wn,null,c));a.g.me(1)},g5=function(a,b,c){for(var d=!0;!a.Dg&&a.Jk<c.length;){var e=Kpa(a,c);
if(e==a5){4==b&&(a.ag=4,b5(15),d=!1);break}else if(e==c5){a.ag=4;b5(16);d=!1;break}else d5(a,e)}4==b&&0==c.length&&(a.ag=1,b5(17),d=!1);a.re=a.re&&d;d||(e5(a),f5(a))},Kpa=function(a,b){var c=a.Jk,d=b.indexOf("\n",c);
if(-1==d)return a5;c=Number(b.substring(c,d));if(isNaN(c))return c5;d+=1;if(d+c>b.length)return a5;var e=b.substr(d,c);a.Jk=d+c;return e},j5=function(a,b){a.pi=(0,g.C)();
$4(a);var c=b?window.location.hostname:"";a.sg=a.Zf.clone();g.Wm(a.sg,"DOMAIN",c);g.Wm(a.sg,"t",a.A);try{a.te=new ActiveXObject("htmlfile")}catch(n){e5(a);a.ag=7;b5(22);f5(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in h5)k=h5[l];else if(l in i5)k=h5[l]=i5[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
h5[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.ld(g.Kc("b/12014412"),d+"</body></html>");a.te.open();a.te.write(g.gd(c));a.te.close();a.te.parentWindow.m=(0,g.z)(a.JK,a);a.te.parentWindow.d=(0,g.z)(a.Hy,a,!0);a.te.parentWindow.rpcClose=(0,g.z)(a.Hy,a,!1);c=a.te.createElement("DIV");a.te.parentWindow.document.body.appendChild(c);d=g.Wc(a.sg.toString());d=g.nc(g.Tc(d));d=g.ld(g.Kc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.md(c,d);a.g.me(1)},$4=function(a){a.Ks=(0,g.C)()+a.o;
k5(a,a.o)},k5=function(a,b){if(null!=a.Gi)throw Error("WatchDog timer not null");
a.Gi=l5((0,g.z)(a.TK,a),b)},m5=function(a){a.Gi&&(g.w.clearTimeout(a.Gi),a.Gi=null)},f5=function(a){a.g.Gv()||a.Dg||a.g.Um(a)},e5=function(a){m5(a);
g.qf(a.ln);a.ln=null;a.i.stop();g.dn(a.ca);if(a.tc){var b=a.tc;a.tc=null;b.abort();b.dispose()}a.te&&(a.te=null)},d5=function(a,b){try{a.g.By(a,b),a.g.me(4)}catch(c){}},o5=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;n5(a,b,function(k){k?c(!0):g.w.setTimeout(function(){o5(a,b,c,d,f)},f)})}},n5=function(a,b,c){var d=new Image;
d.onload=function(){try{p5(d),c(!0)}catch(e){}};
d.onerror=function(){try{p5(d),c(!1)}catch(e){}};
d.onabort=function(){try{p5(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{p5(d),c(!1)}catch(e){}};
g.w.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},p5=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},q5=function(a){this.g=a;
this.i=new V4},s5=function(a){var b=r5(a.g,a.Si,"/mail/images/cleardot.gif");
b4(b);o5(b.toString(),5E3,(0,g.z)(a.TB,a),3,2E3);a.me(1)},u5=function(a){var b=a.g.F;
if(null!=b)b5(5),b?(b5(11),t5(a.g,a,!1)):(b5(12),t5(a.g,a,!0));else if(a.Bd=new W4(a,void 0,void 0,void 0),a.Bd.Ng=a.Bp,b=a.g,b=r5(b,b.Ak()?a.yj:null,a.Cp),b5(5),!g.Md||g.Dc(10))c4(b,"TYPE","xmlhttp"),Z4(a.Bd,b,!1,a.yj,!1);else{c4(b,"TYPE","html");var c=a.Bd;a=!!a.yj;c.Mh=3;c.Zf=b4(b.clone());j5(c,a)}},v5=function(a,b,c){this.g=1;
this.i=[];this.o=[];this.u=new V4;this.D=a||null;this.F=null!=b?b:null;this.A=c||!1},Lpa=function(a,b){this.g=a;
this.map=b;this.context=null},w5=function(a){g.sf.call(this,"statevent",a)},x5=function(a,b){g.sf.call(this,"timingevent",a);
this.size=b},y5=function(a){g.sf.call(this,"serverreachability",a)},C5=function(a){z5(a);
if(3==a.g){var b=a.fk++,c=a.Il.clone();g.Wm(c,"SID",a.l);g.Wm(c,"RID",b);g.Wm(c,"TYPE","terminate");A5(a,c);b=new W4(a,a.l,b,void 0);b.Mh=2;b.Zf=b4(c.clone());(new Image).src=b.Zf;b.pi=(0,g.C)();$4(b)}B5(a)},E5=function(a){a.kC(1,0);
a.Il=r5(a,null,a.Ap);D5(a)},z5=function(a){a.Rf&&(a.Rf.abort(),a.Rf=null);
a.Sb&&(a.Sb.cancel(),a.Sb=null);a.cf&&(g.w.clearTimeout(a.cf),a.cf=null);F5(a);a.yd&&(a.yd.cancel(),a.yd=null);a.Wf&&(g.w.clearTimeout(a.Wf),a.Wf=null)},G5=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.i.push(new Lpa(a.TG++,b));2!=a.g&&3!=a.g||D5(a)},D5=function(a){a.yd||a.Wf||(a.Wf=l5((0,g.z)(a.Gy,a),0),a.Hh=0)},J5=function(a,b){if(1==a.g){if(!b){a.fk=Math.floor(1E5*Math.random());
var c=a.fk++,d=new W4(a,"",c,void 0);d.Ng=null;var e=H5(a),f=a.Il.clone();g.Wm(f,"RID",c);g.Wm(f,"CVER","1");A5(a,f);Y4(d,f,e);a.yd=d;a.g=2}}else 3==a.g&&(b?I5(a,b):0==a.i.length||a.yd||I5(a))},I5=function(a,b){if(b)if(6<a.Eg){a.i=a.o.concat(a.i);
a.o.length=0;var c=a.fk-1;var d=H5(a)}else c=b.B,d=b.ih;else c=a.fk++,d=H5(a);var e=a.Il.clone();g.Wm(e,"SID",a.l);g.Wm(e,"RID",c);g.Wm(e,"AID",a.Xh);A5(a,e);c=new W4(a,a.l,c,a.Hh+1);c.Ng=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.yd=c;Y4(c,e,d)},A5=function(a,b){if(a.Tc){var c=a.Tc.gv();
c&&g.Kb(c,function(d,e){g.Wm(b,e,d)})}},H5=function(a){var b=Math.min(a.i.length,1E3),c=["count="+b];
if(6<a.Eg&&0<b){var d=a.i[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.i[e].g,k=a.i[e].map;f=6>=a.Eg?e:f-d;try{g.Kb(k,function(l,m){c.push("req"+f+"_"+m+"="+encodeURIComponent(l))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.o=a.o.concat(a.i.splice(0,b));
return c.join("&")},K5=function(a){a.Sb||a.cf||(a.B=1,a.cf=l5((0,g.z)(a.Fy,a),0),a.Bh=0)},M5=function(a){if(a.Sb||a.cf||3<=a.Bh)return!1;
a.B++;a.cf=l5((0,g.z)(a.Fy,a),L5(a,a.Bh));a.Bh++;return!0},t5=function(a,b,c){a.Un=c;
a.Ce=b.rf;a.A||E5(a)},F5=function(a){null!=a.Ig&&(g.w.clearTimeout(a.Ig),a.Ig=null)},L5=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},O5=function(a,b){if(2==b||9==b){var c=null;
a.Tc&&(c=null);var d=(0,g.z)(a.SL,a);c||(c=new g.Om("//www.google.com/images/cleardot.gif"),b4(c));n5(c.toString(),1E4,d)}else b5(2);N5(a,b)},N5=function(a,b){a.g=0;
a.Tc&&a.Tc.lu(b);B5(a);z5(a)},B5=function(a){a.g=0;
a.Ce=-1;if(a.Tc)if(0==a.o.length&&0==a.i.length)a.Tc.Lo();else{g.gb(a.o);var b=g.gb(a.i);a.o.length=0;a.i.length=0;a.Tc.Lo(b)}},r5=function(a,b,c){var d=g.Xm(c);
if(""!=d.g)b&&g.Qm(d,b+"."+d.g),g.Rm(d,d.u);else{var e=window.location;d=xpa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.fj&&g.Kb(a.fj,function(f,k){g.Wm(d,k,f)});
g.Wm(d,"VER",a.Eg);A5(a,d);return d},l5=function(a,b){if(!g.Na(a))throw Error("Fn must not be null and must be a function");
return g.w.setTimeout(function(){a()},b)},b5=function(a){P5.dispatchEvent(new w5(P5,a))},Q5=function(){},Mpa=function(a,b){this.action=a;
this.params=b||{}},R5=function(a,b){g.G.call(this);
this.g=new g.M(this.BK,0,this);g.H(this,this.g);this.Vc=5E3;this.i=0;if(g.Na(a))b&&(a=(0,g.z)(a,b));else if(a&&g.Na(a.handleEvent))a=(0,g.z)(a.handleEvent,a);else throw Error("Invalid listener argument");this.l=a},S5=function(a,b,c){this.H=a;
this.A=b;this.l=new g.Ao;this.i=new R5(this.nM,this);this.g=null;this.Za=!1;this.u=null;this.F="";this.D=this.o=0;this.B=[];this.I=c||!1},Npa=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.Un,sessionId:a.g.l,arrayId:a.g.Xh}},T5=function(a,b){a.D=b||0;
a.i.stop();a.g&&(3==a.g.g&&J5(a.g),C5(a.g));a.D=0},U5=function(a){return!!a.g&&3==a.g.g},Opa=function(a,b){(a.A.loungeIdToken=b)||a.i.stop()},V5=function(a){this.port=this.domain="";
this.g="/api/lounge";this.i=!0;a=a||document.location.href;var b=g.Qg(a)||"";b&&(this.port=":"+b);this.domain=g.Pg(a)||"";a=g.Ib;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Hb(a,"10.0")&&(this.i=!1))},W5=function(a,b){var c=a.g;
if(g.Ba(void 0)?0:a.i)c="https://"+a.domain+a.port+a.g;return g.Zg(c+b,{})},X5=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Ra(a.o,d,!0),onError:g.Ra(a.l,e),nd:g.Ra(a.u,e)};c&&(a.qb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.wq(b,a)},Ppa=function(){var a=Y5;
Z5();$5.push(a);a6($5)},b6=function(a,b){Z5();
var c=$5,d=Qpa(a,String(b));0==c.length?Rpa(d):(a6(c),(0,g.B)(c,function(e){e(d)}))},Z5=function(){$5||($5=g.x("yt.mdx.remote.debug.handlers_")||[],g.Ea("yt.mdx.remote.debug.handlers_",$5,void 0))},Rpa=function(a){var b=(c6+1)%50;
c6=b;d6[b]=a;e6||(e6=49==b)},a6=function(a){var b=d6;
if(b[0]){var c=c6,d=e6?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.B)(a,function(f){f(e)})}while(d!=c);
d6=Array(50);c6=-1;e6=!1}},Qpa=function(a,b){var c=((0,g.C)()-Spa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},f6=function(a){g.O.call(this);
this.B=a;this.g=[]},g6=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},Tpa=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.Yd)(a.g,function(f){return!!A4(b,f)});
for(var d=0,e=b.length;d<e;d++)c=g6(a,b[d])||c;return c},Upa=function(a,b){var c=a.g.length;
a.g=(0,g.Yd)(a.g,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.g.length<c},h6=function(a,b,c,d){g.O.call(this);
this.A=a;this.u=b;this.l=c;this.o=d;this.i=0;this.g=null;this.za=NaN},j6=function(a){f6.call(this,"LocalScreenService");
this.l=a;this.i=NaN;i6(this);this.info("Initializing with "+y4(this.g))},k6=function(a){if(a.g.length){var b=(0,g.F)(a.g,function(d){return d.id}),c=W5(a.l,"/pairing/get_lounge_token_batch");
X5(a.l,c,{screen_ids:b.join(",")},(0,g.z)(a.SC,a),(0,g.z)(a.RC,a))}},i6=function(a){var b=w4(I4());
b=(0,g.Yd)(b,function(c){return!c.uuid});
return Tpa(a,b)},l6=function(a,b){Fpa((0,g.F)(a.g,v4));
b&&J4()},n6=function(a,b){g.O.call(this);
this.A=b;var c=g.$s("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.A(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.$a(c,l)}this.g=d;this.u=a;this.l=this.o=NaN;this.i=null;m6("Initialized with "+g.Hg(this.g))},o6=function(a,b,c){var d=W5(a.u,"/pairing/get_screen_availability");
X5(a.u,d,{lounge_token:b.token},(0,g.z)(function(e){e=e.screens||[];for(var f=0,k=e.length;f<k;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.z)(function(){c(!1)},a))},p6=function(a,b){a:if(o4(b)!=o4(a.g))var c=!1;
else{c=g.Rb(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(m6("Updated online screens: "+g.Hg(a.g)),a.g=b,a.M("screenChange"));Vpa(a)},q6=function(a){isNaN(a.l)||g.Jp(a.l);
a.l=g.Hp((0,g.z)(a.Lr,a),0<a.o&&a.o<(0,g.C)()?2E4:1E4)},m6=function(a){b6("OnlineScreenService",a)},r6=function(a){var b={};
(0,g.B)(a.A(),function(c){c.token?b[c.token]=c.id:this.Lb("Requesting availability of screen w/o lounge token.")});
return b},Vpa=function(a){a=g.Rb(g.Lb(a.g,function(b){return b}));
g.qb(a);a.length?g.Zs("yt-remote-online-screen-ids",a.join(","),60):g.at("yt-remote-online-screen-ids")},s6=function(a){f6.call(this,"ScreenService");
this.A=a;this.i=this.l=null;this.o=[];this.u={};Wpa(this)},u6=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.u[b]);var k=a.Gd();if(k=(c?B4(k,c):null)||B4(k,b)){k.uuid=b;var l=t6(a,k);o6(a.i,l,function(m){e(m?l:null)})}else c?Xpa(a,c,(0,g.z)(function(m){var n=t6(this,new t4({name:d,
screenId:c,loungeToken:m,dialId:b||""}));o6(this.i,n,function(p){e(p?n:null)})},a),f):e(null)},v6=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},Xpa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={qb:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,k){var l=k&&k.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.wq(W5(a.A,"/pairing/get_lounge_token_batch"),e)},w6=function(a){a.g=a.l.Gd();
var b=a.u,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+y4(a.g))},Wpa=function(a){x6(a);
a.l=new j6(a.A);a.l.subscribe("screenChange",(0,g.z)(a.bD,a));w6(a);a.o=w4(g.$s("yt-remote-automatic-screen-cache")||[]);x6(a);a.info("Initializing automatic screens: "+y4(a.o));a.i=new n6(a.A,(0,g.z)(a.Gd,a,!0));a.i.subscribe("screenChange",(0,g.z)(function(){this.M("onlineScreenChange")},a))},t6=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=B4(a.o,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.o.push(b),g.Zs("yt-remote-automatic-screen-cache",(0,g.F)(a.o,v4)));x6(a);a.u[b.uuid]=b.id;g.Zs("yt-remote-device-id-map",a.u,31536E3);return b},x6=function(a){a.u=g.$s("yt-remote-device-id-map")||{}},y6=function(a,b,c){g.O.call(this);
this.P=c;this.F=a;this.i=b;this.l=null},z6=function(a,b){b6(a.P,b)},B6=function(a,b){y6.call(this,a,b,"CastSession");
this.g=null;this.o=0;this.A=(0,g.z)(this.tM,this);this.u=(0,g.z)(this.eL,this);this.o=g.Hp((0,g.z)(function(){A6(this,null)},this),12E4)},Ypa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Hg(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Ga,(0,g.z)(function(){z6(this,"Failed to send message: getMdxSessionStatus.")},a)):z6(a,"Sending yt message without session: "+g.Hg(b))},A6=function(a,b){g.Jp(a.o);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.l||a.l.id!=b){var c=(0,g.z)(a.Vm,a),d=(0,g.z)(a.Jd,a);a.zv(b,c,d,5)}}else a.Jd(Error("Waiting for session status timed out."))},C6=function(a,b,c){y6.call(this,a,b,"DialSession");
this.o=this.D=null;this.H="";this.N=c;this.u=null;this.B=g.Ga;this.A=NaN;this.I=(0,g.z)(this.wM,this);this.g=g.Ga},D6=function(a){a.g=a.F.LA(a.H,a.i.label,a.i.friendlyName,(0,g.z)(function(b){this.g=g.Ga;
this.Vm(b)},a),(0,g.z)(function(b){this.g=g.Ga;
this.Jd(b)},a))},E6=function(a){var b={};
b.pairingCode=a.H;b.theme=a.N;if(a.u){var c=a.u.currentTime||0;b.v=a.u.videoId;b.t=c}M4()&&(b.env_useStageMdx=1);return g.Xg(b)},F6=function(a,b){y6.call(this,a,b,"ManualSession");
this.g=g.Hp((0,g.z)(this.Zh,this,null),150)},G6=function(a,b,c,d){g.O.call(this);
this.i=a;this.B=b||"233637DE";this.A=c||"cl";this.D=d||!1;this.g=null;this.u=!1;this.l=[];this.o=(0,g.z)(this.KJ,this)},H6=function(a,b){return b?g.Xa(a.l,function(c){return u4(b,c.label)},a):null},I6=function(a){b6("Controller",a)},Y5=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},J6=function(a){return a.u||!!a.l.length||!!a.g},K6=function(a,b,c){b!=a.g&&(g.qf(a.g),(a.g=b)?(c?a.M("yt-remote-cast2-receiver-resumed",b.i):a.M("yt-remote-cast2-receiver-selected",
b.i),b.subscribe("sessionScreen",(0,g.z)(a.Ey,a,b)),b.l?a.M("yt-remote-cast2-session-change",b.l):c&&a.g.Zh(null)):a.M("yt-remote-cast2-session-change",null))},L6=function(a){var b=a.i.KA(),c=a.g&&a.g.i;
a=(0,g.F)(b,function(d){c&&u4(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=H6(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},bqa=function(a,b,c,d,e,f,k){Zpa()?$pa(b,e,f,k)&&(N6(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?O6(a,c):(window.__onGCastApiAvailable=function(l,m){l?O6(a,c):(P6("Failed to load cast API: "+m),Q6(!1),N6(!1),g.at("yt-remote-cast-available"),g.at("yt-remote-cast-receiver"),R6(),c(!1))},d?g.Up("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?Jpa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?R4():(T4(),Q4(aqa.map(Hpa))))):M6("Cannot initialize because not running Chrome")},R6=function(){M6("dispose");
var a=S6();a&&a.dispose();g.Ea("yt.mdx.remote.cloudview.instance_",null,void 0);T6(!1);g.Pp(U6);U6.length=0},V6=function(){return!!g.$s("yt-remote-cast-installed")},W6=function(){var a=g.$s("yt-remote-cast-receiver");
return a?a.friendlyName:null},X6=function(){M6("clearCurrentReceiver");
g.at("yt-remote-cast-receiver")},Y6=function(){return V6()?S6()?S6().getCastSession():(P6("getCastSelector: Cast is not initialized."),null):(P6("getCastSelector: Cast API is not installed!"),null)},$6=function(){V6()?S6()?Z6()?(M6("Requesting cast selector."),S6().requestSession()):(M6("Wait for cast API to be ready to request the session."),U6.push(g.Op("yt-remote-cast2-api-ready",$6))):P6("requestCastSelector: Cast is not initialized."):P6("requestCastSelector: Cast API is not installed!")},a7=
function(a,b){Z6()?S6().setConnectedScreenStatus(a,b):P6("setConnectedScreenStatus called before ready.")},Zpa=function(){var a=0<=g.Ib.search(/ (CrMo|Chrome|CriOS)\//);
return g.Iw||a},cqa=function(a,b){S6().init(a,b)},$pa=function(a,b,c,d){var e=!1;
S6()||(a=new G6(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.Zs("yt-remote-cast-available",f);r4("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){M6("onReceiverSelected: "+f.friendlyName);
g.Zs("yt-remote-cast-receiver",f);r4("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){M6("onReceiverResumed: "+f.friendlyName);
g.Zs("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){M6("onSessionChange: "+x4(f));
f||g.at("yt-remote-cast-receiver");r4("yt-remote-cast2-session-change",f)}),g.Ea("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
M6("cloudview.createSingleton_: "+e);return e},S6=function(){return g.x("yt.mdx.remote.cloudview.instance_")},O6=function(a,b){Q6(!0);
N6(!1);cqa(a,function(c){c?(T6(!0),g.Rp("yt-remote-cast2-api-ready")):(P6("Failed to initialize cast API."),Q6(!1),g.at("yt-remote-cast-available"),g.at("yt-remote-cast-receiver"),R6());b(c)})},M6=function(a){b6("cloudview",a)},P6=function(a){b6("cloudview",a)},Q6=function(a){M6("setCastInstalled_ "+a);
g.Zs("yt-remote-cast-installed",a)},Z6=function(){return!!g.x("yt.mdx.remote.cloudview.apiReady_")},T6=function(a){M6("setApiReady_ "+a);
g.Ea("yt.mdx.remote.cloudview.apiReady_",a,void 0)},N6=function(a){g.Ea("yt.mdx.remote.cloudview.initializing_",a,void 0)},b7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.A=this.B=0;this.g=null;this.hasNext=this.Ee=!1;this.F=this.D=this.i=this.o=0;this.l=NaN;this.u=!1;this.reset(a)},c7=function(a){a.audioTrackId=null;
a.g=null;a.playerState=-1;a.Ee=!1;a.hasNext=!1;a.B=0;a.A=(0,g.C)();a.o=0;a.i=0;a.D=0;a.F=0;a.l=NaN;a.u=!1},d7=function(a){return 1==a.playerState?((0,g.C)()-a.A)/1E3:0},e7=function(a,b){a.B=b;
a.A=(0,g.C)()},f7=function(a){switch(a.playerState){case 1:case 1081:return((0,g.C)()-a.A)/1E3+a.B;
case -1E3:return 0}return a.B},g7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&c7(a)},h7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.cc(a.g);b.hasPrevious=a.Ee;b.hasNext=a.hasNext;b.playerTime=a.B;b.playerTimeAt=a.A;b.seekableStart=a.o;b.seekableEnd=a.i;b.duration=a.D;b.loadedTime=a.F;b.liveIngestionTime=a.l;return b},k7=function(a,b){g.O.call(this);
this.g=0;this.o=a;this.A=[];this.u=new q4;this.l=this.i=null;this.F=(0,g.z)(this.DH,this);this.B=(0,g.z)(this.hk,this);this.D=(0,g.z)(this.CH,this);this.H=(0,g.z)(this.PH,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Ns,this),i7(this))):c=3;0!=c&&(b?this.Ns(c):g.Hp((0,g.z)(function(){this.Ns(c)},this),0));
var d=Y6();d&&j7(this,d);this.subscribe("yt-remote-cast2-session-change",this.H)},l7=function(a){return new b7(a.o.getPlayerContextData())},i7=function(a){(0,g.B)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.A.push(this.o.subscribe(b,g.Ra(this.HJ,b),this))},a)},m7=function(a){(0,g.B)(a.A,function(b){this.o.unsubscribeByKey(b)},a);
a.A.length=0},n7=function(a,b){var c=a.u;
50>c.g.length+c.i.length&&a.u.i.push(b)},p7=function(a,b,c){var d=l7(a);
e7(d,c);-1E3!=d.playerState&&(d.playerState=b);o7(a,d)},q7=function(a,b,c){a.o.sendMessage(b,c)},o7=function(a,b){m7(a);
a.o.setPlayerContextData(h7(b));i7(a)},j7=function(a,b){a.l&&(a.l.removeUpdateListener(a.F),a.l.removeMediaListener(a.B),a.hk(null));
a.l=b;a.l&&(b6("CP","Setting cast session: "+a.l.sessionId),a.l.addUpdateListener(a.F),a.l.addMediaListener(a.B),a.l.media.length&&a.hk(a.l.media[0]))},r7=function(a){var b=a.i.media,c=a.i.customData;
if(b&&c){var d=l7(a);b.contentId!=d.videoId&&b6("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;e7(d,a.i.getEstimatedTime());o7(a,d)}else b6("CP","No cast media video. Ignoring state update.")},s7=function(a,b,c){return(0,g.z)(function(d){this.Lb("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Lb("Retrying "+b+" using MDx browser channel."),q7(this,b,c))},a)},t7=function(a,b,c){g.O.call(this);
this.u=NaN;this.N=!1;this.H=this.F=this.I=this.P=NaN;this.O=[];this.o=this.B=this.l=this.Qa=this.g=null;this.na=a;this.O.push(g.wr(window,"beforeunload",(0,g.z)(this.LC,this)));this.i=[];this.Qa=new b7;this.V=b.id;this.g=dqa(this,c);this.g.subscribe("handlerOpened",this.HH,this);this.g.subscribe("handlerClosed",this.EH,this);this.g.subscribe("handlerError",this.FH,this);this.g.subscribe("handlerMessage",this.GH,this);Opa(this.g,b.token);this.subscribe("remoteQueueChange",function(){var d=this.Qa.videoId;
g.bt()&&g.Zs("yt-remote-session-video-id",d)},this)},u7=function(a){b6("conn",a)},dqa=function(a,b){return new S5(W5(a.na,"/bc"),b)},v7=function(a,b){a.M("proxyStateChange",b)},eqa=function(a){a.u=g.Hp((0,g.z)(function(){u7("Connecting timeout");
this.A(1)},a),2E4)},w7=function(a){g.Jp(a.u);
a.u=NaN},x7=function(a){g.Jp(a.P);
a.P=NaN},fqa=function(a){y7(a);
a.I=g.Hp((0,g.z)(function(){z7(this,"getNowPlaying")},a),2E4)},y7=function(a){g.Jp(a.I);
a.I=NaN},B7=function(a,b){b&&(w7(a),x7(a));
b==(U5(a.g)&&isNaN(a.u))?b&&(v7(a,1),z7(a,"getSubtitlesTrack")):b?(a.R()&&a.Qa.reset(),v7(a,1),z7(a,"getNowPlaying"),A7(a)):a.A(1)},gqa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Qa.videoId&&(g.Xb(b.params)?a.Qa.g=null:a.Qa.g=b.params,a.M("remotePlayerChange"))},C7=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.Qa.listId=b.params.listId||a.Qa.listId;g7(a.Qa,c,d);a.M("remoteQueueChange")},hqa=function(a,b){b.params=b.params||{};
C7(a,b);D7(a,b);a.M("autoplayDismissed")},D7=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
e7(a.Qa,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.Qa.playerState&&(c=-1E3);a.Qa.playerState=c;c=Number(b.params.loadedTime);a.Qa.F=isNaN(c)?0:c;c=Number(b.params.duration);a.Qa.D=isNaN(c)?0:c;c=a.Qa;var d=Number(b.params.liveIngestionTime);c.l=d;c.u=isNaN(d)?!1:!0;c=a.Qa;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.o=isNaN(d)?0:d;c.i=isNaN(e)?0:e;1==a.Qa.playerState?fqa(a):y7(a);a.M("remotePlayerChange")},iqa=function(a,b){if(-1E3!=
a.Qa.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Qa.playerState=c;c=parseInt(b.params.currentTime,10);e7(a.Qa,isNaN(c)?0:c);a.M("remotePlayerChange")}},jqa=function(a,b){var c="true"==b.params.muted;
a.Qa.volume=parseInt(b.params.volume,10);a.Qa.muted=c;a.M("remotePlayerChange")},kqa=function(a,b){a.B=b.params.videoId;
a.M("nowAutoplaying",parseInt(b.params.timeout,10))},lqa=function(a,b){var c="true"==b.params.hasNext;
a.Qa.Ee="true"==b.params.hasPrevious;a.Qa.hasNext=c;a.M("previousNextChange")},A7=function(a){g.Jp(a.H);
a.H=g.Hp((0,g.z)(a.A,a,1),864E5)},z7=function(a,b,c){c?u7("Sending: action="+b+", params="+g.Hg(c)):u7("Sending: action="+b);
a.g.sendMessage(b,c)},E7=function(a){f6.call(this,"ScreenServiceProxy");
this.Hc=a;this.i=[];this.i.push(this.Hc.$_s("screenChange",(0,g.z)(this.rM,this)));this.i.push(this.Hc.$_s("onlineScreenChange",(0,g.z)(this.lJ,this)))},qqa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.zp("MDX_CONFIG")||b;Dpa();G4();F7||(F7=new V5(b?b.loungeApiHost:void 0),M4()&&(F7.g="/api/loungedev"));G7||(G7=g.x("yt.mdx.remote.deferredProxies_")||[],g.Ea("yt.mdx.remote.deferredProxies_",G7,void 0));mqa();var c=H7();if(!c){var d=new s6(F7);g.Ea("yt.mdx.remote.screenService_",d,void 0);c=H7();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);bqa(a,d,function(m){m?I7()&&a7(I7(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){r4("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.x("yt.mdx.remote.initialized_")&&(g.Ea("yt.mdx.remote.initialized_",!0,void 0),J7("Initializing: "+g.Hg(b)),K7.push(g.Op("yt-remote-cast2-availability-change",function(){r4("yt-remote-receiver-availability-change")})),K7.push(g.Op("yt-remote-cast2-receiver-selected",function(){L7(null);
r4("yt-remote-auto-connect","cast-selector-receiver")})),K7.push(g.Op("yt-remote-cast2-receiver-resumed",function(){r4("yt-remote-receiver-resumed","cast-selector-receiver")})),K7.push(g.Op("yt-remote-cast2-session-change",nqa)),K7.push(g.Op("yt-remote-connection-change",function(m){m?a7(I7(),"YouTube TV"):M7()||(a7(null,null),X6())})),a=N7(),b.isAuto&&(a.id+="#dial"),g.nq("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),J7(" -- with channel params: "+
g.Hg(a)),oqa(a),c.start(),I7()||pqa())},rqa=function(){var a=O7();
V6()&&g.$s("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},O7=function(){var a=H7().Hc.$_gos();
var b=P7();b&&Q7()&&(A4(a,b)||a.push(b));return Cpa(a)},R7=function(){var a=sqa();
!a&&V6()&&W6()&&(a={key:"cast-selector-receiver",name:W6()});return a},sqa=function(){var a=O7(),b=P7();
b||(b=M7());return g.Xa(a,function(c){return b&&u4(b,c.key)?!0:!1})},P7=function(){var a=I7();
if(!a)return null;var b=H7().Gd();return B4(b,a)},nqa=function(a){J7("remote.onCastSessionChange_: "+x4(a));
if(a){var b=P7();b&&b.id==a.id?a7(b.id,"YouTube TV"):(b&&S7(),T7(a,1))}else Q7()&&S7()},S7=function(){Z6()?S6().stopSession():P6("stopSession called before API ready.");
var a=Q7();a&&(a.disconnect(1),U7(null))},V7=function(){var a=Q7();
return!!a&&3!=a.getProxyState()},J7=function(a){b6("remote",a)},H7=function(){if(!W7){var a=g.x("yt.mdx.remote.screenService_");
W7=a?new E7(a):null}return W7},I7=function(){return g.x("yt.mdx.remote.currentScreenId_")},X7=function(a){g.Ea("yt.mdx.remote.currentScreenId_",a,void 0)},Y7=function(){return g.x("yt.mdx.remote.connectData_")},L7=function(a){g.Ea("yt.mdx.remote.connectData_",a,void 0)},Q7=function(){return g.x("yt.mdx.remote.connection_")},U7=function(a){var b=Q7();
L7(null);a||X7("");g.Ea("yt.mdx.remote.connection_",a,void 0);G7&&((0,g.B)(G7,function(c){c(a)}),G7.length=0);
b&&!a?r4("yt-remote-connection-change",!1):!b&&a&&r4("yt-remote-connection-change",!0)},M7=function(){var a=g.bt();
if(!a)return null;var b=H7().Gd();return B4(b,a)},T7=function(a,b){P7()&&P7();
X7(a.id);var c=new t7(F7,a,N7());c.connect(b,Y7());c.subscribe("beforeDisconnect",function(d){r4("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){Q7()&&U7(null)});
U7(c)},pqa=function(){var a=M7();
a?(J7("Resume connection to: "+x4(a)),T7(a,0)):(K4(),X6(),J7("Skipping connecting because no session screen found."))},mqa=function(){var a=N7();
if(g.Xb(a)){a=F4();var b=g.$s("yt-remote-session-name")||"",c=g.$s("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ea("yt.mdx.remote.channelParams_",a,void 0)}},N7=function(){return g.x("yt.mdx.remote.channelParams_")||{}},oqa=function(a){a?(g.Zs("yt-remote-session-app",a.app),g.Zs("yt-remote-session-name",a.name)):(g.at("yt-remote-session-app"),g.at("yt-remote-session-name"));
g.Ea("yt.mdx.remote.channelParams_",a,void 0)},Z7=function(a,b,c){g.G.call(this);
this.u=a;this.i=b;this.l=new g.Jr(this);g.H(this,this.l);this.l.K(b,"onCaptionsTrackListChanged",this.AI);this.l.K(b,"captionschanged",this.BH);this.l.K(b,"captionssettingschanged",this.Xz);this.l.K(b,"videoplayerreset",this.Wm);this.l.K(b,"mdxautoplaycancel",this.SB);this.O=this.l.K(b,"onVolumeChange",this.my);this.D=!1;this.g=c;c.subscribe("proxyStateChange",this.Ay,this);c.subscribe("remotePlayerChange",this.jk,this);c.subscribe("remoteQueueChange",this.Wm,this);c.subscribe("autoplayUpNext",this.Zx,
this);c.subscribe("previousNextChange",this.wy,this);c.subscribe("nowAutoplaying",this.ry,this);c.subscribe("autoplayDismissed",this.Yx,this);this.suggestion=null;this.F=new g.zC(64);this.o=new g.M(this.Vz,500,this);g.H(this,this.o);this.A=new g.M(this.Wz,1E3,this);g.H(this,this.A);this.I=new U4(this.aM,0,this);g.H(this,this.I);this.B={};this.P=new g.M(this.wA,1E3,this);g.H(this,this.P);this.H=new g.xl(this.hF,1E3,this);g.H(this,this.H);this.N=g.Ga;this.Xz();this.Wm();this.jk()},$7=function(a,b){a.u.pd(b,
a.i.getVideoData().lengthSeconds)},b8=function(a){$7(a,0);
a.o.stop();a8(a,new g.zC(64))},d8=function(a,b){if(c8(a)&&!a.D){var c=null;
b&&(c={style:a.i.getSubtitlesUserSettings()},g.ec(c,b));a.g.Lz(a.i.getVideoData(1).videoId,c);a.B=l7(a.g).g}},e8=function(a,b){var c=a.i.getPlaylist();
if(c){var d=c.Sa;var e=c.listId.toString()}c=a.i.getVideoData(1);a.g.playVideo(c.videoId,b,d,e,c.playerParams,c.Sh,n4(c));a8(a,new g.zC(1))},f8=function(a,b){if(b){var c=a.i.getOption("captions","tracklist",{PP:1});
c&&c.length?(a.i.setOption("captions","track",b),a.D=!1):(a.i.loadModule("captions"),a.D=!0)}else a.i.setOption("captions","track",{})},c8=function(a){return l7(a.g).videoId==a.i.getVideoData(1).videoId},a8=function(a,b){a.A.stop();
var c=a.F;if(!g.FC(c,b)){var d=g.U(b,2);d!=g.U(a.F,2)&&g.sJ(a.i,d);a.F=b;g8(a.u,c,b)}},i8=function(a){g.T.call(this,{C:"div",
G:"ytp-remote",J:[{C:"div",G:"ytp-remote-display-status",J:[{C:"div",G:"ytp-remote-display-status-icon",J:[g.GO()]},{C:"div",G:"ytp-remote-display-status-text",U:"{{statustext}}"}]}]});this.l=new g.qP(this,250);g.H(this,this.l);this.o=a;this.K(a,"presentingplayerstatechange",this.u);h8(this,g.oJ(a))},h8=function(a,b){if(3==a.o.getPresentingPlayerType()){var c={RECEIVER_NAME:a.o.getOption("remote","currentReceiver").name};
c=g.U(b,128)?g.FM("Error on $RECEIVER_NAME",c):g.GC(b)||g.U(b,4)?g.FM("Playing on $RECEIVER_NAME",c):g.FM("Connected to $RECEIVER_NAME",c);a.updateValue("statustext",c);a.l.show()}else a.l.hide()},j8=function(a,b){g.ZS.call(this,"Play on",0,a,b);
this.l=a;this.F={};this.K(a,"onMdxReceiversChange",this.I);this.K(a,"presentingplayerstatechange",this.I);this.I()},k8=function(a){g.TJ.call(this,a);
this.i={key:z4(),name:"This computer"};this.o=null;this.u=[];this.B=this.g=null;this.A=[this.i];this.l=this.i;this.Uj=new g.zC(64);this.D=0;this.km=-1;if(!g.Fy(g.V(this.player))){a=this.player;var b=g.YB(a);b&&(b=b.Gm())&&(b=new j8(a,b),g.H(this,b));b=new i8(a);g.H(this,b);g.FJ(a,b.element,4)}},g8=function(a,b,c){a.Uj=c;
a.player.M("presentingplayerstatechange",new g.KC(c,b))},l8=function(a,b){if(b.key!=a.l.key)if(b.key==a.i.key)S7();
else{a.l=b;var c=a.player.getPlaylistId();var d=a.player.getVideoData(1);var e=d.videoId;if(c||e){var f=a.player.getPlaylist();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.oa(l).videoId}else k=[e];f=a.player.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.Sh,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0==f?void 0:f};(d=n4(d))&&(c.locationInfo=d);d=c}else d=null;J7("Connecting to: "+g.Hg(b));"cast-selector-receiver"==b.key?
(L7(d||null),Z6()?S6().setLaunchParams(d||null):P6("setLaunchParams called before ready.")):!d&&V7()&&I7()==b.key?r4("yt-remote-connection-change",!0):(S7(),L7(d||null),d=H7().Gd(),(d=B4(d,b.key))&&T7(d,1))}},rpa=/^https?$/i,tqa=["POST",
"PUT"];g.A(l4,g.Qf);g.h=l4.prototype;
g.h.send=function(a,b,c,d){if(this.g)throw Error("[goog.net.XhrIo] Object is active with another request="+this.F+"; newUri="+a);b=b?b.toUpperCase():"GET";this.F=a;this.l="";this.u=0;this.aa=b;this.O=!1;this.i=!0;this.g=this.N?d4(this.N):d4(g.dY);this.P=this.N?this.N.getOptions():g.dY.getOptions();this.g.onreadystatechange=(0,g.z)(this.Iv,this);try{a4(e4(this,"Opening Xhr")),this.V=!0,this.g.open(b,String(a),!0),this.V=!1}catch(f){a4(e4(this,"Error opening Xhr: "+f.message));i4(this,f);return}a=c||
"";var e=this.headers.clone();d&&opa(d,function(f,k){e.set(k,f)});
d=g.Xa(e.Fd(),ppa);c=g.w.FormData&&a instanceof g.w.FormData;!g.$a(tqa,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,k){this.g.setRequestHeader(k,f)},this);
this.Y&&(this.g.responseType=this.Y);"withCredentials"in this.g&&this.g.withCredentials!==this.R&&(this.g.withCredentials=this.R);try{f4(this),0<this.A&&(this.I=qpa(this.g),a4(e4(this,"Will abort after "+this.A+"ms if incomplete, xhr2 "+this.I)),this.I?(this.g.timeout=this.A,this.g.ontimeout=(0,g.z)(this.Jv,this)):this.B=g.Dg(this.Jv,this.A,this)),a4(e4(this,"Sending request")),this.D=!0,this.g.send(a),this.D=!1}catch(f){a4(e4(this,"Send error: "+f.message)),i4(this,f)}};
g.h.Jv=function(){"undefined"!=typeof g.HX&&this.g&&(this.l="Timed out after "+this.A+"ms, aborting",this.u=8,e4(this,this.l),this.dispatchEvent("timeout"),this.abort(8))};
g.h.abort=function(a){this.g&&this.i&&(e4(this,"Aborting"),this.i=!1,this.o=!0,this.g.abort(),this.o=!1,this.u=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),h4(this))};
g.h.T=function(){this.g&&(this.i&&(this.i=!1,this.o=!0,this.g.abort(),this.o=!1),h4(this,!0));l4.Ga.T.call(this)};
g.h.Iv=function(){this.ea()||(this.V||this.D||this.o?k4(this):this.JJ())};
g.h.JJ=function(){k4(this)};
g.h.isActive=function(){return!!this.g};
g.h.getStatus=function(){try{return 2<j4(this)?this.g.status:-1}catch(a){return-1}};
g.h.getLastError=function(){return g.v(this.l)?this.l:String(this.l)};
var i5={"\x00":"\\0","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},h5={"'":"\\'"},uqa={};g.h=q4.prototype;g.h.isEmpty=function(){return 0==this.g.length&&0==this.i.length};
g.h.clear=function(){this.g=[];this.i=[]};
g.h.contains=function(a){return g.$a(this.g,a)||g.$a(this.i,a)};
g.h.remove=function(a){var b=this.g;var c=(0,g.Yla)(b,a);0<=c?(g.bb(b,c),b=!0):b=!1;return b||g.cb(this.i,a)};
g.h.zc=function(){for(var a=[],b=this.g.length-1;0<=b;--b)a.push(this.g[b]);var c=this.i.length;for(b=0;b<c;++b)a.push(this.i[b]);return a};
var Apa={QM:"atp",dP:"ska",SO:"que",rO:"mus",cP:"sus",IN:"dsp",ZO:"seq"};s4.prototype.Sf=function(){var a=new s4({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.l=this.l;a.i=this.i;a.g=this.g};
var L4,E4="",S4=N4("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",Ipa=N4("loadCastFramework")||N4("loadCastApplicationFramework"),aqa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.A(U4,g.G);g.h=U4.prototype;g.h.HC=function(a){this.o=arguments;this.g=!1;this.za?this.l=(0,g.C)()+this.Vc:this.za=g.Dg(this.u,this.Vc)};
g.h.stop=function(){this.za&&(g.w.clearTimeout(this.za),this.za=null);this.l=null;this.g=!1;this.o=[]};
g.h.pause=function(){++this.i};
g.h.resume=function(){this.i&&(--this.i,!this.i&&this.g&&(this.g=!1,this.A.apply(null,this.o)))};
g.h.T=function(){this.stop();U4.Ga.T.call(this)};
g.h.IC=function(){this.l?(this.za=g.Dg(this.u,this.l-(0,g.C)()),this.l=null):(this.za=null,this.i?this.g=!0:(this.g=!1,this.A.apply(null,this.o)))};V4.prototype.stringify=function(a){return g.w.JSON.stringify(a,void 0)};
V4.prototype.parse=function(a){return g.w.JSON.parse(a,void 0)};g.h=W4.prototype;g.h.Ng=null;g.h.re=!1;g.h.Gi=null;g.h.Ks=null;g.h.pi=null;g.h.Mh=null;g.h.Zf=null;g.h.sg=null;g.h.ih=null;g.h.tc=null;g.h.Jk=0;g.h.te=null;g.h.Wn=null;g.h.ag=null;g.h.zj=-1;g.h.xz=!0;g.h.Dg=!1;g.h.Dp=0;g.h.ln=null;var c5={},a5={};g.h=W4.prototype;g.h.setTimeout=function(a){this.o=a};
g.h.pL=function(a){a=a.target;var b=this.ln;b&&3==j4(a)?b.vj():this.GA(a)};
g.h.GA=function(a){try{if(a==this.tc)a:{var b=j4(this.tc),c=this.tc.u,d=this.tc.getStatus();if(g.Md&&!g.Dc(10)||g.Od&&!g.Cc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.yh&&!m4(this.tc))break a;this.Dg||4!=b||7==c||(8==c||0>=d?this.g.me(3):this.g.me(2));m5(this);var e=this.tc.getStatus();this.zj=e;var f=m4(this.tc);(this.re=200==e)?(4==b&&e5(this),this.u?(g5(this,b,f),g.yh&&this.re&&3==b&&(this.ca.da(this.i,"tick",this.lL),this.i.start())):d5(this,f),this.re&&!this.Dg&&(4==b?this.g.Um(this):(this.re=
!1,$4(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.ag=3,b5(13)):(this.ag=0,b5(14)),e5(this),f5(this))}}catch(k){this.tc&&m4(this.tc)}finally{}};
g.h.lL=function(){var a=j4(this.tc),b=m4(this.tc);this.Jk<b.length&&(m5(this),g5(this,a,b),this.re&&4!=a&&$4(this))};
g.h.JK=function(a){l5((0,g.z)(this.IK,this,a),0)};
g.h.IK=function(a){this.Dg||(m5(this),d5(this,a),$4(this))};
g.h.Hy=function(a){l5((0,g.z)(this.HK,this,a),0)};
g.h.HK=function(a){this.Dg||(e5(this),this.re=a,this.g.Um(this),this.g.me(4))};
g.h.cancel=function(){this.Dg=!0;e5(this)};
g.h.TK=function(){this.Gi=null;var a=(0,g.C)();0<=a-this.Ks?(2!=this.Mh&&this.g.me(3),e5(this),this.ag=2,b5(18),f5(this)):k5(this,this.Ks-a)};
g.h.getLastError=function(){return this.ag};g.h=q5.prototype;g.h.Bp=null;g.h.Bd=null;g.h.mn=!1;g.h.Hv=null;g.h.Gl=null;g.h.oq=null;g.h.Cp=null;g.h.Vd=null;g.h.rf=-1;g.h.yj=null;g.h.Si=null;g.h.connect=function(a){this.Cp=a;a=r5(this.g,null,this.Cp);b5(3);this.Hv=(0,g.C)();var b=this.g.D;null!=b?(this.yj=b[0],(this.Si=b[1])?(this.Vd=1,s5(this)):(this.Vd=2,u5(this))):(c4(a,"MODE","init"),this.Bd=new W4(this,void 0,void 0,void 0),this.Bd.Ng=this.Bp,Z4(this.Bd,a,!1,null,!0),this.Vd=0)};
g.h.TB=function(a){if(a)this.Vd=2,u5(this);else{b5(4);var b=this.g;b.Ce=b.Rf.rf;O5(b,9)}a&&this.me(2)};
g.h.Vo=function(a){return this.g.Vo(a)};
g.h.abort=function(){this.Bd&&(this.Bd.cancel(),this.Bd=null);this.rf=-1};
g.h.Gv=function(){return!1};
g.h.By=function(a,b){this.rf=a.zj;if(0==this.Vd)if(b){try{var c=this.i.parse(b)}catch(d){c=this.g;c.Ce=this.rf;O5(c,2);return}this.yj=c[0];this.Si=c[1]}else c=this.g,c.Ce=this.rf,O5(c,2);else if(2==this.Vd)if(this.mn)b5(7),this.oq=(0,g.C)();else if("11111"==b){if(b5(6),this.mn=!0,this.Gl=(0,g.C)(),c=this.Gl-this.Hv,!g.Md||g.Dc(10)||500>c)this.rf=200,this.Bd.cancel(),b5(12),t5(this.g,this,!0)}else b5(8),this.Gl=this.oq=(0,g.C)(),this.mn=!1};
g.h.Um=function(){this.rf=this.Bd.zj;if(this.Bd.re)0==this.Vd?this.Si?(this.Vd=1,s5(this)):(this.Vd=2,u5(this)):2==this.Vd&&((!g.Md||g.Dc(10)?!this.mn:200>this.oq-this.Gl)?(b5(11),t5(this.g,this,!1)):(b5(12),t5(this.g,this,!0)));else{0==this.Vd?b5(9):2==this.Vd&&b5(10);var a=this.g;this.Bd.getLastError();a.Ce=this.rf;O5(a,2)}};
g.h.Ak=function(){return this.g.Ak()};
g.h.isActive=function(){return this.g.isActive()};
g.h.me=function(a){this.g.me(a)};g.h=v5.prototype;g.h.fj=null;g.h.yd=null;g.h.Sb=null;g.h.Ap=null;g.h.Il=null;g.h.du=null;g.h.Rl=null;g.h.fk=0;g.h.TG=0;g.h.Tc=null;g.h.Wf=null;g.h.cf=null;g.h.Ig=null;g.h.Rf=null;g.h.Un=null;g.h.Xh=-1;g.h.mw=-1;g.h.Ce=-1;g.h.Hh=0;g.h.Bh=0;g.h.Eg=8;var P5=new g.Qf;g.A(w5,g.sf);g.A(x5,g.sf);g.A(y5,g.sf);g.h=v5.prototype;g.h.connect=function(a,b,c,d,e){b5(0);this.Ap=b;this.fj=c||{};d&&g.Ba(e)&&(this.fj.OSID=d,this.fj.OAID=e);this.A?(l5((0,g.z)(this.uu,this,a),100),E5(this)):this.uu(a)};
g.h.uu=function(a){this.Rf=new q5(this);this.Rf.Bp=null;this.Rf.i=this.u;this.Rf.connect(a)};
g.h.Gv=function(){return 0==this.g};
g.h.Gy=function(a){this.Wf=null;J5(this,a)};
g.h.Fy=function(){this.cf=null;this.Sb=new W4(this,this.l,"rpc",this.B);this.Sb.Ng=null;this.Sb.Dp=0;var a=this.du.clone();g.Wm(a,"RID","rpc");g.Wm(a,"SID",this.l);g.Wm(a,"CI",this.Un?"0":"1");g.Wm(a,"AID",this.Xh);A5(this,a);if(!g.Md||g.Dc(10))g.Wm(a,"TYPE","xmlhttp"),Z4(this.Sb,a,!0,this.Rl,!1);else{g.Wm(a,"TYPE","html");var b=this.Sb,c=!!this.Rl;b.Mh=3;b.Zf=b4(a.clone());j5(b,c)}};
g.h.By=function(a,b){if(0!=this.g&&(this.Sb==a||this.yd==a))if(this.Ce=a.zj,this.yd==a&&3==this.g)if(7<this.Eg){try{var c=this.u.parse(b)}catch(f){c=null}if(g.La(c)&&3==c.length)if(0==c[0])a:{if(!this.cf){if(this.Sb)if(this.Sb.pi+3E3<this.yd.pi)F5(this),this.Sb.cancel(),this.Sb=null;else break a;M5(this);b5(19)}}else this.mw=c[1],0<this.mw-this.Xh&&37500>c[2]&&this.Un&&0==this.Bh&&!this.Ig&&(this.Ig=l5((0,g.z)(this.wH,this),6E3));else O5(this,11)}else b!=uqa.nN.g&&O5(this,11);else if(this.Sb==a&&
F5(this),!g.wb(b)){c=this.u.parse(b);g.La(c);for(var d=0;d<c.length;d++){var e=c[d];this.Xh=e[0];e=e[1];2==this.g?"c"==e[0]?(this.l=e[1],this.Rl=e[2],e=e[3],null!=e?this.Eg=e:this.Eg=6,this.g=3,this.Tc&&this.Tc.nu(),this.du=r5(this,this.Ak()?this.Rl:null,this.Ap),K5(this)):"stop"==e[0]&&O5(this,7):3==this.g&&("stop"==e[0]?O5(this,7):"noop"!=e[0]&&this.Tc&&this.Tc.mu(e),this.Bh=0)}}};
g.h.wH=function(){null!=this.Ig&&(this.Ig=null,this.Sb.cancel(),this.Sb=null,M5(this),b5(20))};
g.h.Um=function(a){if(this.Sb==a){F5(this);this.Sb=null;var b=2}else if(this.yd==a)this.yd=null,b=1;else return;this.Ce=a.zj;if(0!=this.g)if(a.re)1==b?(b=(0,g.C)()-a.pi,P5.dispatchEvent(new x5(P5,a.ih?a.ih.length:0,b,this.Hh)),D5(this),this.o.length=0):K5(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.Ce)){if(d=1==b)this.yd||this.Wf||1==this.g||2<=this.Hh?d=!1:(this.Wf=l5((0,g.z)(this.Gy,this,a),L5(this,this.Hh)),this.Hh++,d=!0);d=!(d||2==b&&M5(this))}if(d)switch(c){case 1:O5(this,
5);break;case 4:O5(this,10);break;case 3:O5(this,6);break;case 7:O5(this,12);break;default:O5(this,2)}}};
g.h.kC=function(a){if(!g.$a(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.SL=function(a){a?b5(2):(b5(1),N5(this,8))};
g.h.Vo=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new l4;a.R=!1;return a};
g.h.isActive=function(){return!!this.Tc&&this.Tc.isActive(this)};
g.h.me=function(a){P5.dispatchEvent(new y5(P5,a))};
g.h.Ak=function(){return!(!g.Md||g.Dc(10))};
g.h=Q5.prototype;g.h.nu=function(){};
g.h.mu=function(){};
g.h.lu=function(){};
g.h.Lo=function(){};
g.h.gv=function(){return{}};
g.h.isActive=function(){return!0};g.A(R5,g.G);g.h=R5.prototype;g.h.BK=function(){this.Vc=Math.min(3E5,2*this.Vc);this.l();this.i&&this.start()};
g.h.start=function(){var a=this.Vc+15E3*Math.random();g.fo(this.g,a);this.i=(0,g.C)()+a};
g.h.stop=function(){this.g.stop();this.i=0};
g.h.isActive=function(){return this.g.isActive()};
g.h.reset=function(){this.g.stop();this.Vc=5E3};g.A(S5,Q5);g.h=S5.prototype;g.h.subscribe=function(a,b,c){return this.l.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.l.unsubscribe(a,b,c)};
g.h.zf=function(a){return this.l.Og(a)};
g.h.M=function(a,b){return this.l.M.apply(this.l,arguments)};
g.h.dispose=function(){this.Za||(this.Za=!0,g.qf(this.l),T5(this),g.qf(this.i),this.i=null)};
g.h.ea=function(){return this.Za};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.F="";this.i.stop();this.u=a||null;this.o=b||0;a=this.H+"/test";b=this.H+"/bind";var d=new v5(c?c.firstTestResults:null,c?c.secondTestResults:null,this.I),e=this.g;e&&(e.Tc=null);d.Tc=this;this.g=d;e?this.g.connect(a,b,this.A,e.l,e.Xh):c?this.g.connect(a,b,this.A,c.sessionId,c.arrayId):this.g.connect(a,b,this.A)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.ec(c,b);this.i.isActive()||2==(this.g?this.g.g:0)?this.B.push(c):U5(this)&&G5(this.g,c)};
g.h.nu=function(){this.i.reset();this.u=null;this.o=0;if(this.B.length){var a=this.B;this.B=[];for(var b=0,c=a.length;b<c;++b)G5(this.g,a[b])}this.M("handlerOpened")};
g.h.lu=function(a){var b=2==a&&401==this.g.Ce;4==a||b||this.i.start();this.M("handlerError",a)};
g.h.Lo=function(a){if(!this.i.isActive())this.M("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.B.push(d)}};
g.h.gv=function(){var a={v:2};this.F&&(a.gsessionid=this.F);0!=this.o&&(a.ui=""+this.o);0!=this.D&&(a.ui=""+this.D);this.u&&g.ec(a,this.u);return a};
g.h.mu=function(a){"S"==a[0]?this.F=a[1]:"gracefulReconnect"==a[0]?(this.i.start(),C5(this.g)):this.M("handlerMessage",new Mpa(a[0],a[1]))};
g.h.nM=function(){this.i.isActive();var a=this.g,b=0;a.Sb&&b++;a.yd&&b++;0!=b||this.connect(this.u,this.o)};V5.prototype.o=function(a,b,c,d){b?a(d):a({text:c.responseText})};
V5.prototype.l=function(a,b){a(Error("Request error: "+b.status))};
V5.prototype.u=function(a){a(Error("request timed out"))};var Spa=(0,g.C)(),$5=null,d6=Array(50),c6=-1,e6=!1;g.A(f6,g.O);f6.prototype.Gd=function(){return this.g};
f6.prototype.contains=function(a){return!!A4(this.g,a)};
f6.prototype.get=function(a){return a?B4(this.g,a):null};
f6.prototype.info=function(a){b6(this.B,a)};g.A(h6,g.O);var m8=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=h6.prototype;g.h.start=function(){!this.g&&isNaN(this.za)&&this.JA()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);isNaN(this.za)||(g.Jp(this.za),this.za=NaN)};
g.h.T=function(){this.stop();h6.Ga.T.call(this)};
g.h.JA=function(){this.za=NaN;this.g=g.wq(W5(this.A,"/pairing/get_screen"),{method:"POST",qb:{pairing_code:this.u},timeout:5E3,onSuccess:(0,g.z)(this.pM,this),onError:(0,g.z)(this.oM,this),nd:(0,g.z)(this.qM,this)})};
g.h.pM=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.l;c.name=this.o;this.M("pairingComplete",new t4(c))};
g.h.oM=function(a){this.g=null;a.status&&404==a.status?this.i>=m8.length?this.M("pairingFailed",Error("DIAL polling timed out")):(a=m8[this.i],this.za=g.Hp((0,g.z)(this.JA,this),a),this.i++):this.M("pairingFailed",Error("Server error "+a.status))};
g.h.qM=function(){this.g=null;this.M("pairingFailed",Error("Server not responding"))};g.A(j6,f6);g.h=j6.prototype;g.h.start=function(){i6(this)&&this.M("screenChange");!g.$s("yt-remote-lounge-token-expiration")&&k6(this);g.Jp(this.i);this.i=g.Hp((0,g.z)(this.start,this),1E4)};
g.h.add=function(a,b){i6(this);g6(this,a);l6(this,!1);this.M("screenChange");b(a);a.token||k6(this)};
g.h.remove=function(a,b){var c=i6(this);Upa(this,a)&&(l6(this,!1),c=!0);b(a);c&&this.M("screenChange")};
g.h.Qn=function(a,b,c,d){var e=i6(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,l6(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.M("screenChange")};
g.h.T=function(){g.Jp(this.i);j6.Ga.T.call(this)};
g.h.SC=function(a){i6(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}l6(this,!b);b&&b6(this.B,"Missed "+b+" lounge tokens.")};
g.h.RC=function(a){b6(this.B,"Requesting lounge tokens failed: "+a)};g.A(n6,g.O);g.h=n6.prototype;g.h.start=function(){var a=parseInt(g.$s("yt-remote-fast-check-period")||"0",10);(this.o=(0,g.C)()-144E5<a?0:a)?q6(this):(this.o=(0,g.C)()+3E5,g.Zs("yt-remote-fast-check-period",this.o),this.Lr())};
g.h.isEmpty=function(){return g.Xb(this.g)};
g.h.update=function(){m6("Updating availability on schedule.");var a=this.A(),b=g.Lb(this.g,function(c,d){return c&&!!B4(a,d)},this);
p6(this,b)};
g.h.T=function(){g.Jp(this.l);this.l=NaN;this.i&&(this.i.abort(),this.i=null);n6.Ga.T.call(this)};
g.h.Lr=function(){g.Jp(this.l);this.l=NaN;this.i&&this.i.abort();var a=r6(this);if(o4(a)){var b=W5(this.u,"/pairing/get_screen_availability");this.i=X5(this.u,b,{lounge_token:g.Rb(a).join(",")},(0,g.z)(this.fK,this,a),(0,g.z)(this.eK,this))}else p6(this,{}),q6(this)};
g.h.fK=function(a,b){this.i=null;var c=g.Rb(r6(this));if(g.rb(c,g.Rb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;p6(this,d);q6(this)}else this.Lb("Changing Screen set during request."),this.Lr()};
g.h.eK=function(a){this.Lb("Screen availability failed: "+a);this.i=null;q6(this)};
g.h.Lb=function(a){b6("OnlineScreenService",a)};g.A(s6,f6);g.h=s6.prototype;g.h.start=function(){this.l.start();this.i.start();this.g.length&&(this.M("screenChange"),this.i.isEmpty()||this.M("onlineScreenChange"))};
g.h.add=function(a,b,c){this.l.add(a,b,c)};
g.h.remove=function(a,b,c){this.l.remove(a,b,c);this.i.update()};
g.h.Qn=function(a,b,c,d){this.l.contains(a)?this.l.Qn(a,b,c,d):(a="Updating name of unknown screen: "+a.name,b6(this.B,a),d(Error(a)))};
g.h.Gd=function(a){return a?this.g:g.fb(this.g,(0,g.Yd)(this.o,function(b){return!this.contains(b)},this))};
g.h.KA=function(){return(0,g.Yd)(this.Gd(!0),function(a){return!!this.i.g[a.id]},this)};
g.h.LA=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new h6(this.A,a,b,c);f.subscribe("pairingComplete",(0,g.z)(function(k){g.qf(f);d(t6(this,k))},this));
f.subscribe("pairingFailed",function(k){g.qf(f);e(k)});
f.start();return(0,g.z)(f.stop,f)};
g.h.sM=function(a,b,c,d){g.wq(W5(this.A,"/pairing/get_screen"),{method:"POST",qb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.z)(function(e,f){var k=new t4(f.screen||{});if(!k.name||v6(this,k.name)){a:{var l=k.name;for(var m=2,n=b(l,m);v6(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}k.name=l}c(t6(this,k))},this),
onError:(0,g.z)(function(e){d(Error("pairing request failed: "+e.status))},this),
nd:(0,g.z)(function(){d(Error("pairing request timed out."))},this)})};
g.h.T=function(){g.qf(this.l);g.qf(this.i);s6.Ga.T.call(this)};
g.h.bD=function(){w6(this);this.M("screenChange");this.i.update()};
s6.prototype.dispose=s6.prototype.dispose;g.A(y6,g.O);g.h=y6.prototype;g.h.Vm=function(a){this.l=a;this.M("sessionScreen",this.l)};
g.h.Jd=function(a){this.ea()||(a&&z6(this,""+a),this.l=null,this.M("sessionScreen",null))};
g.h.info=function(a){b6(this.P,a)};
g.h.NA=function(){return null};
g.h.Vr=function(a){var b=this.i;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.z)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.z)(function(){z6(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.T=function(){this.Vr("");y6.Ga.T.call(this)};g.A(B6,y6);g.h=B6.prototype;g.h.Ur=function(a){if(this.g){if(this.g==a)return;z6(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.A);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.u)}this.g=a;this.g.addUpdateListener(this.A);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.u);Ypa(this)};
g.h.Zh=function(a){this.info("launchWithParams no-op for Cast: "+g.Hg(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.z)(function(){this.Jd()},this),(0,g.z)(function(){this.Jd(Error("Failed to stop receiver app."))},this)):this.Jd(Error("Stopping cast device witout session."))};
g.h.Vr=g.Ga;g.h.T=function(){this.info("disposeInternal");g.Jp(this.o);this.o=0;this.g&&(this.g.removeUpdateListener(this.A),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.u));this.g=null;B6.Ga.T.call(this)};
g.h.eL=function(a,b){if(!this.ea())if(b){var c=p4(b);if(g.Oa(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Hg(c));switch(d){case "mdxSessionStatus":A6(this,c.screenId);break;default:z6(this,"Unknown youtube message: "+d)}}else z6(this,"Unable to parse message.")}else z6(this,"No data in message.")};
g.h.zv=function(a,b,c,d){u6(this.F,this.i.label,a,this.i.friendlyName,(0,g.z)(function(e){e?b(e):0<=d?(z6(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.Hp((0,g.z)(this.zv,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.NA=function(){return this.g};
g.h.tM=function(a){this.ea()||a||(z6(this,"Cast session died."),this.Jd())};g.A(C6,y6);g.h=C6.prototype;g.h.Ur=function(a){this.o=a;this.o.addUpdateListener(this.I)};
g.h.Zh=function(a){this.u=a;this.B()};
g.h.stop=function(){this.g();this.g=g.Ga;g.Jp(this.A);this.o?this.o.stop((0,g.z)(this.Jd,this,null),(0,g.z)(this.Jd,this,"Failed to stop DIAL device.")):this.Jd()};
g.h.T=function(){this.g();this.g=g.Ga;g.Jp(this.A);this.o&&this.o.removeUpdateListener(this.I);this.o=null;C6.Ga.T.call(this)};
g.h.wM=function(a){this.ea()||a||(z6(this,"DIAL session died."),this.g(),this.g=g.Ga,this.Jd())};
g.h.Qp=function(a){this.H=z4();if(this.u){var b=new chrome.cast.DialLaunchResponse(!0,E6(this));a(b);D6(this)}else this.B=(0,g.z)(function(){g.Jp(this.A);this.B=g.Ga;this.A=NaN;var c=new chrome.cast.DialLaunchResponse(!0,E6(this));a(c);D6(this)},this),this.A=g.Hp((0,g.z)(function(){this.B()},this),100)};
g.h.xD=function(a,b,c){u6(this.F,this.D.receiver.label,a,this.i.friendlyName,(0,g.z)(function(d){d&&d.token?(this.Vm(d),b(new chrome.cast.DialLaunchResponse(!1))):this.Qp(b,c)},this),(0,g.z)(function(d){z6(this,"Failed to get DIAL screen: "+d);
this.Qp(b,c)},this))};g.A(F6,y6);F6.prototype.stop=function(){this.Jd()};
F6.prototype.Ur=g.Ga;F6.prototype.Zh=function(){g.Jp(this.g);this.g=NaN;var a=B4(this.F.Gd(),this.i.label);a?this.Vm(a):this.Jd(Error("No such screen"))};
F6.prototype.T=function(){g.Jp(this.g);this.g=NaN;F6.Ga.T.call(this)};g.A(G6,g.O);g.h=G6.prototype;
g.h.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.B);this.D||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new chrome.cast.ApiConfig(c,(0,g.z)(this.Dy,this),(0,g.z)(this.OJ,this),d,e);c.customDialLaunchCallback=(0,g.z)(this.XH,this);chrome.cast.initialize(c,(0,g.z)(function(){this.ea()||
(chrome.cast.addReceiverActionListener(this.o),Ppa(),this.i.subscribe("onlineScreenChange",(0,g.z)(this.MA,this)),this.l=L6(this),chrome.cast.setCustomReceivers(this.l,g.Ga,(0,g.z)(function(f){this.Lb("Failed to set initial custom receivers: "+g.Hg(f))},this)),this.M("yt-remote-cast2-availability-change",J6(this)),b(!0))},this),(0,g.z)(function(f){this.Lb("Failed to initialize API: "+g.Hg(f));
b(!1)},this))};
g.h.GL=function(a,b){I6("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.l;if(!a||c&&c.id!=a)I6("Unsetting old screen status: "+this.g.i.friendlyName),K6(this,null)}if(a&&b){if(!this.g){c=B4(this.i.Gd(),a);if(!c){I6("setConnectedScreenStatus: Unknown screen.");return}var d=H6(this,c);d||(I6("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.l.push(d),chrome.cast.setCustomReceivers(this.l,
g.Ga,(0,g.z)(function(e){this.Lb("Failed to set initial custom receivers: "+g.Hg(e))},this)));
I6("setConnectedScreenStatus: new active receiver: "+d.friendlyName);K6(this,new F6(this.i,d),!0)}this.g.Vr(b)}else I6("setConnectedScreenStatus: no screen.")};
g.h.HL=function(a){this.ea()?this.Lb("Setting connection data on disposed cast v2"):this.g?this.g.Zh(a):this.Lb("Setting connection data without a session")};
g.h.vM=function(){this.ea()?this.Lb("Stopping session on disposed cast v2"):this.g?(this.g.stop(),K6(this,null)):I6("Stopping non-existing session")};
g.h.requestSession=function(){chrome.cast.requestSession((0,g.z)(this.Dy,this),(0,g.z)(this.kK,this))};
g.h.T=function(){this.i.unsubscribe("onlineScreenChange",(0,g.z)(this.MA,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.o);g.cb(g.x("yt.mdx.remote.debug.handlers_")||[],Y5);g.qf(this.g);G6.Ga.T.call(this)};
g.h.Lb=function(a){b6("Controller",a)};
g.h.Ey=function(a,b){this.g==a&&(b||K6(this,null),this.M("yt-remote-cast2-session-change",b))};
g.h.KJ=function(a,b){if(!this.ea())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),I6("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.i.label!=a.label)I6("onReceiverAction_: Stopping active receiver: "+this.g.i.friendlyName),this.g.stop();else{I6("onReceiverAction_: Casting to active receiver.");this.g.l&&this.M("yt-remote-cast2-session-change",this.g.l);break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:K6(this,
new F6(this.i,a));break;case chrome.cast.ReceiverType.DIAL:K6(this,new C6(this.i,a,this.A));break;case chrome.cast.ReceiverType.CAST:K6(this,new B6(this.i,a));break;default:this.Lb("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.g&&this.g.i.label==a.label?this.g.stop():this.Lb("Stopping receiver w/o session: "+a.friendlyName)}else this.Lb("onReceiverAction_ called without receiver.")};
g.h.XH=function(a){if(this.ea())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Lb("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.i:null;if(!c||c.label!=b.label)return this.Lb("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.g.l)return I6("Reselecting dial screen."),
this.M("yt-remote-cast2-session-change",this.g.l),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Lb('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);K6(this,new C6(this.i,b,this.A))}b=this.g;b.D=a;return b.D.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.z)(b.xD,b,(b.D.extraData||{}).screenId||null)):new Promise((0,g.z)(b.Qp,b))};
g.h.Dy=function(a){if(!this.ea()){I6("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==chrome.cast.ReceiverType.CAST)I6("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),K6(this,new B6(this.i,b),!0);else{this.Lb("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.i,d=B4(this.i.Gd(),c.label);d&&u4(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(I6("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.qf(this.g),this.g=new B6(this.i,b),this.g.subscribe("sessionScreen",(0,g.z)(this.Ey,this,this.g)),this.g.Zh(null));this.g.Ur(a)}}};
g.h.uM=function(){return this.g?this.g.NA():null};
g.h.kK=function(a){this.ea()||(this.Lb("Failed to estabilish a session: "+g.Hg(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&K6(this,null))};
g.h.OJ=function(a){I6("Receiver availability updated: "+a);if(!this.ea()){var b=J6(this);this.u=a==chrome.cast.ReceiverAvailability.AVAILABLE;J6(this)!=b&&this.M("yt-remote-cast2-availability-change",J6(this))}};
g.h.MA=function(){this.ea()||(this.l=L6(this),I6("Updating custom receivers: "+g.Hg(this.l)),chrome.cast.setCustomReceivers(this.l,g.Ga,(0,g.z)(function(){this.Lb("Failed to set custom receivers.")},this)),this.M("yt-remote-cast2-availability-change",J6(this)))};
G6.prototype.setLaunchParams=G6.prototype.HL;G6.prototype.setConnectedScreenStatus=G6.prototype.GL;G6.prototype.stopSession=G6.prototype.vM;G6.prototype.getCastSession=G6.prototype.uM;G6.prototype.requestSession=G6.prototype.requestSession;G6.prototype.init=G6.prototype.init;G6.prototype.dispose=G6.prototype.dispose;var U6=[];b7.prototype.reset=function(a){this.listId="";this.index=-1;this.videoId="";c7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.g=a.trackData,this.Ee=a.hasPrevious,this.hasNext=a.hasNext,this.B=a.playerTime,this.A=a.playerTimeAt,this.o=a.seekableStart,this.i=a.seekableEnd,this.D=a.duration,this.F=a.loadedTime,this.l=a.liveIngestionTime,this.u=
!isNaN(this.l))};
b7.prototype.isAdPlaying=function(){return 1081==this.playerState};
b7.prototype.getDuration=function(){return this.u?this.D+d7(this):this.D};
b7.prototype.clone=function(){return new b7(h7(this))};g.A(k7,g.O);g.h=k7.prototype;g.h.play=function(){1==this.g?(this.i?this.i.play(null,g.Ga,s7(this,"play")):q7(this,"play"),p7(this,1,f7(l7(this))),this.M("remotePlayerChange")):n7(this,this.play)};
g.h.pause=function(){1==this.g?(this.i?this.i.pause(null,g.Ga,s7(this,"pause")):q7(this,"pause"),p7(this,2,f7(l7(this))),this.M("remotePlayerChange")):n7(this,this.pause)};
g.h.seekTo=function(a){if(1==this.g){if(this.i){var b=l7(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=1==b.playerState||3==b.playerState?chrome.cast.media.ResumeState.PLAYBACK_START:chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.i.seek(c,g.Ga,s7(this,"seekTo",{newTime:a}))}else q7(this,"seekTo",{newTime:a});p7(this,3,a);this.M("remotePlayerChange")}else n7(this,g.Ra(this.seekTo,a))};
g.h.stop=function(){if(1==this.g){this.i?this.i.stop(null,g.Ga,s7(this,"stopVideo")):q7(this,"stopVideo");var a=l7(this);a.index=-1;a.videoId="";c7(a);o7(this,a);this.M("remotePlayerChange")}else n7(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=l7(this);if(this.l){if(c.volume!=a){var d=Math.round(a)/100;this.l.setReceiverVolumeLevel(d,(0,g.z)(function(){b6("CP","set receiver volume: "+d)},this),(0,g.z)(function(){this.Lb("failed to set receiver volume.")},this))}c.muted!=b&&this.l.setReceiverMuted(b,(0,g.z)(function(){b6("CP","set receiver muted: "+b)},this),(0,g.z)(function(){this.Lb("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);q7(this,"setVolume",e)}c.muted=b;c.volume=a;o7(this,c)}else n7(this,g.Ra(this.setVolume,a,b))};
g.h.Lz=function(a,b){if(1==this.g){var c=l7(this),d={videoId:a};b&&(c.g={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.Hg(b.style),g.ec(d,c.g));q7(this,"setSubtitlesTrack",d);o7(this,c)}else n7(this,g.Ra(this.Lz,a,b))};
g.h.setAudioTrack=function(a,b){if(1==this.g){var c=b.getLanguageInfo().getId();q7(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=l7(this);d.audioTrackId=c;o7(this,d)}else n7(this,g.Ra(this.setAudioTrack,a,b))};
g.h.playVideo=function(a,b,c,d,e,f,k){var l=l7(this);c=c||0;var m={videoId:a,currentIndex:c};g7(l,a,c);g.Ba(b)&&(e7(l,b),m.currentTime=b);g.Ba(d)&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=k&&(m.locationInfo=g.Hg(k));q7(this,"setPlaylist",m);d||o7(this,l)};
g.h.dn=function(a,b){if(1==this.g){if(a&&b){var c=l7(this);g7(c,a,b);o7(this,c)}q7(this,"previous")}else n7(this,g.Ra(this.dn,a,b))};
g.h.nextVideo=function(a,b){if(1==this.g){if(a&&b){var c=l7(this);g7(c,a,b);o7(this,c)}q7(this,"next")}else n7(this,g.Ra(this.nextVideo,a,b))};
g.h.Mu=function(){1==this.g?q7(this,"dismissAutoplay"):n7(this,this.Mu)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.M("proxyStateChange",a,this.g)}k7.Ga.dispose.call(this)};
g.h.T=function(){m7(this);this.o=null;this.u.clear();j7(this,null);k7.Ga.T.call(this)};
g.h.Ns=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.M("proxyStateChange",b,a);if(1==a)for(;!this.u.isEmpty();)b=a=this.u,0==b.g.length&&(b.g=b.i,b.g.reverse(),b.i=[]),a.g.pop().apply(this);else 3==a&&this.dispose()}};
g.h.HJ=function(a,b){this.M(a,b)};
g.h.DH=function(a){if(!a)this.hk(null),j7(this,null);else if(this.l.receiver.volume){a=this.l.receiver.volume;var b=l7(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)b6("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,o7(this,b)}};
g.h.hk=function(a){b6("CP","Cast media: "+!!a);this.i&&this.i.removeUpdateListener(this.D);if(this.i=a)this.i.addUpdateListener(this.D),r7(this),this.M("remotePlayerChange")};
g.h.CH=function(a){a?(r7(this),this.M("remotePlayerChange")):this.hk(null)};
g.h.xs=function(){q7(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.PH=function(){var a=Y6();a&&j7(this,a)};
g.h.Lb=function(a){b6("CP",a)};g.A(t7,g.O);g.h=t7.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.Ba(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.Ba(k)&&(l.currentIndex=k);c&&(this.Qa.listId=c);this.Qa.videoId=d;this.Qa.index=k||0;this.Qa.state=3;e7(this.Qa,m);this.o="UNSUPPORTED";u7("Connecting with setPlaylist and params: "+g.Hg(l));this.g.connect({method:"setPlaylist",
params:g.Hg(l)},a,H4())}else u7("Connecting without params"),this.g.connect({},a,H4());eqa(this)};
g.h.dispose=function(){this.ea()||(this.M("beforeDispose"),v7(this,3));t7.Ga.dispose.call(this)};
g.h.T=function(){w7(this);y7(this);x7(this);g.Jp(this.F);this.F=NaN;g.Jp(this.H);this.H=NaN;this.l=null;g.xr(this.O);this.O.length=0;this.g.dispose();t7.Ga.T.call(this);this.o=this.B=this.i=this.Qa=this.g=null};
g.h.LC=function(){this.A(2)};
g.h.HH=function(){u7("Channel opened");this.N&&(this.N=!1,x7(this),this.P=g.Hp((0,g.z)(function(){u7("Timing out waiting for a screen.");this.A(1)},this),15E3));
Gpa(Npa(this.g),this.V)};
g.h.EH=function(){u7("Channel closed");isNaN(this.u)?K4(!0):K4();this.dispose()};
g.h.FH=function(a){K4();isNaN(this.D())?(u7("Channel error: "+a+" without reconnection"),this.dispose()):(this.N=!0,u7("Channel error: "+a+" with reconnection in "+this.D()+" ms"),v7(this,2))};
g.h.GH=function(a){a.params?u7("Received: action="+a.action+", params="+g.Hg(a.params)):u7("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=p4(a.params.devices);this.i=(0,g.F)(a,function(c){return new s4(c)});
a=!!g.Xa(this.i,function(c){return"LOUNGE_SCREEN"==c.type});
B7(this,a);break;case "loungeScreenDisconnected":g.db(this.i,function(c){return"LOUNGE_SCREEN"==c.type});
B7(this,!1);break;case "remoteConnected":var b=new s4(p4(a.params.device));g.Xa(this.i,function(c){return b?c.id==b.id:!1})||upa(this.i,b);
break;case "remoteDisconnected":b=new s4(p4(a.params.device));g.db(this.i,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":C7(this,a);break;case "nowPlaying":hqa(this,a);break;case "onStateChange":D7(this,a);break;case "onAdStateChange":iqa(this,a);break;case "onVolumeChanged":jqa(this,a);break;case "onSubtitlesTrackChanged":gqa(this,a);break;case "nowAutoplaying":kqa(this,a);break;case "autoplayDismissed":this.M("autoplayDismissed");break;case "autoplayUpNext":this.B=a.params.videoId||null;this.M("autoplayUpNext",this.B);break;case "onAutoplayModeChanged":this.o=
a.params.autoplayMode;this.M("autoplayModeChange",this.o);"DISABLED"==this.o&&this.M("autoplayDismissed");break;case "onHasPreviousNextChanged":lqa(this,a);break;case "requestAssistedSignIn":this.M("assistedSignInRequested",a.params.authCode);break;default:u7("Unrecognized action: "+a.action)}};
g.h.vL=function(){if(this.l){var a=this.l;this.l=null;this.Qa.videoId!=a&&z7(this,"getNowPlaying")}};
t7.prototype.subscribe=t7.prototype.subscribe;t7.prototype.unsubscribeByKey=t7.prototype.zf;t7.prototype.ba=function(){var a=3;this.ea()||(a=0,isNaN(this.D())?U5(this.g)&&isNaN(this.u)&&(a=1):a=2);return a};
t7.prototype.getProxyState=t7.prototype.ba;t7.prototype.A=function(a){u7("Disconnecting with "+a);w7(this);this.M("beforeDisconnect",a);1==a&&K4();T5(this.g,a);this.dispose()};
t7.prototype.disconnect=t7.prototype.A;t7.prototype.X=function(){var a=this.Qa;this.l&&(a=this.Qa.clone(),g7(a,this.l,a.index));return h7(a)};
t7.prototype.getPlayerContextData=t7.prototype.X;
t7.prototype.la=function(a){var b=new b7(a);b.videoId&&b.videoId!=this.Qa.videoId&&(this.l=b.videoId,g.Jp(this.F),this.F=g.Hp((0,g.z)(this.vL,this),5E3));var c=[];this.Qa.listId==b.listId&&this.Qa.videoId==b.videoId&&this.Qa.index==b.index||c.push("remoteQueueChange");this.Qa.playerState==b.playerState&&this.Qa.volume==b.volume&&this.Qa.muted==b.muted&&f7(this.Qa)==f7(b)&&g.Hg(this.Qa.g)==g.Hg(b.g)||c.push("remotePlayerChange");this.Qa.reset(a);(0,g.B)(c,function(d){this.M(d)},this)};
t7.prototype.setPlayerContextData=t7.prototype.la;t7.prototype.R=function(){var a=this.g.A.id,b=g.Xa(this.i,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
t7.prototype.getOtherConnectedRemoteId=t7.prototype.R;t7.prototype.D=function(){var a=this.g;return a.i.isActive()?a.i.i-(0,g.C)():NaN};
t7.prototype.getReconnectTimeout=t7.prototype.D;t7.prototype.aa=function(){return this.o||"UNSUPPORTED"};
t7.prototype.getAutoplayMode=t7.prototype.aa;t7.prototype.Y=function(){return this.B||""};
t7.prototype.getAutoplayVideoId=t7.prototype.Y;t7.prototype.ua=function(){if(!isNaN(this.D())){var a=this.g.i;g.go(a.g);a.start()}};
t7.prototype.reconnect=t7.prototype.ua;t7.prototype.ha=function(a,b){z7(this,a,b);A7(this)};
t7.prototype.sendMessage=t7.prototype.ha;g.A(E7,f6);g.h=E7.prototype;g.h.Gd=function(a){return this.Hc.$_gs(a)};
g.h.contains=function(a){return!!this.Hc.$_c(a)};
g.h.get=function(a){return this.Hc.$_g(a)};
g.h.start=function(){this.Hc.$_st()};
g.h.add=function(a,b,c){this.Hc.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Hc.$_r(a,b,c)};
g.h.Qn=function(a,b,c,d){this.Hc.$_un(a,b,c,d)};
g.h.T=function(){for(var a=0,b=this.i.length;a<b;++a)this.Hc.$_ubk(this.i[a]);this.i.length=0;this.Hc=null;E7.Ga.T.call(this)};
g.h.rM=function(){this.M("screenChange")};
g.h.lJ=function(){this.M("onlineScreenChange")};
s6.prototype.$_st=s6.prototype.start;s6.prototype.$_gspc=s6.prototype.sM;s6.prototype.$_gsppc=s6.prototype.LA;s6.prototype.$_c=s6.prototype.contains;s6.prototype.$_g=s6.prototype.get;s6.prototype.$_a=s6.prototype.add;s6.prototype.$_un=s6.prototype.Qn;s6.prototype.$_r=s6.prototype.remove;s6.prototype.$_gs=s6.prototype.Gd;s6.prototype.$_gos=s6.prototype.KA;s6.prototype.$_s=s6.prototype.subscribe;s6.prototype.$_ubk=s6.prototype.zf;var F7=null,G7=null,W7=null,K7=[];g.t(Z7,g.G);g.h=Z7.prototype;
g.h.T=function(){g.G.prototype.T.call(this);this.o.stop();this.A.stop();this.I.stop();this.N();this.g.unsubscribe("proxyStateChange",this.Ay,this);this.g.unsubscribe("remotePlayerChange",this.jk,this);this.g.unsubscribe("remoteQueueChange",this.Wm,this);this.g.unsubscribe("autoplayUpNext",this.Zx,this);this.g.unsubscribe("previousNextChange",this.wy,this);this.g.unsubscribe("nowAutoplaying",this.ry,this);this.g.unsubscribe("autoplayDismissed",this.Yx,this);this.g=this.u=null};
g.h.Xw=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(c8(this)){if(!l7(this.g).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":1==l7(this.g).playerState?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.H.vj(c[0],c[1]);break;case "control_subtitles_set_track":d8(this,c[0]);break;case "control_set_audio_track":c=c[0],c8(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.i.getCurrentTime();e8(this,0==c?void 0:c);break;case "control_seek":e8(this,c[0]);break;case "control_subtitles_set_track":d8(this,c[0]);break;case "control_set_audio_track":c=c[0],c8(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,c)}};
g.h.BH=function(a){this.I.HC(a)};
g.h.aM=function(a){this.Xw("control_subtitles_set_track",g.Xb(a)?null:a)};
g.h.Xz=function(){var a=this.i.getOption("captions","track");g.Xb(a)||d8(this,a)};
g.h.my=function(a){if(c8(this)){this.g.unsubscribe("remotePlayerChange",this.jk,this);var b=Math.round(a.volume);a=!!a.muted;var c=l7(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.P.start();this.g.subscribe("remotePlayerChange",this.jk,this)}};
g.h.AI=function(){g.Xb(this.B)||f8(this,this.B);this.D=!1};
g.h.Ay=function(a,b){this.A.stop();2==b&&this.Wz()};
g.h.jk=function(){if(c8(this)){this.o.stop();var a=l7(this.g);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.u.km=1;break;case 1082:case 1083:this.u.km=0;break;default:this.u.km=-1}switch(a.playerState){case 1081:case 1:a8(this,new g.zC(8));this.Vz();break;case 1085:case 3:a8(this,new g.zC(9));break;case 1083:case 0:a8(this,new g.zC(2));this.H.stop();$7(this,this.i.getVideoData().lengthSeconds);break;case 1084:a8(this,new g.zC(4));break;case 2:a8(this,new g.zC(4));$7(this,f7(a));
break;case -1:a8(this,new g.zC(64));break;case -1E3:a8(this,new g.zC(128,{errorCode:"mdx.remoteerror",message:"This video is not available for remote playback."}))}a=l7(this.g).g;var b=this.B;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.B=a,f8(this,a));a=l7(this.g);-1==a.volume||Math.round(this.i.getVolume())==a.volume&&this.i.isMuted()==a.muted||this.P.isActive()||this.wA()}else b8(this)};
g.h.wy=function(){this.i.M("mdxpreviousnextchange")};
g.h.Wm=function(){c8(this)||b8(this)};
g.h.SB=function(){this.g.Mu()};
g.h.Zx=function(a){a&&(a=g.wq("/watch_queue_ajax",{method:"GET",Dc:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.z)(this.MK,this)}))&&(this.N=(0,g.z)(a.abort,a))};
g.h.MK=function(a,b){var c=new g.FA(g.V(this.i),{videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.i.M("mdxautoplayupnext",c)};
g.h.ry=function(a){isNaN(a)||this.i.M("mdxnowautoplaying",a)};
g.h.Yx=function(){this.i.M("mdxautoplaycanceled")};
g.h.hF=function(a,b){-1==l7(this.g).playerState?e8(this,a):b&&this.g.seekTo(a)};
g.h.wA=function(){if(c8(this)){var a=l7(this.g);this.l.Na(this.O);a.muted?this.i.mute():this.i.unMute();this.i.setVolume(a.volume);this.O=this.l.K(this.i,"onVolumeChange",this.my)}};
g.h.Vz=function(){this.o.stop();if(!this.g.ea()){var a=l7(this.g);1==a.playerState&&a8(this,new g.zC(8));$7(this,f7(a));this.o.start()}};
g.h.Wz=function(){this.A.stop();this.o.stop();var a=this.g.o.getReconnectTimeout();2==this.g.g&&!isNaN(a)&&this.A.start()};g.t(i8,g.T);i8.prototype.u=function(a){h8(this,a.state)};g.t(j8,g.ZS);j8.prototype.I=function(){var a=this.l.getOption("remote","receivers");a&&1<a.length&&!this.l.getOption("remote","quickCast")?(this.F=g.tb(a,this.A,this),g.$S(this,(0,g.F)(a,this.A)),a=this.l.getOption("remote","currentReceiver"),this.le(this.A(a)),this.enable(!0)):this.enable(!1)};
j8.prototype.A=function(a){return a.key};
j8.prototype.ke=function(a){return"cast-selector-receiver"==a?"Cast...":this.F[a].name};
j8.prototype.Jc=function(a){g.ZS.prototype.Jc.call(this,a);this.l.setOption("remote","currentReceiver",this.F[a]);this.o.ib()};g.t(k8,g.TJ);g.h=k8.prototype;g.h.create=function(){qqa(g.wy(g.V(this.player)));this.u.push(g.Op("yt-remote-before-disconnect",this.xH,this));this.u.push(g.Op("yt-remote-connection-change",this.PJ,this));this.u.push(g.Op("yt-remote-receiver-availability-change",this.yy,this));this.u.push(g.Op("yt-remote-auto-connect",this.NJ,this));this.u.push(g.Op("yt-remote-receiver-resumed",this.MJ,this));this.yy()};
g.h.load=function(){this.player.cancelPlayback();g.TJ.prototype.load.call(this);this.o=new Z7(this,this.player,this.g);var a=(a=Y7())?a.currentTime:0;var b=V7()?new k7(Q7(),void 0):null;0==a&&b&&(a=f7(l7(b)));0!=a&&this.pd(a);g8(this,this.Uj,this.Uj);g.cX(this.player.app,6)};
g.h.unload=function(){this.player.M("mdxautoplaycanceled");this.l=this.i;g.rf(this.o,this.g);this.g=this.o=null;g.TJ.prototype.unload.call(this);g.cX(this.player.app,5)};
g.h.T=function(){g.Pp(this.u);g.TJ.prototype.T.call(this)};
g.h.Oe=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.o.Xw.apply(this.o,[a].concat(g.ea(c)))};
g.h.getAdState=function(){return this.km};
g.h.DC=function(){return this.loaded?this.o.suggestion:null};
g.h.Ee=function(){return this.g?l7(this.g).Ee:!1};
g.h.hasNext=function(){return this.g?l7(this.g).hasNext:!1};
g.h.pd=function(a,b){this.D=a||0;this.player.M("progresssync",a,b)};
g.h.getCurrentTime=function(){return this.D};
g.h.getProgressState=function(){var a=l7(this.g),b=this.player.getVideoData();return{allowSeeking:g.Q(g.V(this.player).experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.dc():!a.isAdPlaying()&&this.player.dc(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.u?a.l+d7(a):a.l,isAtLiveHead:1>=(a.u?a.i+d7(a):a.i)-this.getCurrentTime(),loaded:a.F,seekableEnd:a.u?a.i+d7(a):a.i,seekableStart:0<a.o?a.o+
d7(a):a.o}};
g.h.nextVideo=function(){this.g&&this.g.nextVideo()};
g.h.dn=function(){this.g&&this.g.dn()};
g.h.xH=function(a){1==a&&(this.B=this.g?l7(this.g):null)};
g.h.PJ=function(){var a=V7()?new k7(Q7(),void 0):null;if(a){var b=this.l;this.loaded&&this.unload();this.g=a;this.B=null;b.key!=this.i.key&&(this.l=b,this.load())}else g.qf(this.g),this.g=null,this.loaded&&(this.unload(),(a=this.B)&&a.videoId==this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,f7(a)));this.player.M("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.yy=function(){this.A=[this.i].concat(rqa());var a=R7()||this.i;l8(this,a);this.player.ma("onMdxReceiversChange")};
g.h.NJ=function(){var a=R7();l8(this,a)};
g.h.MJ=function(){this.l=R7()};
g.h.Yb=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.A;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?$6():l8(this,b)),this.loaded?this.l:this.i;case "quickCast":return 2==this.A.length&&"cast-selector-receiver"==this.A[1].key?(b&&$6(),!0):!1}};
g.h.xs=function(){this.g.xs()};
g.h.Nb=function(){return!1};
g.h.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.pU.remote=k8;})(_yt_player);
